# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-11 19:45
from django.db import connection, migrations


def convert_apps_to_utf8mb(apps, schema_editor):
    tables = []
    tables.extend([model._meta.db_table for model in apps.get_app_config('api').get_models()])
    tables.extend([model._meta.db_table for model in apps.get_app_config('cms').get_models()])
    tables.extend([model._meta.db_table for model in apps.get_app_config('notifications').get_models()])

    with connection.cursor() as cursor:
        db_alias = connection.settings_dict['NAME']  # should default to cloud_portal
        cursor.execute(f'ALTER DATABASE {db_alias} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;')
        for table in tables:
            cursor.execute(f'ALTER TABLE {table} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;')


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20180821_0209'),
        ('notifications', '0009_cloudnotification_customizations')
    ]

    operations = [
        migrations.RunPython(convert_apps_to_utf8mb),
    ]
