# Generated by Django 2.2 on 2019-06-21 02:04

import cloud.storage_backend
import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0063_auto_20190619_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalfile',
            name='file',
            field=models.FileField(max_length=1000, storage=cloud.storage_backend.MediaStorage(), upload_to=cms.models.rename_file),
        ),
    ]
