# Generated by Django 2.2 on 2019-06-21 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0064_auto_20190621_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='label',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='context',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Product'),
        ),
        migrations.AlterField(
            model_name='datastructure',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
