# Generated by Django 2.2 on 2019-06-24 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0065_auto_20190621_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='contact_email',
        ),
    ]
