# Generated by Django 2.2 on 2019-06-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0066_remove_product_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='advanced',
            field=models.BooleanField(default=True),
        ),
    ]
