# Generated by Django 2.2 on 2019-06-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0067_producttype_advanced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contexttemplate',
            name='skin',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
