# Generated by Django 2.2 on 2019-06-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0068_auto_20190625_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='deprecated',
            field=models.BooleanField(default=False),
        ),
    ]
