# Generated by Django 2.2 on 2019-07-09 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('cms', '0069_context_deprecated'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroupsToProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('product_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.ProductType')),
            ],
        ),
    ]
