# Generated by Django 2.2 on 2019-07-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0070_usergroupstoproducttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastructure',
            name='protected',
            field=models.BooleanField(default=False),
        ),
    ]
