# Generated by Django 2.2 on 2019-07-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0071_datastructure_protected'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastructure',
            name='placeholder',
            field=models.TextField(blank=True, default=''),
        ),
    ]
