# Generated by Django 2.2 on 2019-09-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0071_datastructure_protected'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('ready', models.BooleanField(default=False))
            ],
        ),
    ]
