# Generated by Django 2.2 on 2019-08-16 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('cms', '0073_auto_20190814_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='primary_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group'),
        ),

    ]
