# Generated by Django 2.2 on 2019-08-16 01:25

from django.db import migrations
from django.db.models import Q


def set_groups(apps, schema_editor):
    Product = apps.get_model('cms', 'Product')
    Group = apps.get_model('auth', 'Group')
    for product in Product.objects.all():
        # Try finding by name first
        group = Group.objects.filter(Q(name__icontains='Portal Manager') | Q(name__icontains='Developer'),
                                     usergroupstoproductpermissions__product=product).first()
        # If not found, try finding by permissions
        if not group:
            group = Group.objects.filter(
                usergroupstoproductpermissions__product=product,
                permissions__codename='change_product'
            ).first()

        if group and not hasattr(group, 'product'):
            product.primary_group = group
            product.save()


def unset_groups(apps, schema_editor):
    Product = apps.get_model('cms', 'Product')
    Product.objects.all().update(primary_group=None)


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0074_product_primary_group'),
    ]

    operations = [
        migrations.RunPython(set_groups, unset_groups)
    ]
