# Generated by Django 2.2 on 2019-08-21 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0075_populate_primary_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='context',
            name='product',
        ),
    ]
