# Generated by Django 2.2 on 2019-08-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0075_populate_primary_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='type',
            field=models.IntegerField(choices=[(0, 'Cloud Portal'), (1, 'Vms'), (2, 'Integration'), (3, 'Other'), (4, 'Article')], default=0),
        ),
    ]
