# Generated by Django 2.2 on 2019-08-21 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0076_remove_context_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customization',
            name='public_downloads',
        ),
        migrations.RemoveField(
            model_name='customization',
            name='public_release_history',
        ),
        migrations.RemoveField(
            model_name='customization',
            name='reveal_cloud_merge',
        ),
    ]
