# Generated by Django 2.2 on 2019-08-21 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0076_auto_20190819_2253'),
        ('cms', '0077_auto_20190821_0209'),
    ]

    operations = [
    ]
