# Generated by Django 2.2 on 2019-09-04 23:09

import cms.models
import django.db.models.deletion
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0078_merge_20190821_2058'),
    ]

    operations = [
        migrations.RenameModel('producttype', 'assettype'),

        migrations.RenameModel('product', 'asset'),
        migrations.AlterField(
            model_name='asset',
            name='product_type',
            field=models.ForeignKey(default=cms.models.get_integration_type, null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='cms.assettype'),
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='product_type',
            new_name='asset_type'
        ),

        migrations.AlterField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='created_asset', to=settings.AUTH_USER_MODEL),
        ),

        migrations.AlterField(
            model_name='context',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.assettype'),
        ),
        migrations.RenameField(
            model_name='context',
            old_name='product_type',
            new_name='asset_type'
        ),

        migrations.RenameModel('usergroupstoproductpermissions', 'usergroupstoassetpermissions'),
        migrations.AlterField(
            model_name='usergroupstoassetpermissions',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='cms.Asset'),
        ),
        migrations.RenameField(
            model_name='usergroupstoassetpermissions',
            old_name='product',
            new_name='asset'
        ),

        migrations.RenameModel('usergroupstoproducttype', 'usergroupstoassettype'),
        migrations.AlterField(
            model_name='usergroupstoassettype',
            name='product_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='cms.assettype'),
        ),
        migrations.RenameField(
            model_name='usergroupstoassettype',
            old_name='product_type',
            new_name='asset_type'
        ),

        migrations.AlterField(
            model_name='contentversion',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cms.Asset'),
        ),
        migrations.RenameField(
            model_name='contentversion',
            old_name='product',
            new_name='asset'
        ),

        migrations.RenameModel('productcustomizationreview', 'assetcustomizationreview'),
        migrations.AlterField(
            model_name='assetcustomizationreview',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='accepted_assetcustomizationreview', to=settings.AUTH_USER_MODEL),
        ),

        migrations.AlterField(
            model_name='externalfile',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='cms.Asset'),
        ),
        migrations.RenameField(
            model_name='externalfile',
            old_name='product',
            new_name='asset'
        ),

        migrations.AlterField(
            model_name='datarecord',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='cms.Asset'),
        ),
        migrations.RenameField(
            model_name='datarecord',
            old_name='product',
            new_name='asset'
        ),

        migrations.AlterModelOptions(
            name='asset',
            options={},
        ),
        migrations.AlterModelOptions(
            name='context',
            options={'ordering': ['order', 'id'],
                     'permissions': (('edit_content', 'Can edit content and send for review'),)},
        ),
        migrations.RemoveConstraint(
            model_name='assettype',
            name='Unique Product Type',
        ),
        migrations.AddConstraint(
            model_name='assettype',
            constraint=models.UniqueConstraint(fields=('name', 'type'), name='Unique Asset Type'),
        ),
    ]
