# Generated by Django 2.2 on 2019-09-05 19:19

import cms.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0078_merge_20190821_2058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductType',
            new_name='AssetType',
        ),
        migrations.RemoveConstraint(
            model_name='assettype',
            name='Unique Product Type',
        ),
        migrations.AddConstraint(
            model_name='assettype',
            constraint=models.UniqueConstraint(fields=('name', 'type'), name='Unique Asset Type'),
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Asset',
        ),
        migrations.RenameModel(
            old_name='ProductCustomizationReview',
            new_name='AssetCustomizationReview',
        ),
        migrations.RenameModel(
            old_name='UserGroupsToProductPermissions',
            new_name='UserGroupsToAssetPermissions',
        ),
        migrations.RenameModel(
            old_name='UserGroupsToProductType',
            new_name='UserGroupsToAssetType',
        ),
        migrations.AlterField(
            model_name='contentversion',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cms.Asset'),
        ),
        migrations.AlterField(
            model_name='datarecord',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Asset'),
        ),
        migrations.AlterField(
            model_name='externalfile',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Asset'),
        ),
        migrations.AlterField(
            model_name='usergroupstoassettype',
            name='product_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='cms.AssetType'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='created_asset', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assetcustomizationreview',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='accepted_assetcustomizationreview', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='product_type',
            new_name='asset_type',
        ),
        migrations.RenameField(
            model_name='contentversion',
            old_name='product',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='context',
            old_name='product_type',
            new_name='asset_type',
        ),
        migrations.RenameField(
            model_name='datarecord',
            old_name='product',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='externalfile',
            old_name='product',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='usergroupstoassetpermissions',
            old_name='product',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='usergroupstoassettype',
            old_name='product_type',
            new_name='asset_type',
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={},
        ),
        migrations.AlterModelOptions(
            name='context',
            options={'ordering': ['order', 'id'],
                     'permissions': (('edit_content', 'Can edit content and send for review'),)},
        ),
    ]
