# Generated by Django 2.2 on 2019-09-05 01:32
from django.contrib.auth.management import create_permissions
from django.db import migrations


def remove_permissions(apps, schema_editor):
    # Create permissions
    app_config = apps.get_app_config('cms')
    app_config.models_module = True
    create_permissions(app_config, verbosity=0)
    app_config.models_module = None

    Permissions = apps.get_model('auth.Permission')
    Groups = apps.get_model('auth.Group')
    asset = 'asset'
    product = 'product'
    product_permissions = Permissions.objects.filter(codename__icontains=product)
    for product_permission in product_permissions:
        product_codename = product_permission.codename
        asset_permission = Permissions.objects\
            .filter(codename=product_permission.codename.replace(product, asset)).first()
        if not asset_permission:
            continue
        for group in Groups.objects.filter(permissions__codename=product_codename):
            group.permissions.add(asset_permission)

    product_permissions.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0079_auto_20190905_1919'),
    ]

    operations = [
        migrations.RunPython(remove_permissions)
    ]
