# Generated by Django 2.2 on 2019-09-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0080_auto_20190905_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='protected',
            field=models.BooleanField(default=False),
        ),
    ]
