# Generated by Django 2.2 on 2019-09-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0081_asset_protected'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastructure',
            name='unique',
            field=models.BooleanField(default=False),
        ),
    ]
