# Generated by Django 2.2 on 2019-09-16 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0072_deploymentstatus'),
        ('cms', '0082_datastructure_unique'),
    ]

    operations = [
    ]
