# Generated by Django 2.2 on 2019-09-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0083_auto_20190916_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastructure',
            name='type',
            field=models.IntegerField(choices=[(0, 'Text'), (1, 'Image'), (2, 'HTML'), (3, 'Long Text'), (4, 'File'), (5, 'GUID'), (6, 'Select'), (7, 'External File'), (8, 'External Image'), (9, 'Check Box'), (10, 'Object'), (11, 'Array'), (12, 'Multiselect'), (13, 'Integer')], default=0),
        ),
    ]
