# Generated by Django 2.2 on 2019-09-30 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0084_auto_20190919_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'permissions': (('can_download_package', 'Can Download Asset Package'),)},
        ),
    ]
