# Generated by Django 2.2 on 2019-11-25 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0085_auto_20190930_2030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeploymentStatus',
        ),
    ]
