# Generated by Django 2.2 on 2019-12-02 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0086_delete_deploymentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contexttemplate',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Language'),
        ),
    ]
