# Generated by Django 2.2 on 2020-02-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0087_auto_20191202_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettype',
            name='type',
            field=models.IntegerField(choices=[(0, 'Cloud Portal'), (1, 'Vms'), (2, 'Integration'), (3, 'Other'), (4, 'Article'), (5, 'Agreement')], default=0),
        ),
    ]
