# Generated by Django 2.2 on 2020-02-29 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0088_auto_20200229_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributerAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_date', models.DateTimeField(auto_now_add=True)),
                ('accepted_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.AssetCustomizationReview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
