# Generated by Django 2.2 on 2020-04-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0091_auto_20200608_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastructure',
            name='fieldset',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
