# Generated by Django 2.2 on 2020-05-20 02:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0089_contributeragreement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContributerAgreement',
            new_name='ContributorAgreement',
        ),
    ]
