# Generated by Django 2.2 on 2020-06-08 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0090_auto_20200520_0245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customization',
            options={'permissions': (('access_customization', 'Can access customization'), ('access_integration_store', 'Can access the integration store'))},
        ),
    ]
