# Generated by Django 2.2 on 2020-05-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0090_datastructure_fieldset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('depth', models.IntegerField(blank=True, default=2)),
            ],
        ),
    ]
