# Generated by Django 2.2 on 2020-05-07 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0091_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=2048)),
                ('new_window', models.BooleanField(default=False)),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('authentication', models.IntegerField(choices=[(0, 'Logged Out'), (1, 'Logged In'), (2, 'Both')], default=2)),
                ('condition', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('available', models.ManyToManyField(blank=True, related_name='available_nodes', to='cms.Customization')),
                ('enabled', models.ManyToManyField(blank=True, related_name='enabled_nodes', to='cms.Customization')),
                ('parent_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Menu')),
                ('parent_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.MenuNode')),
            ],
        ),
    ]
