# Generated by Django 2.2 on 2020-05-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0092_menunode'),
    ]

    operations = [
        migrations.AddField(
            model_name='menunode',
            name='is_global',
            field=models.BooleanField(default=True, verbose_name='Global'),
        ),
    ]
