# Generated by Django 2.2 on 2020-05-13 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0093_menunode_is_global'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menunode',
            name='parent_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='cms.Menu'),
        ),
        migrations.AlterField(
            model_name='menunode',
            name='parent_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='cms.MenuNode'),
        ),
    ]
