# Generated by Django 2.2 on 2020-05-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0094_auto_20200513_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='menunode',
            name='touched',
            field=models.BooleanField(default=False),
        ),
    ]
