# Generated by Django 2.2 on 2020-07-22 00:26

from django.conf import settings
from django.db import migrations, connection


# Convert all cloud portal tables (and their columns) to utf8mb4 charset and utf8mb4_unicode_ci collation
def convert_tables_to_utf8mb4(apps, schema_editor):
    db_name = settings.DATABASES.get('default').get('NAME')
    with connection.cursor() as cursor:
        cursor.execute(f'SELECT TABLE_NAME FROM information_schema.tables WHERE TABLE_SCHEMA="{db_name}" AND TABLE_TYPE="BASE TABLE";')
        for table_name, in cursor.fetchall():
            cursor.execute(f'ALTER TABLE {db_name}.{table_name} CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;')


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0095_menunode_touched'),
    ]

    operations = [
        migrations.RunPython(convert_tables_to_utf8mb4, lambda x, y: None)
    ]
