# Generated by Django 2.2 on 2020-07-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0096_collation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettype',
            name='type',
            field=models.IntegerField(choices=[(0, 'Cloud Portal'), (1, 'Vms'), (2, 'Integration'), (3, 'Other'), (4, 'Article'), (5, 'Agreement'), (6, 'Documentation Page')], default=0),
        ),
    ]
