# Generated by Django 2.2 on 2020-08-07 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0097_auto_20200729_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menunode',
            name='display_name',
        ),
    ]
