# Generated by Django 2.2 on 2020-08-08 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0098_remove_menunode_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menunode',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Asset'),
        ),
    ]
