# Generated by Django 2.2 on 2020-09-18 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0099_menunode_asset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customization',
            options={'permissions': (('access_customization', 'Can access customization'), ('access_integration_store', 'Can access the integration store'), ('access_developers', 'Can see Developers pages'))},
        ),
    ]
