# Generated by Django 2.2 on 2020-09-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('cms', '0100_auto_20200918_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='menunode',
            name='permissions',
            field=models.ManyToManyField(blank=True, default=None, to='auth.Permission'),
        ),
    ]
