# Generated by Django 2.2 on 2020-11-11 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0101_menunode_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='menunode',
            name='next_item',
            field=models.BooleanField(default=False, verbose_name='Link to next'),
        ),
        migrations.AddField(
            model_name='menunode',
            name='related_assets',
            field=models.ManyToManyField(blank=True, default=None, related_name='nodes_related', to='cms.Asset'),
        ),
        migrations.AlterField(
            model_name='menunode',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='cms.Asset'),
        ),
    ]
