# Generated by Django 2.2 on 2020-11-20 03:08

from cms.models import AssetCustomizationReview as ReviewModel
from django.db import migrations


def migrate_records(apps, schema_editor):
    ContentVersion = apps.get_model('cms', 'ContentVersion')
    AssetCustomizationReview = apps.get_model('cms', 'AssetCustomizationReview')

    for version in ContentVersion.objects.filter(assetcustomizationreview=None).order_by('-id'):
        for record in version.datarecord_set.all():
            for customization in version.asset.customizations.all():
                first_accepted = AssetCustomizationReview.objects.filter(
                    version__asset=version.asset, customization=customization,
                    state=ReviewModel.REVIEW_STATES.accepted
                ).order_by('version', 'pk').first()
                if first_accepted:
                    if not first_accepted.version.datarecord_set.filter(
                            data_structure=record.data_structure, language=record.language
                    ):
                        record.version = first_accepted.version
                        record.save()
                        break


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0102_auto_20201111_0321'),
    ]

    operations = [
        migrations.RunPython(migrate_records, lambda *_: None)
    ]

