# Generated by Django 2.2 on 2020-11-24 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0103_migrate_datarecord_versions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZendeskCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='ZendeskSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Customization')),
            ],
        ),
        migrations.CreateModel(
            name='ZendeskSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.IntegerField(blank=True, null=True)),
                ('menu_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.MenuNode')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.ZendeskCategory')),
                ('parent_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.ZendeskSection')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.ZendeskSite')),
            ],
        ),
        migrations.AddField(
            model_name='zendeskcategory',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.ZendeskSite'),
        ),
        migrations.CreateModel(
            name='ZendeskArticleLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.ZendeskSite')),
            ],
        ),
        migrations.CreateModel(
            name='ZendeskArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField(blank=True, null=True)),
                ('author_id', models.IntegerField(blank=True, null=True)),
                ('comments_disabled', models.BooleanField()),
                ('created_at', models.CharField(blank=True, max_length=100)),
                ('draft', models.BooleanField()),
                ('edited_at', models.CharField(blank=True, max_length=100)),
                ('html_url', models.CharField(blank=True, max_length=1000)),
                ('permission_group_id', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField()),
                ('promoted', models.BooleanField()),
                ('title', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.CharField(blank=True, max_length=100)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Asset')),
                ('labels', models.ManyToManyField(to='cms.ZendeskArticleLabel')),
                ('menu_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.MenuNode')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.ZendeskSection')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.ZendeskSite')),
            ],
        ),
    ]
