# Generated by Django 2.2 on 2020-11-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0104_auto_20201124_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='zendeskcategory',
            name='name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='zendesksection',
            name='name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
