# Generated by Django 2.2 on 2020-11-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0105_auto_20201124_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='zendeskarticle',
            name='user_segment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
