# Generated by Django 2.2 on 2020-11-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0106_zendeskarticle_user_segment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='zendesksection',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zendeskarticle',
            name='article_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zendeskarticle',
            name='author_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zendeskarticle',
            name='permission_group_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zendeskarticle',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zendeskarticle',
            name='user_segment_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zendeskarticlelabel',
            name='label_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zendeskcategory',
            name='category_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zendesksection',
            name='section_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
