# Generated by Django 2.2 on 2020-11-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0107_auto_20201125_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='allow_porting',
            field=models.BooleanField(default=False),
        ),
    ]
