# Generated by Django 2.2 on 2020-12-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0108_menu_allow_porting'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='type',
            field=models.IntegerField(choices=[(0, 'Generic'), (1, 'Documentation Structure'), (2, 'Documentation Knowledgebase')], default=0),
        ),
    ]
