# Generated by Django 2.2 on 2020-12-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0109_menu_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='base_url',
            field=models.CharField(blank=True, help_text='Ex: developers', max_length=255),
        ),
    ]
