# Generated by Django 2.2 on 2020-12-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0110_menu_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, help_text='Ex: knowledgebase', max_length=255),
        ),
    ]
