# Generated by Django 2.2 on 2020-12-18 07:18

from django.db import migrations

initialTypes = [
    ('time', 'Time', 3),
    ('trial', 'Trial', 0),
    ('digital', 'Professional', 3),
    ('analog', 'Analog', 3),
    ('edge', 'Edge', 3),
    ('vmax', 'VMAX', 3),
    ('videowall', 'Video Wall', 3),
    ('analogencoder', 'Analog Encoder', 3),
    ('starter', 'Starter', 3),
    ('iomodule', 'IO Module', 3),
    ('bridge', 'Bridge', 3),
    ('nvr', 'NVR', 0)
]

def populate_licenses(apps, schema_editor):
    LicenseType = apps.get_model('cms', 'LicenseType')
    for (name, title, deactivations_allowed) in initialTypes:
        LicenseType(name=name, title=title,deactivations_allowed=deactivations_allowed).save()

class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0112_licensetype'),
    ]

    operations = [
        migrations.RunPython(populate_licenses)
    ]
