# Generated by Django 2.2 on 2021-01-18 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('cms', '0114_auto_20210113_0417'), ('cms', '0115_auto_20210114_2129'), ('cms', '0116_auto_20210114_2132'), ('cms', '0117_auto_20210115_0251')]

    dependencies = [
        ('cms', '0113_auto_20201218_0718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zendeskcategory',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='zendeskarticle',
            name='sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zendeskcategory',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zendeskcategory',
            name='sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zendesksection',
            name='sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='zendeskarticle',
            name='comments_disabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='zendeskarticle',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='zendeskarticle',
            name='promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='zendesksection',
            name='menu_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.MenuNode'),
        ),
    ]
