# Generated by Django 2.2 on 2021-01-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0113_auto_20201218_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='admin_config',
            field=models.TextField(default='{\n        "header": ["name","url","enabled","order","is_global","preview"],\n        "details": ["asset","icon","authentication"],\n        "advanced": ["related_assets","next_item","condition","permissions", "new_window"]\n    }', help_text='customizes admin view'),
        ),
    ]
