# Generated by Django 2.2 on 2021-02-05 02:01

from django.db import migrations, models
import uuid


def generate_uuids(apps, schema_editor):
    Asset = apps.get_model('cms', 'Asset')
    for asset in Asset.objects.all():
        asset.uuid = uuid.uuid4()
        asset.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0114_menu_admin_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(generate_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='asset',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
