# Generated by Django 2.2 on 2021-02-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('cms', '0115_merge_20210128_0349'), ('cms', '0116_auto_20210129_0502')]

    dependencies = [
        ('cms', '0114_menu_admin_config'),
        ('cms', '0114_zendesk_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='zendeskarticle',
            name='needs_sync',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zendesksection',
            name='needs_sync',
            field=models.BooleanField(default=False),
        ),
    ]
