# Generated by Django 2.2 on 2021-02-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0114_menu_admin_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
