# Generated by Django 2.2.17 on 2021-02-13 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0115_asset_uuid'),
        ('cms', '0115_menu_enabled'),
    ]

    operations = [
    ]
