# Generated by Django 2.2 on 2021-02-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('cms', '0117_menu_short_description'), ('cms', '0118_menu_title')]

    dependencies = [
        ('cms', '0116_merge_20210213_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='short_description',
            field=models.TextField(blank=True, help_text='Short description, used in meta tags for SEO if applicable'),
        ),
        migrations.AddField(
            model_name='menu',
            name='title',
            field=models.CharField(blank=True, help_text='Title, used in meta tags for SEO if applicable', max_length=255),
        ),
    ]
