# Generated by Django 2.2 on 2021-02-23 01:34

from django.db import migrations, models
import jsonfield.fields

STRUCTURES = [
    {
        'name': '%VMS_WIN_PATH%',
        'config': {
            'default_ds': '%companyName%',
            'advanced_ds': '%advanced.customWindowsInstallPath%',
            'vms_name_ds': '%vmsName%'
        }
    },
    {
        'name': '%VMS_LIN_PATH%',
        'config': {
            'default_ds': '%companyId%'
        }
    },
    {
        'name': '%VMS_COMPANY_ID%',
        'config': {
            'ds': '%companyId%'
        }
    },
    {
        'name': '%VMS_LIN_SERVICE_NAME%',
        'config': {
            'ds': '%companyId%'
        }
    }
]


def create_structures(apps, schema_editor):
    SpecialStructure = apps.get_model('cms', 'SpecialStructure')
    for struct in STRUCTURES:
        SpecialStructure.objects.create(**struct)


def delete_structures(apps, schema_editor):
    SpecialStructure = apps.get_model('cms', 'SpecialStructure')
    SpecialStructure.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0116_merge_20210213_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('config', jsonfield.fields.JSONField(blank=True, default={})),
            ],
        ),
        migrations.RunPython(create_structures, delete_structures)
    ]
