# Generated by Django 2.2.18 on 2021-02-19 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_asset_ds_pair(apps, schema_editor):
    if not settings.LOCAL_ENVIRONMENT and not settings.INSTANCE == 'LOCAL':
        ExternalFile = apps.get_model('cms', 'ExternalFile')
        AssetDsPair = apps.get_model('cms', 'AssetDsPair')
        external_files = ExternalFile.objects.order_by('md5')
        existing_files = {}
        for file in external_files:
            asset_ds_pair, _ = AssetDsPair.objects.get_or_create(asset=file.asset, data_structure=file.data_structure)
            md5 = str(file.md5)

            if not md5:
                try:
                    file.delete()
                except IOError:
                    pass
                continue

            old_url = str(file.file.name)
            new_url = None

            if md5 in existing_files:
                existing_files[md5].asset_ds_pair.add(asset_ds_pair)
                new_url = existing_files[md5].file.name
                if file.asset.asset_type.id == 6 and new_url and old_url != new_url:
                    for data_record in file.data_structure.datarecord_set.all():
                        if old_url in data_record.value:
                            data_record.value = data_record.value.replace(old_url, new_url)
                            data_record.save()
                if new_url:
                    file.delete()
                else:
                    existing_files[md5].file = file.file

            else:
                file.asset_ds_pair.add(asset_ds_pair)
                existing_files[md5] = file
        
        processed_files = ExternalFile.objects.all()

        for file in processed_files:
            if not file.asset_ds_pair.count():
                file.delete()

def reverse_add_asset_ds_pair(apps, schema_editor):
    if not settings.LOCAL_ENVIRONMENT and not settings.INSTANCE == 'LOCAL':
        ExternalFile = apps.get_model('cms', 'ExternalFile')
        external_files = ExternalFile.objects.all()
        for old_file in external_files:
            asset_ds_pairs = list(old_file.asset_ds_pair.all())
            if len(asset_ds_pairs) == 1:
                old_file.asset = asset_ds_pairs[0].asset
                old_file.data_structure = asset_ds_pairs[0].data_structure
                old_file.save()
                continue

            for asset_ds_pair in asset_ds_pairs:
                new_file = ExternalFile(file=old_file.file, md5=old_file.md5,
                    size=old_file.size, data_structure=asset_ds_pair.data_structure,
                    asset=asset_ds_pair.asset)
                new_file.save()
            old_file.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0117_specialstructure'),
    ]

    operations = [
        migrations.RunSQL(
            'DROP TABLE IF EXISTS cms_externalfile_asset_ds_pair;DROP TABLE IF EXISTS cms_assetdspair;',
            migrations.RunSQL.noop),
        migrations.AlterField(
            model_name='externalfile',
            name='md5',
            field=models.CharField(max_length=32),
        ),
        migrations.CreateModel(
            name='AssetDsPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Asset')),
                ('data_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.DataStructure')),
            ],
        ),
        migrations.AddField(
            model_name='externalfile',
            name='asset_ds_pair',
            field=models.ManyToManyField(blank=True, default=None, to='cms.AssetDsPair'),
        ),
        migrations.RunPython(add_asset_ds_pair, reverse_add_asset_ds_pair),
        migrations.RemoveField(
            model_name='externalfile',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='externalfile',
            name='data_structure',
        ),
        migrations.AlterField(
            model_name='externalfile',
            name='md5',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
