# Generated by Django 2.2.19 on 2021-03-02 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0117_menu_seo_fields'),
        ('cms', '0118_auto_20210219_2251'),
    ]

    operations = [
    ]
