# Generated by Django 2.2.19 on 2021-03-06 00:36

from django.db import migrations

STRUCTURES = [
    {
        'name': '%VMS_MAC_COMPANY_ID%',
        'config': {
            'ds': '%companyName%'
        }
    },
    {
        'name': '%VMS_WIN_EXECUTABLE%',
        'config': {
            'ds': '%vmsId%'
        }
    }
]


def create_structures(apps, schema_editor):
    SpecialStructure = apps.get_model('cms', 'SpecialStructure')
    for struct in STRUCTURES:
        SpecialStructure.objects.create(**struct)

    vms_lin = SpecialStructure.objects.filter(name='%VMS_LIN_PATH%').first()
    if vms_lin:
        default_ds = vms_lin.config.pop('default_ds', None)
        if default_ds:
            vms_lin.config['ds'] = default_ds
        vms_lin.save()


def remove_structures(apps, schema_editor):
    SpecialStructure = apps.get_model('cms', 'SpecialStructure')
    for struct in STRUCTURES:
        SpecialStructure.objects.filter(name=struct['name']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0119_merge_20210302_2032'),
    ]

    operations = [
        migrations.RunPython(create_structures, remove_structures)
    ]
