# Generated by Django 2.2.19 on 2021-03-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0120_branding_vars'),
    ]

    operations = [
        migrations.AddField(
            model_name='menunode',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='menunode',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
