# Generated by Django 2.2.18 on 2021-03-13 02:34

import json

from django.db import migrations, models
original_config = '{\n        "header": ["name","url","enabled","order","is_global","preview"],\n        "details": ["asset","icon","authentication"],\n        "advanced": ["related_assets","next_item","condition","permissions", "new_window"]\n    }'
updated_config = '{\n        "header": ["name","url","enabled","order","preview"],\n        "details": ["asset","icon","authentication"],\n        "advanced": ["related_assets","next_item","subtitle","condition","permissions", "new_window", "is_global"]\n    }'


def update_default_config(new_config, old_config):
    def update_handler(apps, schema_editor):
       Menu = apps.get_model('cms', 'Menu')
       old_config_sorted = json.dumps(json.loads(old_config), sort_keys=True)
       for menu in Menu.objects.all():
           current_config_sorted = json.dumps(json.loads(menu.admin_config), sort_keys=True)
           if old_config_sorted == current_config_sorted:
               menu.admin_config = new_config
               menu.save()

    return update_handler


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0121_auto_20210313_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='admin_config',
            field=models.TextField(
                default=updated_config, help_text='customizes admin view'),
        ),
        migrations.RunPython(update_default_config(updated_config, original_config),
                             update_default_config(original_config, updated_config)),
    ]
