# Generated by Django 2.2.19 on 2021-03-19 03:07

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0122_auto_20210313_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menunode',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=cms.models.node_asset_on_delete, related_name='nodes', to='cms.Asset'),
        ),
    ]
