# Generated by Django 2.2.18 on 2021-03-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0123_auto_20210319_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcustomizationreview',
            name='default_preview',
            field=models.TextField(blank=True),
        ),
    ]
