# Generated by Django 2.2.19 on 2021-04-15 02:09

from django.db import migrations

STRUCTURES = [
    {
        'name': '%VMS_ID%',
        'config': {
            'ds': '%vmsId%'
        }
    }
]


def create_structures(apps, schema_editor):
    SpecialStructure = apps.get_model('cms', 'SpecialStructure')
    for struct in STRUCTURES:
        struct_obj = SpecialStructure.objects.get_or_create(name=struct['name'])[0]
        struct_obj.config = struct['config']
        struct_obj.save()


def remove_structures(apps, schema_editor):
    SpecialStructure = apps.get_model('cms', 'SpecialStructure')
    for struct in STRUCTURES:
        SpecialStructure.objects.filter(name=struct['name']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0124_assetcustomizationreview_default_preview'),
    ]

    operations = [
        migrations.RunPython(create_structures, remove_structures)
    ]
