# Generated by Django 2.2.19 on 2021-04-19 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0115_merge_and_sync'),
        ('cms', '0125_vms_id'),
    ]

    operations = [
    ]
