# Generated by Django 2.2.20 on 2021-06-22 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0125_vms_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('values', jsonfield.fields.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('base_vms', models.ForeignKey(limit_choices_to={'asset_type__type': 1}, on_delete=django.db.models.deletion.CASCADE, to='cms.Asset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
