# Generated by Django 2.2.20 on 2021-06-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0126_customclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customclient',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
