# Generated by Django 2.2.19 on 2021-04-22 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0126_merge_20210419_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZendeskSyncLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_time', models.DateTimeField(auto_now_add=True)),
                ('menu', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.Menu')),
                ('zendesk_category', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.ZendeskCategory')),
                ('zendesk_site', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.ZendeskSite')),
            ],
        ),
        migrations.CreateModel(
            name='ZendeskSyncItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'In Progress'), (1, 'Success'), (2, 'Failed')], default=0)),
                ('asset', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.Asset')),
                ('menu_node', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.MenuNode')),
                ('sync_log', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='sync_items', to='cms.ZendeskSyncLog')),
                ('zendesk_article', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.ZendeskArticle')),
                ('zendesk_section', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.ZendeskSection')),
            ],
        ),
    ]
