# Generated by Django 2.2.20 on 2021-06-23 23:04

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0127_auto_20210623_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='custom_field_overrides',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
