# Generated by Django 2.2.19 on 2021-04-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0127_zendesksyncitem_zendesksynclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='zendesk_sync_enabled',
            field=models.ManyToManyField(blank=True, help_text='Used to select Customizations with Zendesk syncing enabled', to='cms.Customization'),
        ),
    ]
