# Generated by Django 2.2.19 on 2021-04-25 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0128_menu_zendesk_sync_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='zendesksyncitem',
            name='review',
            field=models.ForeignKey(default=1666, editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.AssetCustomizationReview'),
            preserve_default=False,
        ),
    ]
