# Generated by Django 2.2.20 on 2021-06-24 02:25

from cms.models import AssetType
from django.db import migrations

fields = {
    '%companyName%': {
        'label': 'Company Name',
        'type': 'text',
        'source': 'custom',
        'description': 'Developer name that users will see on About page of the client.'
    },
    '%customOpenSourceLibrariesUrl%': {
        'label': 'Custom url for the open source libraries',
        'type': 'text',
        'source': 'custom',
        'description': '',
        'optional': True
    },
    '%contact.companyUrl%': {
        'label': 'Company Web Page',
        'type': 'text',
        'source': 'custom',
        'description': 'URL that users will see on About page of the client.'
    },
    '%contact.supportAddress%': {'label': 'Support address', 'type': 'text', 'source': 'custom'}
}


def forward(apps, schema_editor):
    HistAssetType = apps.get_model('cms', 'AssetType')
    vms = HistAssetType.objects.filter(type=AssetType.ASSET_TYPES.vms, name='').first()
    if not vms:
        vms = HistAssetType.objects.create(type=AssetType.ASSET_TYPES.vms, name='')
    vms.custom_field_overrides = fields
    vms.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0128_assettype_custom_field_overrides'),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop)
    ]
