# Generated by Django 2.2.20 on 2021-07-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0129_vms_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='host',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
