# Generated by Django 2.2.19 on 2021-04-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0129_zendesksyncitem_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='zendeskcategory',
            name='general_section_title',
            field=models.CharField(default='General', max_length=500),
        ),
    ]
