# Generated by Django 2.2.19 on 2021-05-19 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0130_zendeskcategory_general_section_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zendeskarticle',
            name='menu_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.MenuNode'),
        ),
        migrations.AlterField(
            model_name='zendesksection',
            name='menu_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.MenuNode'),
        ),
    ]
