# Generated by Django 2.2.20 on 2021-07-03 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0130_customization_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='customclient',
            name='created_customization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Customization'),
        ),
    ]
