# Generated by Django 2.2.20 on 2021-06-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0131_auto_20210519_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='zendesksyncitem',
            name='failure_message',
            field=models.TextField(null=True),
        ),
    ]
