# Generated by Django 2.2.20 on 2021-07-09 22:13

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0131_customclient_created_customization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customclient',
            name='values',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
