# Generated by Django 2.2.24 on 2021-07-28 02:39

from django.db import migrations
from cms.models import AssetType


def forward(apps, schema_editor):
    HistAssetType = apps.get_model('cms', 'AssetType')
    vms = HistAssetType.objects.filter(type=AssetType.ASSET_TYPES.vms, name='').first()
    if not vms:
        vms = HistAssetType.objects.create(type=AssetType.ASSET_TYPES.vms, name='')
    vms.custom_field_overrides['fields']['%eulaVersion%'] = {'source': 'auto'}
    vms.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0133_cloud_host_fields'),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop)
    ]
