# Generated by Django 2.2.24 on 2021-07-29 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0134_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='data_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.DataStructure'),
        ),
    ]
