# Generated by Django 2.2.24 on 2021-08-05 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0135_flag_data_structure'),
        ('cms', '0134_eula_version'),
    ]

    operations = [
    ]
