# Generated by Django 2.2.24 on 2021-08-11 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0136_merge_20210805_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalfile',
            name='assest_ds_pair_last_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
