# Generated by Django 2.2.24 on 2021-08-09 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0136_merge_20210805_0126'),
        ('cms', '0132_zendesksyncitem_failure_message'),
        ('cms', '0137_externalfile_assest_ds_pair_last_added')
    ]

    operations = [
    ]
