# Generated by Django 2.2.24 on 2021-08-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0137_merge_20210809_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zendesksyncitem',
            name='state',
            field=models.IntegerField(choices=[(0, 'In Progress'), (1, 'Success'), (2, 'Failed'), (3, 'Canceled')], default=0),
        ),
    ]
