# Generated by Django 2.2.24 on 2021-08-19 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0138_auto_20210813_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customization',
            options={'ordering': ['name'], 'permissions': (('access_customization', 'Can access customization'), ('access_integration_store', 'Can access the integration store'), ('access_developers', 'Can see Developers pages'))},
        ),
    ]
