# Generated by Django 2.2.24 on 2021-09-23 17:41

from django.db import migrations
from cms.models import AssetType


def forward(apps, schema_editor):
    HistAssetType = apps.get_model('cms', 'AssetType')
    vms = HistAssetType.objects.filter(type=AssetType.ASSET_TYPES.vms, name='').first()
    vms.custom_field_overrides['cloudHostFields'].append('%cloudHost%')
    vms.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0139_auto_20210819_1228'),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop)
    ]
