# Generated by Django 2.2.24 on 2021-09-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0139_auto_20210819_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zendeskarticle',
            name='labels',
            field=models.ManyToManyField(blank=True, to='cms.ZendeskArticleLabel'),
        ),
    ]
