# Generated by Django 2.2.24 on 2021-10-12 02:50

from django.db import migrations
from cms.models import AssetType


def forward(apps, schema_editor):
    HistAssetType = apps.get_model('cms', 'AssetType')
    vms = HistAssetType.objects.filter(type=AssetType.ASSET_TYPES.vms, name='').first()
    vms.custom_field_overrides['fields']['%customOpenSourceLibrariesUrl%']['regex'] = 'urlField'
    vms.custom_field_overrides['fields']['%contact.companyUrl%']['regex'] = 'urlField'
    vms.custom_field_overrides['fields']['%contact.supportAddress%']['regex'] = 'emailField'
    vms.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0140_add_cloud_host_field'),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop)
    ]
