# Generated by Django 2.2.24 on 2021-10-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0140_add_cloud_host_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='zendeskarticle',
            name='ignore_structure',
            field=models.BooleanField(default=False),
        ),
    ]
