# Generated by Django 2.2.24 on 2021-10-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0141_add_regex'),
        ('cms', '0141_zendeskarticle_ignore_structure'),
    ]

    operations = [
    ]
