# Generated by Django 2.2.24 on 2021-10-27 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0140_auto_20210929_2320'),
        ('cms', '0142_merge_20211026_1902'),
    ]

    operations = [
    ]
