# Generated by Django 2.2.24 on 2021-11-11 04:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0143_merge_20211027_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Title of notification')),
                ('body', models.TextField(help_text='Body text of notification')),
                ('min_ts', models.DateTimeField(blank=True, help_text='Notification should not be shown before this time', null=True)),
                ('max_ts', models.DateTimeField(blank=True, help_text='Notification should not be shown after this time', null=True)),
                ('build_raw', models.FloatField(blank=True, help_text="Stores build as a float, don't use directly, instead use build attribute/kwarg", null=True)),
                ('url', models.URLField(blank=True, help_text='Where to navigate if notification is clicked', null=True)),
                ('users_viewed', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
