# Generated by Django 2.2.24 on 2021-11-12 06:09

from django.db import migrations


def add_get_all_review_emails_group(apps, schema_editor):
    Group = apps.get_model(
        'auth', 'Group')
    Permission = apps.get_model(
        'auth', 'Permission')
    ContentType = apps.get_model(
        'contenttypes', 'ContentType')
    GroupOptions = apps.get_model(
        'api', 'GroupOptions')
    Account = apps.get_model(
        'api', 'Account')

    all_review_emails_group, _ = Group.objects.get_or_create(
        name='Nx Internal - Receive All Review Emails')

    GroupOptions.objects.get_or_create(
        group=all_review_emails_group)

    permission, _ = Permission.objects.get_or_create(
        name='Receive All Review Emails', codename='get_all_review_emails', content_type=ContentType.objects.get_for_model(Account))

    all_review_emails_group.permissions.add(permission)


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0143_merge_20211027_2108'),
    ]

    operations = [
        migrations.RunPython(add_get_all_review_emails_group, migrations.RunPython.noop)
    ]
