# Generated by Django 2.2.24 on 2021-11-12 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0143_merge_20211027_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceScheduling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(help_text='Maintenance scheduled datetime')),
                ('components', models.TextField(help_text='List of affected components')),
                ('partner_message', models.TextField(help_text='List of affected partner features')),
                ('user_message', models.TextField(help_text='List of affected end user features')),
                ('custom', models.TextField(help_text='Custom message text')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceCompletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(help_text='Maintenance completed datetime')),
                ('partner_message', models.TextField(help_text='List of affected partner features')),
                ('custom', models.TextField(help_text='Custom message text')),
                ('scheduled_maintenance', models.ForeignKey(blank=True, help_text='Related scheduled maintenance', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.MaintenanceScheduling')),
            ],
        ),
    ]
