# Generated by Django 2.2.24 on 2021-11-12 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0144_maintenancecompletion_maintenancescheduling'),
        ('cms', '0144_portalnotification'),
    ]

    operations = [
    ]
