# Generated by Django 2.2.24 on 2021-11-12 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0145_merge_20211112_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancecompletion',
            name='portal_notification',
            field=models.ForeignKey(blank=True, help_text='Related notification', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.PortalNotification'),
        ),
        migrations.AddField(
            model_name='maintenancescheduling',
            name='portal_notification',
            field=models.ForeignKey(blank=True, help_text='Related notification', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.PortalNotification'),
        ),
    ]
