# Generated by Django 2.2.24 on 2021-12-03 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0144_auto_20211112_0609'),
        ('cms', '0146_auto_20211112_2219'),
    ]

    operations = [
    ]
