# Generated by Django 2.2.24 on 2021-11-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0146_auto_20211112_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettype',
            name='type',
            field=models.IntegerField(choices=[(0, 'Cloud Portal'), (1, 'Vms'), (2, 'Integration'), (3, 'Other'), (4, 'Article'), (5, 'Agreement'), (6, 'Documentation Page'), (7, 'Release Notes')], default=0),
        ),
    ]
