# Generated by Django 2.2.24 on 2021-12-02 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0147_auto_20211128_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zendesksyncitem',
            name='review',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.AssetCustomizationReview'),
        ),
    ]
