# Generated by Django 2.2.24 on 2021-12-03 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0147_merge_20211203_0549'),
        ('cms', '0147_auto_20211128_0049'),
    ]

    operations = [
    ]
