# Generated by Django 2.2.24 on 2021-12-03 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0146_externalfile_admin_upload'),
        ('cms', '0148_merge_20211203_0552'),
    ]

    operations = [
    ]
