# Generated by Django 2.2.24 on 2021-12-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0149_merge_20211203_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettype',
            name='type',
            field=models.IntegerField(choices=[(0, 'Cloud Portal'), (1, 'Vms'), (2, 'Integration'), (3, 'Other'), (4, 'Article'), (5, 'Agreement'), (6, 'Documentation Page'), (7, 'Release Notes'), (8, 'VMS Extension')], default=0),
        ),
        migrations.AlterField(
            model_name='datastructure',
            name='type',
            field=models.IntegerField(choices=[(0, 'Text'), (1, 'Image'), (2, 'HTML'), (3, 'Long Text'), (4, 'File'), (5, 'GUID'), (6, 'Select'), (7, 'External File'), (8, 'External Image'), (9, 'Check Box'), (10, 'Object'), (11, 'Array'), (12, 'Multiselect'), (13, 'Integer'), (14, 'Foreign Key')], default=0),
        ),
    ]
