# Generated by Django 2.2.24 on 2021-12-03 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0148_auto_20211202_0603'),
        ('cms', '0149_merge_20211203_1706'),
    ]

    operations = [
    ]
