# Generated by Django 2.2.24 on 2021-12-03 01:37

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0146_auto_20211112_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAPIJSON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='API display name', max_length=36)),
                ('version', models.CharField(help_text='API version', max_length=20)),
                ('content', jsonfield.fields.JSONField(default={}, help_text='API JSON')),
                ('type', models.IntegerField(choices=[(0, 'VMS')], default=0)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
