# Generated by Django 2.2.24 on 2021-12-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0149_merge_20211203_1706'),
        ('cms', '0150_openapijson'),
    ]

    operations = [
    ]
