# Generated by Django 2.2.24 on 2021-12-14 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0151_merge_20211206_1945'),
        ('cms', '0150_merge_20211203_1819'),
    ]

    operations = [
    ]
