# Generated by Django 2.2.24 on 2021-12-14 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0150_auto_20211210_0326'),
        ('cms', '0151_merge_20211206_1945'),
    ]

    operations = [
    ]
