# Generated by Django 2.2.24 on 2021-12-19 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0152_merge_20211214_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openapijson',
            options={'verbose_name': 'OpenAPI JSON'},
        ),
    ]
