# Generated by Django 2.2.25 on 2022-04-14 17:22

from django.db import migrations
from cms.models import AssetType


def forward(apps, schema_editor):
    HistAssetType = apps.get_model('cms', 'AssetType')
    vms = HistAssetType.objects.filter(type=AssetType.ASSET_TYPES.vms, name='').first()
    vms.custom_field_overrides['fields']['%contact.supportAddress%']['regex'] = 'emailOrUrlField'
    vms.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0153_auto_20211219_0135'),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop)
    ]
