# Generated by Django 2.2.25 on 2022-04-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0153_auto_20211219_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
