# Generated by Django 2.2.27 on 2022-04-28 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0154_custom_client_support'),
        ('cms', '0154_customization_enabled'),
    ]

    operations = [
    ]
