# Generated by Django 2.2.24 on 2022-01-25 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0153_auto_20211219_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openapijson',
            name='version',
            field=models.CharField(help_text='API version', max_length=13, validators=[django.core.validators.RegexValidator('^(\\d)\\.(\\d){1,2}\\.(\\d){1,2}\\.(\\d){5}$', 'Version should be in a valid format. ex: 5.12.11.11111')]),
        ),
    ]
