# Generated by Django 2.2.24 on 2022-02-01 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0155_auto_20220125_0030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customization',
            options={'ordering': ['name'], 'permissions': (('access_customization', 'Can access customization'), ('access_integration_store', 'Can access the integration store'), ('access_developers', 'Can see Developers pages'), ('view_integration_drafts', 'Can view all integration drafts'))},
        ),
    ]
