# Generated by Django 2.2.25 on 2022-02-09 07:09

from django.db import migrations

def remove_wrong_release_notes_context(apps, schema_editor):
    """Release notes struct was initially created with wrong name for context.
    """
    Context = apps.get_model('cms', 'Context')
    Context.objects.filter(name='releaseNotes').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0157_auto_20220201_1833'),
    ]

    operations = [
        migrations.RunPython(remove_wrong_release_notes_context)
    ]
