# Generated by Django 2.2.24 on 2022-02-15 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0152_merge_20211214_2309'),
        ('cms', '0157_auto_20220201_1833'),
    ]

    operations = [
    ]
