# Generated by Django 2.2.24 on 2022-02-15 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0158_auto_20220209_0709'),
        ('cms', '0158_merge_20220215_2157'),
    ]

    operations = [
    ]
