# Generated by Django 2.2.25 on 2022-02-22 07:04

import cloud.storage_backend
import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0159_merge_20220215_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalfile',
            name='file',
            field=models.FileField(blank=True, max_length=1000, null=True, storage=cloud.storage_backend.MediaStorage(), upload_to=cms.models.rename_file),
        ),
    ]
