# Generated by Django 2.2.27 on 2022-04-18 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0160_auto_20220222_0704'),
        ('cms', '0154_custom_client_support'),
    ]

    operations = [
    ]
