# Generated by Django 2.2.26 on 2022-04-04 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0161_merge_20220418_2252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpenAPIJSON',
            new_name='ReadOnlyAPI',
        ),
        migrations.AlterModelOptions(
            name='readonlyapi',
            options={'verbose_name': 'Readonly API'},
        ),
        migrations.RemoveField(
            model_name='readonlyapi',
            name='content',
        ),
        migrations.CreateModel(
            name='ReadOnlyAPIFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=46)),
                ('type', models.IntegerField(choices=[(0, 'Main JSON'), (1, 'Legacy JSON'), (2, 'Deprecated JSON'), (3, 'Preamble Markdown File'), (4, 'Changelog Markdown File')], default=0)),
                ('content', models.TextField(blank=True, help_text='File contents')),
                ('readonly_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.ReadOnlyAPI')),
            ],
        ),
    ]
