# Generated by Django 2.2.27 on 2022-04-29 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0155_merge_20220428_1940'),
        ('cms', '0162_auto_20220404_1533'),
    ]

    operations = [
    ]
