# Generated by Django 2.2.28 on 2022-07-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0163_merge_20220429_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='readonlyapi',
            name='manifest',
            field=models.TextField(default='[\n            {\n                "name": "Current API",\n                "sections": [\n                    {\n                        "name": "REST",\n                        "scheme": "openapi_v1.json"\n                    },\n                    {\n                        "name": "LEGACY",\n                        "scheme": "openapi_legacy.json"\n                    }\n                ]\n            },\n            {\n               "name": "Deprecated API",\n               "sections": [\n                    {\n                        "name": "LEGACY",\n                        "scheme": "openapi_deprecated.json"\n                    }\n                ]\n            }\n        ]', help_text='Content manifest'),
        ),
        migrations.AlterField(
            model_name='readonlyapifile',
            name='type',
            field=models.IntegerField(choices=[(0, 'JSON'), (1, 'Preamble Markdown File'), (2, 'Changelog Markdown File')], default=0),
        ),
        migrations.AlterModelOptions(
            name='readonlyapifile',
            options={'verbose_name': 'Readonly API file'},
        )
    ]
