# Generated by Django 2.2.28 on 2022-09-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0165_alter_asset_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readonlyapifile',
            name='filename',
            field=models.CharField(help_text="File name must exist in the readonlyAPI's manifest", max_length=46),
        ),
    ]
