# Generated by Django 4.1.2 on 2023-01-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0165_alter_asset_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readonlyapi',
            name='order',
            field=models.IntegerField(default=0, help_text='lower number will show up first in the dropdown'),
        ),
    ]
