# Generated by Django 4.0.8 on 2023-02-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0166_auto_20220913_1808'),
        ('cms', '0166_readonlyapi_order'),
    ]

    operations = [
    ]
