# Generated by Django 4.1.9 on 2023-07-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0167_merge_0166_auto_20220913_1808_0166_readonlyapi_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='additional_hosts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
