# Generated by Django 4.1.2 on 2023-06-26 19:58
from time import sleep

import waffle
from django.db import migrations
from rest_framework.test import APIRequestFactory
from cms.feature_flags.feature_flags import FLAGS


def setup_flags(apps, schema_editor):
    # do nothing. in case if this migration was already migrate on instance
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0168_customization_additional_hosts'),
    ]

    operations = [
        migrations.RunPython(setup_flags)
    ]
