# Generated by Django 4.1.10 on 2023-08-14 22:00
import waffle
from django.db import migrations, models
import django.db.models.deletion
from rest_framework.test import APIRequestFactory
from cms.feature_flags.feature_flags import FLAGS


def setup_flags(apps, schema_editor):
    Account = apps.get_model('api', model_name='account')
    user = Account.objects.filter(customization='default').last()
    request = APIRequestFactory().get('/')
    request.user = user
    request.META = request.session = {}
    request.CUSTOMIZATION = 'default'
    Group = apps.get_model('auth', model_name='Group')
    waffle.utils.get_cache().clear()
    for permission in ['access_developers', 'access_integration_store']:
        flag = getattr(FLAGS, permission)
        waffle.flag_is_active(request, flag)
        groups = Group.objects.filter(permissions__codename=permission)
        flag_object = apps.get_model('cms', model_name='Flag').objects.only("id", "everyone", "groups").get(name=flag)
        flag_object.everyone = None
        flag_object.groups.add(*list(groups.all()))
        flag_object.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0169_auto_20230626_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='customizations',
            field=models.ManyToManyField(blank=True, help_text='Select customization flag is enable for only. This setting does not work when "Enable for all customization" is set.', limit_choices_to={'enabled': True}, to='cms.customization', verbose_name='Enable for selected Customization'),
        ),
        migrations.AddField(
            model_name='flag',
            name='enable_all_customizations',
            field=models.BooleanField(default=False, help_text='Enable flag for all customization. To select customizations manually disable this field. Note! If flag is enabled previously applied customizations will be wiped.', verbose_name='Enable for all customization'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='data_structure',
            field=models.ForeignKey(blank=True, help_text='This feature is deprecated. Values are still considered valid. Use "Enable for all customization" and "Enable for selected Customization" to set flag for exact customizations instead.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.datastructure'),
        ),
        migrations.RunPython(setup_flags)
    ]
