# Generated by Django 4.1.11 on 2024-01-18 21:00

from django.db import migrations
import waffle

from rest_framework.test import APIRequestFactory
from cms.feature_flags.feature_flags import FLAGS

def setup_flags(apps, schema_editor):
    Account = apps.get_model('api', model_name='account')
    user = Account.objects.filter(customization='default').last()
    request = APIRequestFactory().get('/')
    request.user = user
    request.META = request.session = {}
    request.CUSTOMIZATION = 'default'
    Group = apps.get_model('auth', model_name='Group')
    waffle.utils.get_cache().clear()
    for permission in ['access_developers', 'access_integration_store']:
        flag = getattr(FLAGS, permission)
        waffle.flag_is_active(request, flag)
        groups = Group.objects.filter(permissions__codename=permission)
        flag_object = apps.get_model('cms', model_name='Flag').objects.only("id", "everyone", "groups").get(name=flag)
        flag_object.everyone = None
        flag_object.groups.add(*list(groups.all()))
        flag_object.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0170_flag_customizations_flag_enable_all_customizations_and_more'),
    ]

    operations = [
        migrations.RunPython(setup_flags)
    ]
