# Generated by Django 4.1.11 on 2024-05-21 20:31

from django.db import migrations
import logging

logger  = logging.getLogger(__name__)

NAME_MAP = {
    'Sync Unsaved Layouts across sessions': 'Layouts - Sync Unsaved Layouts Across Sessions',
    'Show dialog on removing item from layout': 'Layouts - Removing Item Confirmation Dialog',
    'Show resolution menu item for layouts': 'Layouts - Item Resolution',
    'Show resolution menu item for layout items': 'Layouts - Layout Resolution',
    'Show show status in the bottom right of the layout element': 'Layouts - Item Status (bottom right)',
    'Show cross system for layouts': 'Layouts - Cross System Layouts',
    'Show other systems to allow full cross system layout editing features for layouts': 'Layouts - Other Systems and Full Cross System Layout Editing',
    'Show updated cross system menu separated from the tree': 'Layouts - Updated Cross System Menu (separated from the tree)',
    'Show camera groups in the tree': 'Layouts - Tree Camera Groups',
    'Show fisheye de-warping': 'Layouts - Fisheye De-warping'
}


def rename_flags(apps, schema_editor):
    Flag = apps.get_model('cms', 'Flag')
    for old_name, new_name in NAME_MAP.items():
        # Check if old flag name is in DB
        if flag := Flag.objects.filter(name=old_name).first():
            # If new flag name is not in DB, rename old flag. Else, delete old flag.
            if not Flag.objects.filter(name=new_name).exists():
                flag.name = new_name
                flag.save()
                logger.info(f'Renamed {old_name} to {new_name}')
            else:
                flag.delete()
                logger.info(f'Flag {new_name} already exists. Deleting {old_name}')
        else:
            logger.info(f'Flag {old_name} was not found')


class Migration(migrations.Migration):
    dependencies = [
        ('cms', '0171_setup_flags'),
    ]

    operations = [
        migrations.RunPython(rename_flags, migrations.RunPython.noop)
    ]
