# Generated by Django 4.1.13 on 2024-10-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0172_rename_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='supports_mobile',
            field=models.BooleanField(default=True, help_text='Used to identify if the customization supports mobile builds.'),
        ),
    ]
