# Generated by Django 4.2.15 on 2024-09-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0172_rename_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readonlyapifile',
            name='type',
            field=models.IntegerField(choices=[(0, 'JSON'), (1, 'Preamble Markdown File'), (2, 'Changelog Markdown File'), (3, 'Markdown')], default=0),
        ),
    ]
