

EMAIL = f"{EMAIL_OWNER}"
PASSWORD = f"{BASE_PASSWORD}"
URL = f"{ENV}"

#TWOFA web elements

TWOFA_SWITCH = f"//nx-account-security-component//nx-switch//input[@id='TWOFA-active-status-switch']//.."
TWOFA_SWITCH_ENABLED = f"//nx-account-security-component//input[(@id='TWOFA-active-status-switch') and (@class='selected')]//.."
TWOFA_SWITCH_DISABLED = f"//nx-account-security-component//input[(@id='TWOFA-active-status-switch') and (@class='')]//.."
TWOFA_ENABLE_BUTTON = f"//button[contains(text(), {ENABLE_TWOFA_TEXT})]"
TWOFA_DISABLE_BUTTON = f"//button[contains(text(), {DISABLE_TWOFA_TEXT})]"
TWOFA_DISABLED_BADGE = f"//a[@id=tag-tag and contains(text(), {DISABLED_TEXT})]"
TWOFA_ENABLED_BADGE = f"//a[@id=tag-tag and contains(text(), {ENABLED_TEXT})]"
TWOFA_PASSWORD_MODAL_FIELD = f"//nx-two-fa-modal-content//input[@id='login_password']"
TWOFA_PASSWORD_MODAL_NEXT_BTN = f"//nx-two-fa-modal-content//svg-icon[contains(@data-src,'/images/icons/standard/arrow_right.svg')]"
TWOFA_QA_CODE_BTN = f"//nx-two-fa-modal-content//button[@id='qrMode']"
TWOFA_KEY_MODAL_NEXT_BTN = f"//nx-two-fa-modal-content//button[@id='nextWizardCode']"
TWOFA_KEY = f"//nx-two-fa-modal-content//nx-info-block//div[@class='block-section-values']//p[contains(@title,'Key')]"
TWOFA_TOTP_FIELD = f"//nx-two-fa-modal-content//input[@id='tfaCodeInput']"
TWOFA_VERIFY_BTN = f"//nx-two-fa-modal-content//button[text()={TWOFA_VERIFY_BTN_TEXT}]"
TWOFA_COPY_ALL_BTN = f"//nx-two-fa-modal-content//span[text()={TWOFA_COPY_ALL_BTN_TEXT}]"
TWOFA_OK_BTN = f"//nx-two-fa-modal-content//button[@id='wizardDone']"
TWOFA_BACKUP_CODE_ERROR = f"//nx-authorize-backup-code-component//p"
TWOFA_AUTH_CODE_FIELD = f"//nx-authorize-component//nx-authorize-auth-code-component//input[@id='authCode']"
TWOFA_AUTH_CODE_LOG_IN_BTN = f"//nx-authorize-component//nx-process-button//button[@type='submit']"
TWOFA_BACKUP_CODE_BTN = f"//nx-authorize-auth-code-component//span[text()={TWOFA_BACKUP_CODE_BTN_TEXT}]"
TWOFA_BACKUP_CODE_FIELD = f"//nx-authorize-backup-code-component//input[@id='backupCode']"
TWOFA_BACKUP_CODE_LOG_IN_BTN = f"//nx-authorize-backup-code-component//nx-process-button//button[@type='submit']"
TWOFA_CLOUD_ILLUSTRATION = f"//nx-authorize-component//nx-authorize-auth-code-component//svg-icon[contains(@data-src,'/images/placeholders/section/cloud_header.svg')]"
TWOFA_LOG_IN_CLOUD = f"//nx-authorize-component//nx-authorize-auth-code-component//h3[contains(text(),{TWOFA_LOG_IN_CLOUD_TEXT})]"
TWOFA_CODE_INSTRUCTIONS = f"//nx-authorize-component//nx-authorize-auth-code-component//p[text()={TWOFA_CODE_INSTRUCTIONS_TEXT}]"
TWOFA_BACK_BTN = f"//nx-authorize-component//nx-authorize-auth-code-component//span[text()={BACK_TEXT}]"
TWOFA_LOG_IN_BTN = f"//nx-authorize-auth-code-component//nx-process-button//button[text()={LOG_IN_BUTTON_TEXT}]"
TWOFA_BK_CLOUD_ILLUSTRATION = f"//nx-authorize-component//nx-authorize-backup-code-component//svg-icon[contains(@data-src,'/images/placeholders/section/cloud_header.svg')]"
TWOFA_BK_LOG_IN_CLOUD = f"//nx-authorize-component//nx-authorize-backup-code-component//h3[text()={TWOFA_LOG_IN_CLOUD_TEXT}]"
TWOFA_BK_CODE_FIELD = f"//nx-authorize-component//nx-authorize-backup-code-component//input[@id='backupCode']"
TWOFA_BK_CODE_HELP = f"//nx-authorize-component//nx-authorize-backup-code-component//span[text()={TWOFA_BACKUP_CODE_HELP_TEXT}]"
TWOFA_BK_CODE_CONTACT = f"//nx-authorize-component//nx-authorize-backup-code-component//a[text()={TWOFA_BACKUP_CODE_CONTACT_SUPPORT_TEXT}]"
TWOFA_BK_BACK_BTN = f"//nx-authorize-component//nx-authorize-backup-code-component//span[text()={BACK_TEXT}]"
TWOFA_AUTH_CODE_BTN = f"//nx-authorize-backup-code-component//span[text()={TWOFA_AUTH_CODE_BTN_TEXT}]"
TWOFA_BK_LOG_IN_BTN = f"//nx-authorize-backup-code-component//nx-process-button//button[text()={LOG_IN_BUTTON_TEXT}]"
TWOFA_VERIFICATION_CHECKBOX = f"//nx-account-security-component//nx-section//nx-checkbox//input[@id='skip-tfauth']/.."
TWOFA_VERIFICATION_CHECKBOX_ID = f"//nx-account-security-component//nx-section//nx-checkbox//input[@id='skip-tfauth']"
TWOFA_ERROR_LOGIN_CODE = f"//nx-authorize-component//nx-authorize-auth-code-component//p[contains(text(),{TWOFA_INVALID_CODE_TEXT})]"
TWOFA_DISABLE_MODAL_HEADER = f"//nx-two-fa-modal-content//h1[contains(text(),{TWOFA_DISABLE_MODAL_HEADER_TEXT})]"
TWOFA_DISABLE_MODAL_DESCRIPTION = f"//nx-two-fa-modal-content//form//label[text()={TWOFA_DISABLE_MODAL_DESCRIPTION_TEXT}]"
TWOFA_DISABLE_MODAL_BTN = f"//nx-two-fa-modal-content//button[@type='submit']"
TWOFA_DISABLE_MODAL_RED_COLOR = f"rgba(194, 38, 38, 1)"
TWOFA_DISABLE_MODAL_CANCEL_BTN = f"//nx-two-fa-modal-content//button[(@type=reset) or contains(text(),{CANCEL_BUTTON_TEXT})]"
TWOFA_SECURITY_PAGE_SAVE_BTN = f"//nx-account-security-component//nx-apply//button[@type='submit']"
TWOFA_SECURITY_PAGE_CANCEL_BTN = f"//nx-account-security-component//nx-apply//button[@type='reset']"
TWOFA_SETTINGS_MODAL_HEADER = f"//nx-two-fa-modal-content//h1[contains(text(),{TWOFA_SETTINGS_MODAL_HEADER_TEXT})]"
TWOFA_SETTINGS_MODAL_DESCRIPTION_UNCHECK = f"//nx-two-fa-modal-content//p[text()={TWOFA_SETTINGS_MODAL_DESCRIPTION_TEXT2}]"
TWOFA_SETTINGS_MODAL_DESCRIPTION_CHECK = f"//nx-two-fa-modal-content//p[text()={TWOFA_SETTINGS_MODAL_DESCRIPTION_TEXT1}]"
TWOFA_SETTINGS_MODAL_ON_INSTRUCTIONS = f"//nx-two-fa-modal-content//label[text()={TWOFA_SETTINGS_MODAL_INST_ON_TEXT}]"
TWOFA_SETTINGS_MODAL_OFF_INSTRUCTIONS = f"//nx-two-fa-modal-content//label[text()={TWOFA_SETTINGS_MODAL_INST_OFF_TEXT}]"
TWOFA_SETTINGS_MODAL_APPLY_BTN = f"//nx-two-fa-modal-content//nx-process-button//child::div"
TWOFA_SETTINGS_MODAL_CANCEL_BTN = f"//nx-two-fa-modal-content//button[(@type=reset) or contains(text(),{CANCEL_BUTTON_TEXT})]"