
PASSWORD = f"{BASE_PASSWORD}"
URL = f"{ENV}"
CZECH_ALERT = f"Váš účet byl úspěšně uložen"

#account web elements

ACCOUNT_DROPDOWN = f"//header//div[@data-testid='accountSettingsDropdown']/preceding-sibling::button"
ACCOUNT_SETTINGS_BUTTON = f"//header//li//a[@href = '/account']"
LOG_IN_CLOSE_BUTTON = f"//button[@data-dismiss='modal']"
ACCOUNT_SETTINGS_BUTTON_SYSTEM = f"//button[@id='accountSettingsButton']"
ACCOUNT_EMAIL = f"//a[@id='settings']"
ACCOUNT_FIRST_NAME = f"//form[@name='accountForm']//input[@id='firstName']"
ACCOUNT_LAST_NAME = f"//form[@name='accountForm']//input[@id='lastName']"
ACCOUNT_LANGUAGE_DROPDOWN = f"//nx-language-select//button[@id='dropdownMenuButton']"
ACCOUNT_SAVE = f"//nx-process-button[@data-testid='saveSettingsBtn']//button"
ACCOUNT_CANCEL = f"//nx-cancel-button[@data-testid='cancelSettingsBtn']//button"
TEST_FIRST_NAME = f"mark"
TEST_LAST_NAME = f"hamill"
DELETE_ACCOUNT_BUTTON = f"//nx-account-settings-component//nx-block//button[@id='accountSettingsDeleteButton']"
DELETE_ACCOUNT_DISABLED_BUTTON = f"//nx-account-settings-component//nx-block//button[@disabled and contains(text(), {DELETE_ACCOUNT_TEXT})]"
CAN_NOT_DELETE_ACCOUNT_TOOLTIP = f"//nx-tooltip-component/div[contains(@class,'tooltip-body')]"
DELTE_ACCOUNT_DIALOG = f"//nx-modal-delete-cloud-user-content"
DELETE_ACCOUNT_MODAL_BUTTON = f"{DELTE_ACCOUNT_DIALOG}//nx-process-button//button[contains(text(),{DELETE_BUTTON_TEXT})]"
DELETE_ACCOUNT_CANCEL_BUTTON = f"{DELTE_ACCOUNT_DIALOG}//button[contains(text(),{CANCEL_BUTTON_TEXT})]"
DELETE_ACCOUNT_CLOSE_BUTTON = f"{DELTE_ACCOUNT_DIALOG}//button[contains(@class,close)]"
DELETE_ACCOUNT_HEADER = f"{DELTE_ACCOUNT_DIALOG}//h1[contains(text(),{DELETE_ACCOUNT_HEADER_TEXT})]"
DELETE_ACCOUNT_INFO = f"{DELTE_ACCOUNT_DIALOG}//span[contains(text(),{DELETE_ACCOUNT_INFO_TEXT})]"
DELETE_ACCOUNT_PASSWORD_INPUT = f"{DELTE_ACCOUNT_DIALOG}//form[@name=deleteCloudUserForm]//input[@id=password]"
DELETE_ACCOUNT_PASSWORD_LABEL = f"{DELTE_ACCOUNT_DIALOG}//form[@name=deleteCloudUserForm]//input[@id=password]/preceding-sibling::label[@for=password and contains(text(),{DELETE_ACCOUNT_PASSWORD_LABEL_TEXT})]"
DELETE_ACCOUNT_PASSWORD_ERROR = f"{DELTE_ACCOUNT_DIALOG}//form[@name=deleteCloudUserForm]//input[@id=password]/following-sibling::label[@for=password]"

APPLY_CHANGES_BUTTON = f"{MODAL_APPLY_DIALOG}//button[contains(text(), {APPLY_CHANGES_BUTTON_TEXT})]"
DISCARD_CHANGES_BUTTON = f"{MODAL_APPLY_DIALOG}//button[contains(text(), {DISCARD_CHANGES_BUTTON_TEXT})]"
CANCEL_CHANGES_BUTTON = f"{MODAL_APPLY_DIALOG}//button[contains(text(), {CANCEL_BUTTON_TEXT})]"
APPLY_CHANGES_QUESTION = f"//h1[contains(text(), {APPLY_CHANGES_QUESTION_TEXT})]"
NO_UNSAVED_CHANGES = f"//nx-apply//div[contains(text(), {NO_UNSAVED_CHANGES_TEXT})]"
APPLY_CHANGES_CLOSE_BUTTON = f"{MODAL_APPLY_DIALOG}//button[@class=close]"