
EMAIL = f"{EMAIL_OWNER}"
EMAIL_INVALID = f"aodehurgjaegir"
PASSWORD = f"{BASE_PASSWORD}"
URL = f"{ENV}"
GOOD_EMAIL = f"{EMAIL_VIEWER}"
GOOD_EMAIL_UNREGISTERED = f"{EMAIL_UNREGISTERED}"
GOOD_PASSWORD = f"{BASE_PASSWORD}"
BAD_PASSWORD = f"adrhartjad"