
URL = f"{ENV}"
PASSWORD = f"{BASE_PASSWORD}"
EXISTING_EMAIL = f"{EMAIL_VIEWER}"
RESTORE_PASS_EMAIL_IS_REQUIRED = f"//p[contains(@class,error-label) and contains(text(),{ENTER_EMAIL_TEXT})]"
EMAIL_INVALID = f"//p[contains(@class,error-label) and contains(text(),{EMAIL_INVALID_TEXT})]"
EMAIL_IS_REQUIRED_HEBREW = f"//p[contains(@class,error-label) and contains(text(),{EMAIL_IS_REQUIRED_TEXT})]"
EMAIL_INVALID_HEBREW = f"//p[contains(@class,error-label) and contains(text(),{EMAIL_INVALID_TEXT})]"
FORM_WITH_ERROR = f"//form[@name='restorePasswordWithCode']//nx-password-input[contains(@class,'ng-invalid')]//input"

RESET_PASSWORD_FORM = f"//form[@name='resetForm' or @name='resetPasswordForm']"
RESET_PASSWORD_OK_BUTTON = f"{RESET_PASSWORD_FORM}//button[contains(@class,btn btn-primary)]"
RESTORE_PASSWORD_EMAIL_INPUT = f"//nx-authorize-reset-request-component//input[@type='email' and @id='resetPasswordEmail']"
RESET_PASSWORD_BUTTON = f"//button[contains(@class,btn btn-primary) and contains(text(), {RESET_PASSWORD_BUTTON_TEXT})]"
RESET_NEXT_BUTTON = f"//button[contains(@class,btn btn-primary) and contains(text(), {NEXT_TEXT})]"
RESET_PASSWORD_INPUT = f"{RESET_PASSWORD_FORM}//input[@id=resetPassword]"
FORGOT_PASSWORD_BUTTON = f"//button//span[contains(text(),{FORGOT_PASSWORD_TEXT})]"
SAVE_PASSWORD = f"{RESET_PASSWORD_FORM}/following-sibling::footer//button[contains(@class,btn btn-primary)]"
RESET_EMAIL_SENT_MESSAGE = f"//nx-authorize-reset-request-component//p[contains(text(),{RESET_EMAIL_SENT_MESSAGE_TEXT})]"
RESET_EMAIL_SENT_MESSAGE_HEBREW = f"//h1/span[contains(text(),{RESET_EMAIL_SENT_MESSAGE_TEXT})]"
RESET_SUCCESS_MESSAGE = f"//h3[contains(text(),{RESET_SUCCESS_MESSAGE_TEXT})]"
RESET_SUCCESS_INSTRUCTION = f"//p[contains(text(),{RESET_SUCCESS_INSTRUCTION_TEXT})]"
RESET_SUCCESS_LOG_IN_LINK = f"//div[contains(@class,'process-success')]//a[contains(@class,'btn btn-primary')]"
RESET_EYE_ICON_OPEN = f"{RESET_PASSWORD_FORM}{EYE_ICON_OPEN}"
RESET_EYE_ICON_CLOSED = f"{RESET_PASSWORD_FORM}{EYE_ICON_CLOSED}"
RESET_PASSWORD_EMAIL_SENT = f"{RESET_PASSWORD_FORM}/div[contains(@class, email-sent)]"
RESET_LOGIN_BUTTON = f"{RESET_PASSWORD_FORM}/following-sibling::footer//button[contains(text(), {LOG_IN_BUTTON_TEXT})]"
RESET_BACK_BUTTON = f"//nx-authorize-component//nx-authorize-reset-request-component//footer//span[text()={BACK_TEXT}]/.."
RESET_PASSWORD_COMP_HEADER = f"//nx-authorize-component//nx-authorize-reset-request-component//header//h3[text()={RESET_PASSWORD_BUTTON_TEXT}]"