[tool.poetry]
name = "cloud-portal"
version = "23.2"
description = "Nx Cloud Portal"
authors = []
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "~3.8.10"

[tool.poetry.group.prod]
optional = true

[tool.poetry.group.prod.dependencies]
asgiref = "^3.5.2" #BSD 3-Clause "New" or "Revised" License|https://github.com/django/asgiref|https://github.com/django/asgiref/blob/main/LICENSE
boto3 = "~1.9.132" #Apache-2.0 License|https://github.com/boto/boto3|https://github.com/boto/boto3/blob/develop/LICENSE
botocore = "1.12.253" #Apache-2.0 License|https://github.com/boto/botocore|https://github.com/boto/botocore/blob/develop/LICENSE.txt
cssutils = "1.0.2" # GNU Lesser General Public License v3.0|https://github.com/jaraco/cssutils|https://github.com/jaraco/cssutils/blob/main/COPYING
Django = "4.1.11" #BSD 3-Clause "New" or "Revised" License|https://github.com/django/django|https://github.com/django/django/blob/main/LICENSE
django-admin-tools = "0.9.2" #MIT License|https://github.com/django-admin-tools/django-admin-tools|https://github.com/django-admin-tools/django-admin-tools/blob/master/LICENSE
django_autocomplete_light = "~3.9.7" #MIT License|https://github.com/yourlabs/django-autocomplete-light|https://github.com/yourlabs/django-autocomplete-light/blob/master/LICENSE
django-celery-beat = "~2.5.0" #BSD 3-Clause "New" or "Revised" License|https://github.com/celery/django-celery-beat|https://github.com/celery/django-celery-beat/blob/main/LICENSE
django_celery_results = "~2.5.1" #BSD 3-Clause "New" or "Revised" License|https://github.com/celery/django-celery-results|https://github.com/celery/django-celery-results/blob/main/LICENSE
django-cleanup = "5.1.0" #MIT License|https://github.com/un1t/django-cleanup|https://github.com/un1t/django-cleanup/blob/master/LICENSE
django-cors-headers = "3.7.0" #MIT License|https://github.com/adamchainz/django-cors-headers|https://github.com/adamchainz/django-cors-headers/blob/main/LICENSE
django_csv_exports = "1.0.5" #BSD 2-Clause "Simplified" License|https://github.com/rochapps/django-csv-exports|https://github.com/rochapps/django-csv-exports/blob/master/LICENSE
django-model-utils = "~4.3.1" #BSD 3-Clause "New" or "Revised" License|https://github.com/jazzband/django-model-utils|https://github.com/jazzband/django-model-utils/blob/master/LICENSE.txt
django_mock_queries = "~2.2.0" #MIT License|https://github.com/stphivos/django-mock-queries|https://github.com/stphivos/django-mock-queries/blob/master/LICENSE.txt
django_nested_admin = "~4.0.2" #BSD 2-Clause "Simplified" License|https://github.com/theatlantic/django-nested-admin|https://github.com/theatlantic/django-nested-admin/blob/master/LICENSE
django-npm = "1.0.0" #MIT License|https://github.com/kevin1024/django-npm|https://github.com/kevin1024/django-npm/blob/master/LICENSE
django-oauth-toolkit = "~2.3.0" #Copyright (c) 2013, Massimiliano Pippi, Federico Frenguelli and contributors|https://github.com/jazzband/django-oauth-toolkit|https://github.com/jazzband/django-oauth-toolkit/blob/master/LICENSE
django_proxy = "1.2.2" #Copyright Mjumbe Wawatu Ukweli|https://github.com/mjumbewu/django-proxy|https://github.com/mjumbewu/django-proxy/blob/master/README.md#license
django_push_notifications = "3.0.0" #MIT License|https://github.com/jazzband/django-push-notifications|https://github.com/jazzband/django-push-notifications/blob/master/LICENSE
django-redis = "5.2.0" #Copyright (c) 2011-2016 Andrey Antukh <niwi@niwi.nz>|https://github.com/jazzband/django-redis|https://github.com/jazzband/django-redis/blob/master/LICENSE
django_rest_hooks = "1.7.1" #ISC License|https://github.com/zapier/django-rest-hooks|https://github.com/zapier/django-rest-hooks/blob/master/LICENSE.md
django-silk = "~5.0.3" #MIT License|https://github.com/jazzband/django-silk|https://github.com/jazzband/django-silk/blob/master/LICENSE
django-storages = "~1.13.2" #BSD 3-Clause "New" or "Revised" License|https://github.com/jschneier/django-storages|https://github.com/jschneier/django-storages/blob/master/LICENSE
django-tinymce = "3.5.0" #MIT License|https://github.com/jazzband/django-tinymce|https://github.com/jazzband/django-tinymce/blob/master/LICENSE.txt
# since version 2.6. flag.is_active() must have read_only keyword argument
django_waffle = "~2.5.0" #BSD 3-Clause "New" or "Revised" License|https://github.com/django-waffle/django-waffle|https://github.com/django-waffle/django-waffle/blob/master/LICENSE
# in newer version there is issue with scheme generation for drf_yasg
djangorestframework = "~3.12.0" #Copyright © 2011-present, Encode OSS Ltd.|https://github.com/encode/django-rest-framework|https://github.com/encode/django-rest-framework/blob/master/LICENSE.md
drf_yasg = "1.21.0" #BSD 3-Clause "New" or "Revised" License|https://github.com/axnsan12/drf-yasg|https://github.com/axnsan12/drf-yasg/blob/master/LICENSE.rst
gunicorn = "~20.1.0" #2009-2023 (c) Benoît Chesneau|https://github.com/benoitc/gunicorn|https://github.com/benoitc/gunicorn/blob/master/LICENSE
html2text = "2020.1.16" #GNU General Public License v3.0|https://github.com/aaronsw/html2text
html_sanitizer = "1.7.0" #MIT License|https://github.com/mganss/HtmlSanitizer|https://github.com/mganss/HtmlSanitizer/blob/master/LICENSE.md
htmlmin = "0.1.12" #MIT License|https://github.com/voku/HtmlMin|https://github.com/voku/HtmlMin/blob/master/LICENSE
httpx = "0.24.0" #MIT License|https://github.com/projectdiscovery/httpx|https://github.com/projectdiscovery/httpx/blob/main/LICENSE.md
importlib_metadata = "1.6.0" #Apache 2.0 License|https://github.com/python/importlib_metadata|https://github.com/python/importlib_metadata/blob/main/LICENSE
inlinestyler = "0.2.1" #BSD 3-Clause "New" or "Revised" License|https://github.com/dlanger/inlinestyler|https://github.com/dlanger/inlinestyler/blob/master/LICENSE
jsonfield = "3.1.0" #MIT License|https://github.com/rpkilby/jsonfield|https://github.com/rpkilby/jsonfield/blob/master/LICENSE
libsass = "0.20.1" #Copyright (C) 2012-2016 by the Sass Open Source Foundation|https://github.com/sass/libsass|https://github.com/sass/libsass/blob/master/LICENSE
meilisearch = "0.17.0" #MIT License|https://github.com/meilisearch/meilisearch|https://github.com/meilisearch/meilisearch/blob/main/LICENSE
mistletoe = "0.7.2" #MIT License|https://github.com/miyuchina/mistletoe|https://github.com/miyuchina/mistletoe/blob/master/LICENSE
mysqlclient = "2.2.4" #GNU General Public License v2.0|https://github.com/PyMySQL/mysqlclient|https://github.com/PyMySQL/mysqlclient/blob/main/LICENSE
MarkupSafe = "^1.1.1" #BSD 3-Clause "New" or "Revised" License|https://github.com/pallets/markupsafe|https://github.com/pallets/markupsafe/blob/main/LICENSE.rst
numpy="==1.22.0" #BSD 3-Clause "New" or "Revised" License|https://github.com/numpy/numpy|https://github.com/numpy/numpy/blob/main/LICENSE.txt
packaging = "~21.0" #Apache 2.0 License and BSD License|https://github.com/pypa/packaging|https://github.com/pypa/packaging/blob/main/LICENSE
pandas="==1.5.0" #BSD 3-Clause "New" or "Revised" License|https://github.com/pandas-dev/pandas|https://github.com/pandas-dev/pandas/blob/main/LICENSE
Pillow = "9.0.1" #HPND License|https://github.com/python-pillow/Pillow|https://github.com/python-pillow/Pillow/blob/main/LICENSE
py = "1.10.0" #Unknown License|https://github.com/codebasics/py| ################################################################
pycurl = "~7.44.1" #GNU Lesser General Public License v2.1|https://github.com/pycurl/pycurl|https://github.com/pycurl/pycurl/blob/master/COPYING-LGPL
pystache = "0.6.0" #MIT License|https://github.com/defunkt/pystache|https://github.com/defunkt/pystache/blob/master/LICENSE
pytz = "*" #MIT License|https://github.com/stub42/pytz|https://github.com/stub42/pytz/blob/master/LICENSE.txt
PyYAML = "6.0.1" #MIT License|https://github.com/yaml/pyyaml|https://github.com/yaml/pyyaml/blob/main/LICENSE
redis = "4.5.5" #BSD 3-Clause "New" or "Revised" License|https://github.com/redis/redis|https://github.com/redis/redis/blob/unstable/COPYING
requests = "~2.31.0" #Apache License 2.0|https://github.com/psf/requests|https://github.com/psf/requests/blob/main/LICENSE
"ruamel.yaml" = "0.17.21" #MIT License|https://github.com/commx/ruamel-yaml|https://github.com/commx/ruamel-yaml/blob/master/LICENSE
"ruamel.yaml.clib" = "0.2.6" #MIT License|https://github.com/ruamel/yaml.clib|https://github.com/ruamel/yaml.clib/blob/master/LICENSE
uvicorn = "~0.22.0" #BSD 3-Clause "New" or "Revised" License|https://github.com/encode/uvicorn|https://github.com/encode/uvicorn/blob/master/LICENSE.md
zenpy = "2.0.40" #GNU General Public License v3.0|https://github.com/facetoe/zenpy|https://github.com/facetoe/zenpy/blob/master/LICENSE
etils = { version = "*", extras = ["edc"] } #Apache License 2.0|https://github.com/google/etils|https://github.com/google/etils/blob/main/LICENSE

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
mock = "^4.0.3"
model_bakery = "^1.12.0"
pyfakefs = "^4.5.1"
pytest = "~6.2.4"
pytest-asyncio = "~0.20.3"
pytest-cov = "~2.12.1"
pytest-django = "~4.5.0"
pytest-env = "~0.6.2"
pytest-mock = "^3.6.1"
moto = { version = "^2", extras = ["s3"] }

[tool.poetry.group.front-build]
optional = true

[tool.poetry.group.front-build.dependencies]
cssutils = "1.0.2"
htmlmin = "0.1.12"
inlinestyler = "0.2.1"
nodeenv = "1.6.0"
PyYAML = "6.0.1"
pystache = "0.6.0"

[tool.poetry.group.local]
optional = true

[tool.poetry.group.local.dependencies]

[tool.poetry.group.piplicenses]
optional=true

[tool.poetry.group.piplicenses.dependencies]
pip-licenses = "4.2.0"

[[tool.poetry.source]]
name = "pypi-remote"
url = "http://artifactory.us.nxteam.dev/artifactory/api/pypi/pypi-remote/simple"
priority = "default"

[[tool.poetry.source]]
name = "pypi-local"
url = "http://artifactory.us.nxteam.dev/artifactory/api/pypi/pypi-local/simple"
priority = "primary"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
