from itertools import cycle
import json
import os
from uuid import UUID

from model_bakery import baker
from model_bakery.recipe import seq
import pytest

from django.conf import settings

from cms.models import Menu, MenuNode


@pytest.fixture()
def menu_with_nodes(db):
    name = 'auto_menu'
    title = 'Auto Menu'
    short_description = 'This is an auto menu'
    customizations = baker.make('Customization', name=seq('cust'), _quantity=3)
    authentication = [MenuNode.AUTH_CHOICES.logged_out, MenuNode.AUTH_CHOICES.logged_in, MenuNode.AUTH_CHOICES.both]
    conditions = ['%DEVELOPERS_ENABLED%', '', '']

    uuid_count = 0

    def _next_uuid():
        nonlocal uuid_count
        uuid_count += 1
        return UUID(int=uuid_count)

    def _make_menu(depth=3, nodes_per=3):
        def _create_nodes(parent_menu=None, parent_node=None, level=1):
            prefix = f'{parent_node.name}_node' if parent_node else 'node'
            assets = [*baker.make('Asset', name=seq(f'{prefix}_asset'), uuid=_next_uuid, _quantity=3), None]
            related_assets = list(
                baker.make('Asset', name=seq(f'{prefix}_related_asset_'), uuid=_next_uuid, _quantity=3))
            icons = [*(f'icon{i + 1}.svg' for i in range(3)), '']

            common = {
                'name': seq(prefix),
                'url': seq(prefix, suffix='_url'),
                'subtitle': seq(prefix, suffix='_subtitle'),
                'asset': cycle(assets),
                'next_item': cycle((True, False, False)),
                'new_window': cycle((False, True, False)),
                'icon': cycle(icons),
                'authentication': cycle(authentication),
                'parent_menu': parent_menu,
                'parent_node': parent_node,
                'condition': cycle(conditions),
                'touched': True,
                'is_global': True,
                'order': iter(range(nodes_per))
            }

            num_first_set = min(nodes_per, 2)
            num_second_set = nodes_per - num_first_set

            nodes = list(baker.make(
                'MenuNode', _quantity=num_first_set, **common,
                related_assets=related_assets, available=customizations,
                enabled=customizations[0:1],
            ))
            if num_second_set > 0:
                nodes.extend(baker.make(
                    'MenuNode', _quantity=num_second_set, **common
                ))

            for node in nodes:
                if level + 1 <= depth:
                    _create_nodes(parent_node=node, level=level + 1)

        menu = baker.make('Menu', name=name, depth=depth, title=title, short_description=short_description)
        _create_nodes(parent_menu=menu, level=1)
        return menu

    return _make_menu


@pytest.fixture()
def expected_menu_dict():
    return {
        'assets': ['00000000-0000-0000-0000-000000000010',
                   '00000000-0000-0000-0000-000000000005',
                   '00000000-0000-0000-0000-00000000002f',
                   '00000000-0000-0000-0000-00000000001f',
                   '00000000-0000-0000-0000-00000000000b',
                   '00000000-0000-0000-0000-00000000004a',
                   '00000000-0000-0000-0000-000000000015',
                   '00000000-0000-0000-0000-000000000021',
                   '00000000-0000-0000-0000-00000000001b',
                   '00000000-0000-0000-0000-000000000007',
                   '00000000-0000-0000-0000-000000000004',
                   '00000000-0000-0000-0000-000000000043',
                   '00000000-0000-0000-0000-000000000001',
                   '00000000-0000-0000-0000-000000000009',
                   '00000000-0000-0000-0000-00000000000e',
                   '00000000-0000-0000-0000-00000000003e',
                   '00000000-0000-0000-0000-00000000002e',
                   '00000000-0000-0000-0000-000000000027',
                   '00000000-0000-0000-0000-000000000042',
                   '00000000-0000-0000-0000-00000000004d',
                   '00000000-0000-0000-0000-000000000023',
                   '00000000-0000-0000-0000-00000000002b',
                   '00000000-0000-0000-0000-000000000048',
                   '00000000-0000-0000-0000-000000000013',
                   '00000000-0000-0000-0000-000000000040',
                   '00000000-0000-0000-0000-000000000012',
                   '00000000-0000-0000-0000-00000000000f',
                   '00000000-0000-0000-0000-000000000026',
                   '00000000-0000-0000-0000-00000000000c',
                   '00000000-0000-0000-0000-000000000030',
                   '00000000-0000-0000-0000-000000000036',
                   '00000000-0000-0000-0000-000000000045',
                   '00000000-0000-0000-0000-000000000014',
                   '00000000-0000-0000-0000-00000000001d',
                   '00000000-0000-0000-0000-00000000004e',
                   '00000000-0000-0000-0000-00000000002d',
                   '00000000-0000-0000-0000-00000000003f',
                   '00000000-0000-0000-0000-000000000016',
                   '00000000-0000-0000-0000-000000000044',
                   '00000000-0000-0000-0000-000000000008',
                   '00000000-0000-0000-0000-00000000001a',
                   '00000000-0000-0000-0000-00000000003b',
                   '00000000-0000-0000-0000-000000000031',
                   '00000000-0000-0000-0000-000000000039',
                   '00000000-0000-0000-0000-000000000035',
                   '00000000-0000-0000-0000-00000000003d',
                   '00000000-0000-0000-0000-000000000038',
                   '00000000-0000-0000-0000-00000000004b',
                   '00000000-0000-0000-0000-000000000018',
                   '00000000-0000-0000-0000-000000000003',
                   '00000000-0000-0000-0000-000000000025',
                   '00000000-0000-0000-0000-000000000028',
                   '00000000-0000-0000-0000-000000000020',
                   '00000000-0000-0000-0000-000000000047',
                   '00000000-0000-0000-0000-000000000006',
                   '00000000-0000-0000-0000-000000000041',
                   '00000000-0000-0000-0000-00000000000d',
                   '00000000-0000-0000-0000-00000000002c',
                   '00000000-0000-0000-0000-000000000046',
                   '00000000-0000-0000-0000-000000000037',
                   '00000000-0000-0000-0000-000000000017',
                   '00000000-0000-0000-0000-00000000003c',
                   '00000000-0000-0000-0000-00000000001c',
                   '00000000-0000-0000-0000-000000000034',
                   '00000000-0000-0000-0000-00000000003a',
                   '00000000-0000-0000-0000-00000000000a',
                   '00000000-0000-0000-0000-000000000011',
                   '00000000-0000-0000-0000-00000000001e',
                   '00000000-0000-0000-0000-00000000002a',
                   '00000000-0000-0000-0000-000000000033',
                   '00000000-0000-0000-0000-00000000004c',
                   '00000000-0000-0000-0000-000000000032',
                   '00000000-0000-0000-0000-000000000022',
                   '00000000-0000-0000-0000-000000000029',
                   '00000000-0000-0000-0000-000000000024',
                   '00000000-0000-0000-0000-000000000002',
                   '00000000-0000-0000-0000-000000000019',
                   '00000000-0000-0000-0000-000000000049'],
        'depth': 3,
        'name': 'auto_menu',
        'nodes': [{
                      'asset': 'node_asset1',
                      'asset_type': 2,
                      'authentication': 0,
                      'available': ['cust1', 'cust2', 'cust3'],
                      'condition': '%DEVELOPERS_ENABLED%',
                      'enabled': [],
                      'icon': 'icon1.svg',
                      'is_global': True,
                      'name': 'node1',
                      'new_window': False,
                      'next_item': True,
                      'nodes': [{
                                    'asset': 'node1_node_asset1',
                                    'asset_type': 2,
                                    'authentication': 0,
                                    'available': ['cust1', 'cust2', 'cust3'],
                                    'condition': '%DEVELOPERS_ENABLED%',
                                    'enabled': [],
                                    'icon': 'icon1.svg',
                                    'is_global': True,
                                    'name': 'node1_node1',
                                    'new_window': False,
                                    'next_item': True,
                                    'nodes': [{
                                                  'asset': 'node1_node1_node_asset1',
                                                  'asset_type': 2,
                                                  'authentication': 0,
                                                  'available': ['cust1', 'cust2', 'cust3'],
                                                  'condition': '%DEVELOPERS_ENABLED%',
                                                  'enabled': [],
                                                  'icon': 'icon1.svg',
                                                  'is_global': True,
                                                  'name': 'node1_node1_node1',
                                                  'new_window': False,
                                                  'next_item': True,
                                                  'nodes': [],
                                                  'order': 0,
                                                  'permissions': [],
                                                  'related_assets': [('node1_node1_node_related_asset_1',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000010'),
                                                                     ('node1_node1_node_related_asset_2',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000011'),
                                                                     ('node1_node1_node_related_asset_3',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000012')],
                                                  'subtitle': 'node1_node1_node1_subtitle',
                                                  'touched': True,
                                                  'url': 'node1_node1_node1_url',
                                                  'uuid': '00000000-0000-0000-0000-00000000000d'
                                              },
                                              {
                                                  'asset': 'node1_node1_node_asset2',
                                                  'asset_type': 2,
                                                  'authentication': 1,
                                                  'available': ['cust1', 'cust2', 'cust3'],
                                                  'condition': '',
                                                  'enabled': [],
                                                  'icon': 'icon2.svg',
                                                  'is_global': True,
                                                  'name': 'node1_node1_node2',
                                                  'new_window': True,
                                                  'next_item': False,
                                                  'nodes': [],
                                                  'order': 1,
                                                  'permissions': [],
                                                  'related_assets': [('node1_node1_node_related_asset_1',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000010'),
                                                                     ('node1_node1_node_related_asset_2',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000011'),
                                                                     ('node1_node1_node_related_asset_3',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000012')],
                                                  'subtitle': 'node1_node1_node2_subtitle',
                                                  'touched': True,
                                                  'url': 'node1_node1_node2_url',
                                                  'uuid': '00000000-0000-0000-0000-00000000000e'
                                              },
                                              {
                                                  'asset': 'node1_node1_node_asset3',
                                                  'asset_type': 2,
                                                  'authentication': 2,
                                                  'available': [],
                                                  'condition': '',
                                                  'enabled': [],
                                                  'icon': 'icon3.svg',
                                                  'is_global': True,
                                                  'name': 'node1_node1_node3',
                                                  'new_window': False,
                                                  'next_item': False,
                                                  'nodes': [],
                                                  'order': 2,
                                                  'permissions': [],
                                                  'related_assets': [],
                                                  'subtitle': 'node1_node1_node3_subtitle',
                                                  'touched': True,
                                                  'url': 'node1_node1_node3_url',
                                                  'uuid': '00000000-0000-0000-0000-00000000000f'
                                              }],
                                    'order': 0,
                                    'permissions': [],
                                    'related_assets': [('node1_node_related_asset_1',
                                                        2,
                                                        '00000000-0000-0000-0000-00000000000a'),
                                                       ('node1_node_related_asset_2',
                                                        2,
                                                        '00000000-0000-0000-0000-00000000000b'),
                                                       ('node1_node_related_asset_3',
                                                        2,
                                                        '00000000-0000-0000-0000-00000000000c')],
                                    'subtitle': 'node1_node1_subtitle',
                                    'touched': True,
                                    'url': 'node1_node1_url',
                                    'uuid': '00000000-0000-0000-0000-000000000007'
                                },
                                {
                                    'asset': 'node1_node_asset2',
                                    'asset_type': 2,
                                    'authentication': 1,
                                    'available': ['cust1', 'cust2', 'cust3'],
                                    'condition': '',
                                    'enabled': [],
                                    'icon': 'icon2.svg',
                                    'is_global': True,
                                    'name': 'node1_node2',
                                    'new_window': True,
                                    'next_item': False,
                                    'nodes': [{
                                                  'asset': 'node1_node2_node_asset1',
                                                  'asset_type': 2,
                                                  'authentication': 0,
                                                  'available': ['cust1', 'cust2', 'cust3'],
                                                  'condition': '%DEVELOPERS_ENABLED%',
                                                  'enabled': [],
                                                  'icon': 'icon1.svg',
                                                  'is_global': True,
                                                  'name': 'node1_node2_node1',
                                                  'new_window': False,
                                                  'next_item': True,
                                                  'nodes': [],
                                                  'order': 0,
                                                  'permissions': [],
                                                  'related_assets': [('node1_node2_node_related_asset_1',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000016'),
                                                                     ('node1_node2_node_related_asset_2',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000017'),
                                                                     ('node1_node2_node_related_asset_3',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000018')],
                                                  'subtitle': 'node1_node2_node1_subtitle',
                                                  'touched': True,
                                                  'url': 'node1_node2_node1_url',
                                                  'uuid': '00000000-0000-0000-0000-000000000013'
                                              },
                                              {
                                                  'asset': 'node1_node2_node_asset2',
                                                  'asset_type': 2,
                                                  'authentication': 1,
                                                  'available': ['cust1', 'cust2', 'cust3'],
                                                  'condition': '',
                                                  'enabled': [],
                                                  'icon': 'icon2.svg',
                                                  'is_global': True,
                                                  'name': 'node1_node2_node2',
                                                  'new_window': True,
                                                  'next_item': False,
                                                  'nodes': [],
                                                  'order': 1,
                                                  'permissions': [],
                                                  'related_assets': [('node1_node2_node_related_asset_1',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000016'),
                                                                     ('node1_node2_node_related_asset_2',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000017'),
                                                                     ('node1_node2_node_related_asset_3',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000018')],
                                                  'subtitle': 'node1_node2_node2_subtitle',
                                                  'touched': True,
                                                  'url': 'node1_node2_node2_url',
                                                  'uuid': '00000000-0000-0000-0000-000000000014'
                                              },
                                              {
                                                  'asset': 'node1_node2_node_asset3',
                                                  'asset_type': 2,
                                                  'authentication': 2,
                                                  'available': [],
                                                  'condition': '',
                                                  'enabled': [],
                                                  'icon': 'icon3.svg',
                                                  'is_global': True,
                                                  'name': 'node1_node2_node3',
                                                  'new_window': False,
                                                  'next_item': False,
                                                  'nodes': [],
                                                  'order': 2,
                                                  'permissions': [],
                                                  'related_assets': [],
                                                  'subtitle': 'node1_node2_node3_subtitle',
                                                  'touched': True,
                                                  'url': 'node1_node2_node3_url',
                                                  'uuid': '00000000-0000-0000-0000-000000000015'
                                              }],
                                    'order': 1,
                                    'permissions': [],
                                    'related_assets': [('node1_node_related_asset_1',
                                                        2,
                                                        '00000000-0000-0000-0000-00000000000a'),
                                                       ('node1_node_related_asset_2',
                                                        2,
                                                        '00000000-0000-0000-0000-00000000000b'),
                                                       ('node1_node_related_asset_3',
                                                        2,
                                                        '00000000-0000-0000-0000-00000000000c')],
                                    'subtitle': 'node1_node2_subtitle',
                                    'touched': True,
                                    'url': 'node1_node2_url',
                                    'uuid': '00000000-0000-0000-0000-000000000008'
                                },
                                {
                                    'asset': 'node1_node_asset3',
                                    'asset_type': 2,
                                    'authentication': 2,
                                    'available': [],
                                    'condition': '',
                                    'enabled': [],
                                    'icon': 'icon3.svg',
                                    'is_global': True,
                                    'name': 'node1_node3',
                                    'new_window': False,
                                    'next_item': False,
                                    'nodes': [{
                                                  'asset': 'node1_node3_node_asset1',
                                                  'asset_type': 2,
                                                  'authentication': 0,
                                                  'available': ['cust1', 'cust2', 'cust3'],
                                                  'condition': '%DEVELOPERS_ENABLED%',
                                                  'enabled': [],
                                                  'icon': 'icon1.svg',
                                                  'is_global': True,
                                                  'name': 'node1_node3_node1',
                                                  'new_window': False,
                                                  'next_item': True,
                                                  'nodes': [],
                                                  'order': 0,
                                                  'permissions': [],
                                                  'related_assets': [('node1_node3_node_related_asset_1',
                                                                      2,
                                                                      '00000000-0000-0000-0000-00000000001c'),
                                                                     ('node1_node3_node_related_asset_2',
                                                                      2,
                                                                      '00000000-0000-0000-0000-00000000001d'),
                                                                     ('node1_node3_node_related_asset_3',
                                                                      2,
                                                                      '00000000-0000-0000-0000-00000000001e')],
                                                  'subtitle': 'node1_node3_node1_subtitle',
                                                  'touched': True,
                                                  'url': 'node1_node3_node1_url',
                                                  'uuid': '00000000-0000-0000-0000-000000000019'
                                              },
                                              {
                                                  'asset': 'node1_node3_node_asset2',
                                                  'asset_type': 2,
                                                  'authentication': 1,
                                                  'available': ['cust1', 'cust2', 'cust3'],
                                                  'condition': '',
                                                  'enabled': [],
                                                  'icon': 'icon2.svg',
                                                  'is_global': True,
                                                  'name': 'node1_node3_node2',
                                                  'new_window': True,
                                                  'next_item': False,
                                                  'nodes': [],
                                                  'order': 1,
                                                  'permissions': [],
                                                  'related_assets': [('node1_node3_node_related_asset_1',
                                                                      2,
                                                                      '00000000-0000-0000-0000-00000000001c'),
                                                                     ('node1_node3_node_related_asset_2',
                                                                      2,
                                                                      '00000000-0000-0000-0000-00000000001d'),
                                                                     ('node1_node3_node_related_asset_3',
                                                                      2,
                                                                      '00000000-0000-0000-0000-00000000001e')],
                                                  'subtitle': 'node1_node3_node2_subtitle',
                                                  'touched': True,
                                                  'url': 'node1_node3_node2_url',
                                                  'uuid': '00000000-0000-0000-0000-00000000001a'
                                              },
                                              {
                                                  'asset': 'node1_node3_node_asset3',
                                                  'asset_type': 2,
                                                  'authentication': 2,
                                                  'available': [],
                                                  'condition': '',
                                                  'enabled': [],
                                                  'icon': 'icon3.svg',
                                                  'is_global': True,
                                                  'name': 'node1_node3_node3',
                                                  'new_window': False,
                                                  'next_item': False,
                                                  'nodes': [],
                                                  'order': 2,
                                                  'permissions': [],
                                                  'related_assets': [],
                                                  'subtitle': 'node1_node3_node3_subtitle',
                                                  'touched': True,
                                                  'url': 'node1_node3_node3_url',
                                                  'uuid': '00000000-0000-0000-0000-00000000001b'
                                              }],
                                    'order': 2,
                                    'permissions': [],
                                    'related_assets': [],
                                    'subtitle': 'node1_node3_subtitle',
                                    'touched': True,
                                    'url': 'node1_node3_url',
                                    'uuid': '00000000-0000-0000-0000-000000000009'
                                }],
                      'order': 0,
                      'permissions': [],
                      'related_assets': [('node_related_asset_1',
                                          2,
                                          '00000000-0000-0000-0000-000000000004'),
                                         ('node_related_asset_2',
                                          2,
                                          '00000000-0000-0000-0000-000000000005'),
                                         ('node_related_asset_3',
                                          2,
                                          '00000000-0000-0000-0000-000000000006')],
                      'subtitle': 'node1_subtitle',
                      'touched': True,
                      'url': 'node1_url',
                      'uuid': '00000000-0000-0000-0000-000000000001'
                  },
                  {
                      'asset': 'node_asset2',
                      'asset_type': 2,
                      'authentication': 1,
                      'available': ['cust1', 'cust2', 'cust3'],
                      'condition': '',
                      'enabled': [],
                      'icon': 'icon2.svg',
                      'is_global': True,
                      'name': 'node2',
                      'new_window': True,
                      'next_item': False,
                      'nodes': [{
                                    'asset': 'node2_node_asset1',
                                    'asset_type': 2,
                                    'authentication': 0,
                                    'available': ['cust1', 'cust2', 'cust3'],
                                    'condition': '%DEVELOPERS_ENABLED%',
                                    'enabled': [],
                                    'icon': 'icon1.svg',
                                    'is_global': True,
                                    'name': 'node2_node1',
                                    'new_window': False,
                                    'next_item': True,
                                    'nodes': [{
                                                  'asset': 'node2_node1_node_asset1',
                                                  'asset_type': 2,
                                                  'authentication': 0,
                                                  'available': ['cust1', 'cust2', 'cust3'],
                                                  'condition': '%DEVELOPERS_ENABLED%',
                                                  'enabled': [],
                                                  'icon': 'icon1.svg',
                                                  'is_global': True,
                                                  'name': 'node2_node1_node1',
                                                  'new_window': False,
                                                  'next_item': True,
                                                  'nodes': [],
                                                  'order': 0,
                                                  'permissions': [],
                                                  'related_assets': [('node2_node1_node_related_asset_1',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000028'),
                                                                     ('node2_node1_node_related_asset_2',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000029'),
                                                                     ('node2_node1_node_related_asset_3',
                                                                      2,
                                                                      '00000000-0000-0000-0000-00000000002a')],
                                                  'subtitle': 'node2_node1_node1_subtitle',
                                                  'touched': True,
                                                  'url': 'node2_node1_node1_url',
                                                  'uuid': '00000000-0000-0000-0000-000000000025'
                                              },
                                              {
                                                  'asset': 'node2_node1_node_asset2',
                                                  'asset_type': 2,
                                                  'authentication': 1,
                                                  'available': ['cust1', 'cust2', 'cust3'],
                                                  'condition': '',
                                                  'enabled': [],
                                                  'icon': 'icon2.svg',
                                                  'is_global': True,
                                                  'name': 'node2_node1_node2',
                                                  'new_window': True,
                                                  'next_item': False,
                                                  'nodes': [],
                                                  'order': 1,
                                                  'permissions': [],
                                                  'related_assets': [('node2_node1_node_related_asset_1',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000028'),
                                                                     ('node2_node1_node_related_asset_2',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000029'),
                                                                     ('node2_node1_node_related_asset_3',
                                                                      2,
                                                                      '00000000-0000-0000-0000-00000000002a')],
                                                  'subtitle': 'node2_node1_node2_subtitle',
                                                  'touched': True,
                                                  'url': 'node2_node1_node2_url',
                                                  'uuid': '00000000-0000-0000-0000-000000000026'
                                              },
                                              {
                                                  'asset': 'node2_node1_node_asset3',
                                                  'asset_type': 2,
                                                  'authentication': 2,
                                                  'available': [],
                                                  'condition': '',
                                                  'enabled': [],
                                                  'icon': 'icon3.svg',
                                                  'is_global': True,
                                                  'name': 'node2_node1_node3',
                                                  'new_window': False,
                                                  'next_item': False,
                                                  'nodes': [],
                                                  'order': 2,
                                                  'permissions': [],
                                                  'related_assets': [],
                                                  'subtitle': 'node2_node1_node3_subtitle',
                                                  'touched': True,
                                                  'url': 'node2_node1_node3_url',
                                                  'uuid': '00000000-0000-0000-0000-000000000027'
                                              }],
                                    'order': 0,
                                    'permissions': [],
                                    'related_assets': [('node2_node_related_asset_1',
                                                        2,
                                                        '00000000-0000-0000-0000-000000000022'),
                                                       ('node2_node_related_asset_2',
                                                        2,
                                                        '00000000-0000-0000-0000-000000000023'),
                                                       ('node2_node_related_asset_3',
                                                        2,
                                                        '00000000-0000-0000-0000-000000000024')],
                                    'subtitle': 'node2_node1_subtitle',
                                    'touched': True,
                                    'url': 'node2_node1_url',
                                    'uuid': '00000000-0000-0000-0000-00000000001f'
                                },
                                {
                                    'asset': 'node2_node_asset2',
                                    'asset_type': 2,
                                    'authentication': 1,
                                    'available': ['cust1', 'cust2', 'cust3'],
                                    'condition': '',
                                    'enabled': [],
                                    'icon': 'icon2.svg',
                                    'is_global': True,
                                    'name': 'node2_node2',
                                    'new_window': True,
                                    'next_item': False,
                                    'nodes': [{
                                                  'asset': 'node2_node2_node_asset1',
                                                  'asset_type': 2,
                                                  'authentication': 0,
                                                  'available': ['cust1', 'cust2', 'cust3'],
                                                  'condition': '%DEVELOPERS_ENABLED%',
                                                  'enabled': [],
                                                  'icon': 'icon1.svg',
                                                  'is_global': True,
                                                  'name': 'node2_node2_node1',
                                                  'new_window': False,
                                                  'next_item': True,
                                                  'nodes': [],
                                                  'order': 0,
                                                  'permissions': [],
                                                  'related_assets': [('node2_node2_node_related_asset_1',
                                                                      2,
                                                                      '00000000-0000-0000-0000-00000000002e'),
                                                                     ('node2_node2_node_related_asset_2',
                                                                      2,
                                                                      '00000000-0000-0000-0000-00000000002f'),
                                                                     ('node2_node2_node_related_asset_3',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000030')],
                                                  'subtitle': 'node2_node2_node1_subtitle',
                                                  'touched': True,
                                                  'url': 'node2_node2_node1_url',
                                                  'uuid': '00000000-0000-0000-0000-00000000002b'
                                              },
                                              {
                                                  'asset': 'node2_node2_node_asset2',
                                                  'asset_type': 2,
                                                  'authentication': 1,
                                                  'available': ['cust1', 'cust2', 'cust3'],
                                                  'condition': '',
                                                  'enabled': [],
                                                  'icon': 'icon2.svg',
                                                  'is_global': True,
                                                  'name': 'node2_node2_node2',
                                                  'new_window': True,
                                                  'next_item': False,
                                                  'nodes': [],
                                                  'order': 1,
                                                  'permissions': [],
                                                  'related_assets': [('node2_node2_node_related_asset_1',
                                                                      2,
                                                                      '00000000-0000-0000-0000-00000000002e'),
                                                                     ('node2_node2_node_related_asset_2',
                                                                      2,
                                                                      '00000000-0000-0000-0000-00000000002f'),
                                                                     ('node2_node2_node_related_asset_3',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000030')],
                                                  'subtitle': 'node2_node2_node2_subtitle',
                                                  'touched': True,
                                                  'url': 'node2_node2_node2_url',
                                                  'uuid': '00000000-0000-0000-0000-00000000002c'
                                              },
                                              {
                                                  'asset': 'node2_node2_node_asset3',
                                                  'asset_type': 2,
                                                  'authentication': 2,
                                                  'available': [],
                                                  'condition': '',
                                                  'enabled': [],
                                                  'icon': 'icon3.svg',
                                                  'is_global': True,
                                                  'name': 'node2_node2_node3',
                                                  'new_window': False,
                                                  'next_item': False,
                                                  'nodes': [],
                                                  'order': 2,
                                                  'permissions': [],
                                                  'related_assets': [],
                                                  'subtitle': 'node2_node2_node3_subtitle',
                                                  'touched': True,
                                                  'url': 'node2_node2_node3_url',
                                                  'uuid': '00000000-0000-0000-0000-00000000002d'
                                              }],
                                    'order': 1,
                                    'permissions': [],
                                    'related_assets': [('node2_node_related_asset_1',
                                                        2,
                                                        '00000000-0000-0000-0000-000000000022'),
                                                       ('node2_node_related_asset_2',
                                                        2,
                                                        '00000000-0000-0000-0000-000000000023'),
                                                       ('node2_node_related_asset_3',
                                                        2,
                                                        '00000000-0000-0000-0000-000000000024')],
                                    'subtitle': 'node2_node2_subtitle',
                                    'touched': True,
                                    'url': 'node2_node2_url',
                                    'uuid': '00000000-0000-0000-0000-000000000020'
                                },
                                {
                                    'asset': 'node2_node_asset3',
                                    'asset_type': 2,
                                    'authentication': 2,
                                    'available': [],
                                    'condition': '',
                                    'enabled': [],
                                    'icon': 'icon3.svg',
                                    'is_global': True,
                                    'name': 'node2_node3',
                                    'new_window': False,
                                    'next_item': False,
                                    'nodes': [{
                                                  'asset': 'node2_node3_node_asset1',
                                                  'asset_type': 2,
                                                  'authentication': 0,
                                                  'available': ['cust1', 'cust2', 'cust3'],
                                                  'condition': '%DEVELOPERS_ENABLED%',
                                                  'enabled': [],
                                                  'icon': 'icon1.svg',
                                                  'is_global': True,
                                                  'name': 'node2_node3_node1',
                                                  'new_window': False,
                                                  'next_item': True,
                                                  'nodes': [],
                                                  'order': 0,
                                                  'permissions': [],
                                                  'related_assets': [('node2_node3_node_related_asset_1',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000034'),
                                                                     ('node2_node3_node_related_asset_2',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000035'),
                                                                     ('node2_node3_node_related_asset_3',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000036')],
                                                  'subtitle': 'node2_node3_node1_subtitle',
                                                  'touched': True,
                                                  'url': 'node2_node3_node1_url',
                                                  'uuid': '00000000-0000-0000-0000-000000000031'
                                              },
                                              {
                                                  'asset': 'node2_node3_node_asset2',
                                                  'asset_type': 2,
                                                  'authentication': 1,
                                                  'available': ['cust1', 'cust2', 'cust3'],
                                                  'condition': '',
                                                  'enabled': [],
                                                  'icon': 'icon2.svg',
                                                  'is_global': True,
                                                  'name': 'node2_node3_node2',
                                                  'new_window': True,
                                                  'next_item': False,
                                                  'nodes': [],
                                                  'order': 1,
                                                  'permissions': [],
                                                  'related_assets': [('node2_node3_node_related_asset_1',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000034'),
                                                                     ('node2_node3_node_related_asset_2',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000035'),
                                                                     ('node2_node3_node_related_asset_3',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000036')],
                                                  'subtitle': 'node2_node3_node2_subtitle',
                                                  'touched': True,
                                                  'url': 'node2_node3_node2_url',
                                                  'uuid': '00000000-0000-0000-0000-000000000032'
                                              },
                                              {
                                                  'asset': 'node2_node3_node_asset3',
                                                  'asset_type': 2,
                                                  'authentication': 2,
                                                  'available': [],
                                                  'condition': '',
                                                  'enabled': [],
                                                  'icon': 'icon3.svg',
                                                  'is_global': True,
                                                  'name': 'node2_node3_node3',
                                                  'new_window': False,
                                                  'next_item': False,
                                                  'nodes': [],
                                                  'order': 2,
                                                  'permissions': [],
                                                  'related_assets': [],
                                                  'subtitle': 'node2_node3_node3_subtitle',
                                                  'touched': True,
                                                  'url': 'node2_node3_node3_url',
                                                  'uuid': '00000000-0000-0000-0000-000000000033'
                                              }],
                                    'order': 2,
                                    'permissions': [],
                                    'related_assets': [],
                                    'subtitle': 'node2_node3_subtitle',
                                    'touched': True,
                                    'url': 'node2_node3_url',
                                    'uuid': '00000000-0000-0000-0000-000000000021'
                                }],
                      'order': 1,
                      'permissions': [],
                      'related_assets': [('node_related_asset_1',
                                          2,
                                          '00000000-0000-0000-0000-000000000004'),
                                         ('node_related_asset_2',
                                          2,
                                          '00000000-0000-0000-0000-000000000005'),
                                         ('node_related_asset_3',
                                          2,
                                          '00000000-0000-0000-0000-000000000006')],
                      'subtitle': 'node2_subtitle',
                      'touched': True,
                      'url': 'node2_url',
                      'uuid': '00000000-0000-0000-0000-000000000002'
                  },
                  {
                      'asset': 'node_asset3',
                      'asset_type': 2,
                      'authentication': 2,
                      'available': [],
                      'condition': '',
                      'enabled': [],
                      'icon': 'icon3.svg',
                      'is_global': True,
                      'name': 'node3',
                      'new_window': False,
                      'next_item': False,
                      'nodes': [{
                                    'asset': 'node3_node_asset1',
                                    'asset_type': 2,
                                    'authentication': 0,
                                    'available': ['cust1', 'cust2', 'cust3'],
                                    'condition': '%DEVELOPERS_ENABLED%',
                                    'enabled': [],
                                    'icon': 'icon1.svg',
                                    'is_global': True,
                                    'name': 'node3_node1',
                                    'new_window': False,
                                    'next_item': True,
                                    'nodes': [{
                                                  'asset': 'node3_node1_node_asset1',
                                                  'asset_type': 2,
                                                  'authentication': 0,
                                                  'available': ['cust1', 'cust2', 'cust3'],
                                                  'condition': '%DEVELOPERS_ENABLED%',
                                                  'enabled': [],
                                                  'icon': 'icon1.svg',
                                                  'is_global': True,
                                                  'name': 'node3_node1_node1',
                                                  'new_window': False,
                                                  'next_item': True,
                                                  'nodes': [],
                                                  'order': 0,
                                                  'permissions': [],
                                                  'related_assets': [('node3_node1_node_related_asset_1',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000040'),
                                                                     ('node3_node1_node_related_asset_2',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000041'),
                                                                     ('node3_node1_node_related_asset_3',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000042')],
                                                  'subtitle': 'node3_node1_node1_subtitle',
                                                  'touched': True,
                                                  'url': 'node3_node1_node1_url',
                                                  'uuid': '00000000-0000-0000-0000-00000000003d'
                                              },
                                              {
                                                  'asset': 'node3_node1_node_asset2',
                                                  'asset_type': 2,
                                                  'authentication': 1,
                                                  'available': ['cust1', 'cust2', 'cust3'],
                                                  'condition': '',
                                                  'enabled': [],
                                                  'icon': 'icon2.svg',
                                                  'is_global': True,
                                                  'name': 'node3_node1_node2',
                                                  'new_window': True,
                                                  'next_item': False,
                                                  'nodes': [],
                                                  'order': 1,
                                                  'permissions': [],
                                                  'related_assets': [('node3_node1_node_related_asset_1',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000040'),
                                                                     ('node3_node1_node_related_asset_2',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000041'),
                                                                     ('node3_node1_node_related_asset_3',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000042')],
                                                  'subtitle': 'node3_node1_node2_subtitle',
                                                  'touched': True,
                                                  'url': 'node3_node1_node2_url',
                                                  'uuid': '00000000-0000-0000-0000-00000000003e'
                                              },
                                              {
                                                  'asset': 'node3_node1_node_asset3',
                                                  'asset_type': 2,
                                                  'authentication': 2,
                                                  'available': [],
                                                  'condition': '',
                                                  'enabled': [],
                                                  'icon': 'icon3.svg',
                                                  'is_global': True,
                                                  'name': 'node3_node1_node3',
                                                  'new_window': False,
                                                  'next_item': False,
                                                  'nodes': [],
                                                  'order': 2,
                                                  'permissions': [],
                                                  'related_assets': [],
                                                  'subtitle': 'node3_node1_node3_subtitle',
                                                  'touched': True,
                                                  'url': 'node3_node1_node3_url',
                                                  'uuid': '00000000-0000-0000-0000-00000000003f'
                                              }],
                                    'order': 0,
                                    'permissions': [],
                                    'related_assets': [('node3_node_related_asset_1',
                                                        2,
                                                        '00000000-0000-0000-0000-00000000003a'),
                                                       ('node3_node_related_asset_2',
                                                        2,
                                                        '00000000-0000-0000-0000-00000000003b'),
                                                       ('node3_node_related_asset_3',
                                                        2,
                                                        '00000000-0000-0000-0000-00000000003c')],
                                    'subtitle': 'node3_node1_subtitle',
                                    'touched': True,
                                    'url': 'node3_node1_url',
                                    'uuid': '00000000-0000-0000-0000-000000000037'
                                },
                                {
                                    'asset': 'node3_node_asset2',
                                    'asset_type': 2,
                                    'authentication': 1,
                                    'available': ['cust1', 'cust2', 'cust3'],
                                    'condition': '',
                                    'enabled': [],
                                    'icon': 'icon2.svg',
                                    'is_global': True,
                                    'name': 'node3_node2',
                                    'new_window': True,
                                    'next_item': False,
                                    'nodes': [{
                                                  'asset': 'node3_node2_node_asset1',
                                                  'asset_type': 2,
                                                  'authentication': 0,
                                                  'available': ['cust1', 'cust2', 'cust3'],
                                                  'condition': '%DEVELOPERS_ENABLED%',
                                                  'enabled': [],
                                                  'icon': 'icon1.svg',
                                                  'is_global': True,
                                                  'name': 'node3_node2_node1',
                                                  'new_window': False,
                                                  'next_item': True,
                                                  'nodes': [],
                                                  'order': 0,
                                                  'permissions': [],
                                                  'related_assets': [('node3_node2_node_related_asset_1',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000046'),
                                                                     ('node3_node2_node_related_asset_2',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000047'),
                                                                     ('node3_node2_node_related_asset_3',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000048')],
                                                  'subtitle': 'node3_node2_node1_subtitle',
                                                  'touched': True,
                                                  'url': 'node3_node2_node1_url',
                                                  'uuid': '00000000-0000-0000-0000-000000000043'
                                              },
                                              {
                                                  'asset': 'node3_node2_node_asset2',
                                                  'asset_type': 2,
                                                  'authentication': 1,
                                                  'available': ['cust1', 'cust2', 'cust3'],
                                                  'condition': '',
                                                  'enabled': [],
                                                  'icon': 'icon2.svg',
                                                  'is_global': True,
                                                  'name': 'node3_node2_node2',
                                                  'new_window': True,
                                                  'next_item': False,
                                                  'nodes': [],
                                                  'order': 1,
                                                  'permissions': [],
                                                  'related_assets': [('node3_node2_node_related_asset_1',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000046'),
                                                                     ('node3_node2_node_related_asset_2',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000047'),
                                                                     ('node3_node2_node_related_asset_3',
                                                                      2,
                                                                      '00000000-0000-0000-0000-000000000048')],
                                                  'subtitle': 'node3_node2_node2_subtitle',
                                                  'touched': True,
                                                  'url': 'node3_node2_node2_url',
                                                  'uuid': '00000000-0000-0000-0000-000000000044'
                                              },
                                              {
                                                  'asset': 'node3_node2_node_asset3',
                                                  'asset_type': 2,
                                                  'authentication': 2,
                                                  'available': [],
                                                  'condition': '',
                                                  'enabled': [],
                                                  'icon': 'icon3.svg',
                                                  'is_global': True,
                                                  'name': 'node3_node2_node3',
                                                  'new_window': False,
                                                  'next_item': False,
                                                  'nodes': [],
                                                  'order': 2,
                                                  'permissions': [],
                                                  'related_assets': [],
                                                  'subtitle': 'node3_node2_node3_subtitle',
                                                  'touched': True,
                                                  'url': 'node3_node2_node3_url',
                                                  'uuid': '00000000-0000-0000-0000-000000000045'
                                              }],
                                    'order': 1,
                                    'permissions': [],
                                    'related_assets': [('node3_node_related_asset_1',
                                                        2,
                                                        '00000000-0000-0000-0000-00000000003a'),
                                                       ('node3_node_related_asset_2',
                                                        2,
                                                        '00000000-0000-0000-0000-00000000003b'),
                                                       ('node3_node_related_asset_3',
                                                        2,
                                                        '00000000-0000-0000-0000-00000000003c')],
                                    'subtitle': 'node3_node2_subtitle',
                                    'touched': True,
                                    'url': 'node3_node2_url',
                                    'uuid': '00000000-0000-0000-0000-000000000038'
                                },
                                {
                                    'asset': 'node3_node_asset3',
                                    'asset_type': 2,
                                    'authentication': 2,
                                    'available': [],
                                    'condition': '',
                                    'enabled': [],
                                    'icon': 'icon3.svg',
                                    'is_global': True,
                                    'name': 'node3_node3',
                                    'new_window': False,
                                    'next_item': False,
                                    'nodes': [{
                                                  'asset': 'node3_node3_node_asset1',
                                                  'asset_type': 2,
                                                  'authentication': 0,
                                                  'available': ['cust1', 'cust2', 'cust3'],
                                                  'condition': '%DEVELOPERS_ENABLED%',
                                                  'enabled': [],
                                                  'icon': 'icon1.svg',
                                                  'is_global': True,
                                                  'name': 'node3_node3_node1',
                                                  'new_window': False,
                                                  'next_item': True,
                                                  'nodes': [],
                                                  'order': 0,
                                                  'permissions': [],
                                                  'related_assets': [('node3_node3_node_related_asset_1',
                                                                      2,
                                                                      '00000000-0000-0000-0000-00000000004c'),
                                                                     ('node3_node3_node_related_asset_2',
                                                                      2,
                                                                      '00000000-0000-0000-0000-00000000004d'),
                                                                     ('node3_node3_node_related_asset_3',
                                                                      2,
                                                                      '00000000-0000-0000-0000-00000000004e')],
                                                  'subtitle': 'node3_node3_node1_subtitle',
                                                  'touched': True,
                                                  'url': 'node3_node3_node1_url',
                                                  'uuid': '00000000-0000-0000-0000-000000000049'
                                              },
                                              {
                                                  'asset': 'node3_node3_node_asset2',
                                                  'asset_type': 2,
                                                  'authentication': 1,
                                                  'available': ['cust1', 'cust2', 'cust3'],
                                                  'condition': '',
                                                  'enabled': [],
                                                  'icon': 'icon2.svg',
                                                  'is_global': True,
                                                  'name': 'node3_node3_node2',
                                                  'new_window': True,
                                                  'next_item': False,
                                                  'nodes': [],
                                                  'order': 1,
                                                  'permissions': [],
                                                  'related_assets': [('node3_node3_node_related_asset_1',
                                                                      2,
                                                                      '00000000-0000-0000-0000-00000000004c'),
                                                                     ('node3_node3_node_related_asset_2',
                                                                      2,
                                                                      '00000000-0000-0000-0000-00000000004d'),
                                                                     ('node3_node3_node_related_asset_3',
                                                                      2,
                                                                      '00000000-0000-0000-0000-00000000004e')],
                                                  'subtitle': 'node3_node3_node2_subtitle',
                                                  'touched': True,
                                                  'url': 'node3_node3_node2_url',
                                                  'uuid': '00000000-0000-0000-0000-00000000004a'
                                              },
                                              {
                                                  'asset': 'node3_node3_node_asset3',
                                                  'asset_type': 2,
                                                  'authentication': 2,
                                                  'available': [],
                                                  'condition': '',
                                                  'enabled': [],
                                                  'icon': 'icon3.svg',
                                                  'is_global': True,
                                                  'name': 'node3_node3_node3',
                                                  'new_window': False,
                                                  'next_item': False,
                                                  'nodes': [],
                                                  'order': 2,
                                                  'permissions': [],
                                                  'related_assets': [],
                                                  'subtitle': 'node3_node3_node3_subtitle',
                                                  'touched': True,
                                                  'url': 'node3_node3_node3_url',
                                                  'uuid': '00000000-0000-0000-0000-00000000004b'
                                              }],
                                    'order': 2,
                                    'permissions': [],
                                    'related_assets': [],
                                    'subtitle': 'node3_node3_subtitle',
                                    'touched': True,
                                    'url': 'node3_node3_url',
                                    'uuid': '00000000-0000-0000-0000-000000000039'
                                }],
                      'order': 2,
                      'permissions': [],
                      'related_assets': [],
                      'subtitle': 'node3_subtitle',
                      'touched': True,
                      'url': 'node3_url',
                      'uuid': '00000000-0000-0000-0000-000000000003'
                  }]
    }


@pytest.fixture(scope='session')
def menu_import_dict():
    with open(os.path.join(settings.BASE_DIR, 'cms/tests/_mocks/menu_import.json'), 'r') as import_file:
        return json.load(import_file)
