image: nx/ci:1.17

include:
  - project: "dev/ci"
    file: "pipelines/infra-templates.yml"
  - local: "ci/Docker/**/.gitlab-ci.yml"

default:
  tags:
    - service

variables:
  JENKINS_JOB_LOG: "true"
  JUNKSHOP_ENABLED: "false"

workflow:
  rules:
    - if: $CI_PROJECT_NAMESPACE != "dev"
      when: never
    # Enable for merge requests.
    - if: $CI_MERGE_REQUEST_ID
    # Enable for protected branch.
    - if: $CI_COMMIT_REF_PROTECTED
    - when: never

stages:
  - pre-build
  - docker image
  - check
  - build
  - test
  - fail-fast

.retries:
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - scheduler_failure

.frontend-changes:
  extends: .retries
  needs: []
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - front_end/**/*

.get_target_branch_script:
  script:
  - set -e
  - if [[ "$CI_COMMIT_REF_PROTECTED" == "true" ]]; then
  -   TARGET_BRANCH_NAME=${CI_COMMIT_REF_NAME}
  - else
  -   TARGET_BRANCH_NAME=$(get_target_protected_branch.py
        --gitlab-server-url=${CI_SERVER_URL}
        --gitlab-token=$(cat /vault/secrets/gitlab.jenkins.token)
        --project-id=${CI_PROJECT_ID}
        --merge-request-iid=${CI_MERGE_REQUEST_IID})
  - fi

no-changes:
  extends: .retries
  stage: check
  script:
    - echo "If this is the only job that runs then no changes were made that requires the pipeline"

.backend-changes:
  extends: .retries
  needs: []
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - cloud/**/*

.frontend-test-changes:
  extends: .retries
  needs: []
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - front_end/**/*.spec.ts

.frontend-node:
  extends: .frontend-changes
  image: ${NODE_JS_IMAGE}:${NODE_JS_IMAGE_TAG}

.frontend-test:
  extends: .frontend-test-changes
  image: ${NODE_JS_IMAGE}:${NODE_JS_IMAGE_TAG}

.django-python:
  extends: .backend-changes
  image: ${DJANGO_PYTHON_IMAGE}:${DJANGO_PYTHON_IMAGE_TAG}
  services:
    - name: mysql:5.7
      alias: mysql
    - name: redis:3.2.8-alpine
      alias: redis
  variables:
    TESTING: "true"
    MYSQL_DATABASE: "cloudportal"
    MYSQL_ROOT_PASSWORD: ""
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    MYSQL_PASSWORD: ""
  before_script:
    - cd cloud
    - echo "Waiting for mysql server to be ready"
    - >
      for i in {1..60}; do
        if ! mysql --host=mysql -u root -e ";"
        then
          if [ $i == 60 ]
          then
            echo "Could not connect to mysql server after 60 attempts"
            exit 1
          else
            echo "Attempt $i to connect to mysql server failed"
          fi
        else
          echo "Attempt $i Successfully connected to mysql server"
          break
        fi

        sleep 5
      done

.django-unit-test:
  extends: .django-python
  stage: test
  coverage: /^TOTAL.+?(\d+\%)$/

django-checks:
  extends: .backend-changes
  image: ${DJANGO_PYTHON_IMAGE}:${DJANGO_PYTHON_IMAGE_TAG}
  stage: check
  variables:
    USE_SQLITE: "true"
  script:
    - cd cloud
    - if ! python manage.py makemigrations --dry-run --check ; then echo Missing above migrations && exit 1 ; fi
    - if ! python manage.py check ; then echo System check failed && exit 1 ; fi

nx-mentions-check:
  extends: .frontend-changes
  stage: check
  script: ci/nx_mentions.sh

language-check:
  extends: .frontend-node
  stage: check
  script:
    - cd front_end
    - npm install
    - npm run lang-ci-check

frontend-lint-check:
  extends: .frontend-node
  stage: check
  script:
    - cd front_end
    - npm install
    - npm run lint:ci app

fe-lint-tests-check:
  extends: .frontend-test
  stage: check
  script:
    - cd front_end
    - npm install
    - npm run lint:ci:tests app

django-unit-test-slow:
  extends: .django-unit-test
  artifacts:
    when: always
    reports:
      junit: cloud/slow-report.xml
      cobertura: cloud/slow-coverage.xml
  script:
    - pytest -m "not integration" -m slow --create-db --junitxml=slow-report.xml --cov="." --cov-report xml:slow-coverage.xml --cov-report term

django-unit-test-fast:
  extends: .django-unit-test
  artifacts:
    when: always
    reports:
      junit: cloud/fast-report.xml
      cobertura: cloud/fast-coverage.xml
  script:
    - pytest -m "not integration" -m "not slow" --create-db --junitxml=fast-report.xml --cov="." --cov-report xml:fast-coverage.xml --cov-report term

frontend-unit-test:
  extends: .frontend-node
  stage: test
  variables:
    CHROME_BIN: /usr/bin/google-chrome
  script:
    - cd front_end
    - npm install
    - npm run lang
    - npm run test:ci front-end
  artifacts:
    reports:
      junit: front_end/reports/*.xml
      cobertura: front_end/coverage/test-karma/cobertura-coverage.xml

authorization-unit-test:
  extends: .frontend-node
  stage: test
  variables:
    CHROME_BIN: /usr/bin/google-chrome
  script:
    - cd front_end
    - npm install
    - npm run lang
    - npm run test:ci authorization
  artifacts:
    reports:
      junit: authorization/reports/*.xml
      cobertura: authorization/coverage/test-karma/cobertura-coverage.xml

webadmin:
  extends: .frontend-changes
  stage: build
  script:
    - runJenkinsJob.sh gitlab.vms.review.webadmin.build
      "BUILD_DESCRIPTION=$CI_COMMIT_TITLE"
      "GITLAB_BRANCH=$CI_COMMIT_REF_NAME"
      "GITLAB_COMMIT=$CI_COMMIT_SHORT_SHA"
      "GITLAB_PIPELINE_URL=$CI_PIPELINE_URL"
      "GITLAB_JOB_ID=$CI_JOB_ID"
      "GITLAB_JOB_PROJECT=$CI_PROJECT_PATH"
      "GITLAB_JOB_URL=$CI_JOB_URL"

frontend:
  extends: .frontend-changes
  stage: build
  script:
    - !reference [.get_target_branch_script, script]
    - runJenkinsJob.sh gitlab.cloud.frontend
      "PUSH_TO_ARTIFACTORY=true"
      "BRANCH=$TARGET_BRANCH_NAME"
      "BUILD_IDENTITY=$CI_PIPELINE_ID"
      "GITLAB_BRANCH=$CI_COMMIT_REF_NAME"
      "GITLAB_COMMIT=$CI_COMMIT_SHORT_SHA"
      "GITLAB_PIPELINE_URL=$CI_PIPELINE_URL"
      "GITLAB_JOB_ID=$CI_JOB_ID"
      "GITLAB_JOB_PROJECT=$CI_PROJECT_PATH"
      "GITLAB_JOB_URL=$CI_JOB_URL"
      "REVISION=$CI_COMMIT_SHORT_SHA"

wheel-uploader:
  extends: .retries
  stage: pre-build
  script:
    - mkdir ~/.nxcloud
    - >
      echo "auth: $NXCLOUD_UTIL_SERVICE_AUTH" > ~/.nxcloud/config.yaml
    - curl -L hdw.mx/linux/nxcloud | tee ./nxcloud > /dev/null && chmod +x ./nxcloud
    - cat cloud/requirements.txt | ./nxcloud runCommand UploadWheels
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - cloud/requirements.txt


.fail-on:
  image: ${DJANGO_PYTHON_IMAGE}:${DJANGO_PYTHON_IMAGE_TAG}
  stage: fail-fast
  variables:
    CANCEL_ENDPOINT: "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/pipelines/$CI_PIPELINE_ID/cancel"
    CANCEL_HEADER: "PRIVATE-TOKEN:$CANCEL_PIPELINE_ACCESS_TOKEN"
  allow_failure: true
  script:
    - cd cloud
    - /usr/local/bin/python -m pip install --upgrade pip
    - /usr/local/bin/python -m pip install discord.py
    - cd bots
    - python y_u_no_pipeline_bot.py
    - echo "Canceling jobs still running on pipeline"
    - curl --request POST --header $CANCEL_HEADER $CANCEL_ENDPOINT

.fail-on-frontend:
  extends: .fail-on
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - front_end/**/*
      when: on_failure

.fail-on-frontend-test:
  extends: .fail-on
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - front_end/**/*.spec.ts
      when: on_failure

.fail-on-backend:
  extends: .fail-on
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - cloud/**/*
      when: on_failure

on-frontend-lint:
  extends: .fail-on-frontend
  needs: ["frontend-lint-check"]

on-test-lint:
  extends: .fail-on-frontend-test
  needs: ["fe-lint-tests-check"]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - front_end/**/*.spec.ts
      when: on_failure

on-language-check:
  extends: .fail-on-frontend
  needs: ["language-check"]

on-nx-mentions:
  extends: .fail-on-frontend
  needs: ["nx-mentions-check"]

on-frontend-build:
  extends: .fail-on-frontend
  needs: ["frontend"]

on-webadmin-build:
  extends: .fail-on-frontend
  needs: ["webadmin"]

on-authorization-test:
  extends: .fail-on-frontend
  needs: ["authorization-unit-test"]

on-frontend-test:
  extends: .fail-on-frontend
  needs: ["frontend-unit-test"]

on-django-checks:
  extends: .fail-on-backend
  needs: ["django-checks"]

on-django-tests-slow:
  extends: .fail-on-backend
  needs: ["django-unit-test-slow"]

on-django-tests-fast:
  extends: .fail-on-backend
  needs: ["django-unit-test-fast"]

on-wheel-upload:
  extends: .fail-on
  needs: ["wheel-uploader"]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - cloud/requirements.txt

.hooker:
  image: ${DJANGO_PYTHON_IMAGE}:${DJANGO_PYTHON_IMAGE_TAG}
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  variables:
    CANCEL_ENDPOINT: "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/pipelines/$CI_PIPELINE_ID/cancel"
    CANCEL_HEADER: "PRIVATE-TOKEN:$CANCEL_PIPELINE_ACCESS_TOKEN"
  allow_failure: true
  before_script:
    - cd cloud
    - /usr/local/bin/python -m pip install --upgrade pip
    - /usr/local/bin/python -m pip install discord-webhook
    - /usr/local/bin/python -m pip install gql
    - /usr/local/bin/python -m pip install aiohttp
    - cd bots

y-u-no-review:
  extends: .hooker
  script:
    - python y_u_no_review_bot.py

check-python-licenses:
  image: ${DJANGO_PYTHON_IMAGE}:${DJANGO_PYTHON_IMAGE_TAG}
  stage: check
  needs: []
  artifacts:
    paths:
      - cloud/ci-license.json
    when: on_failure
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - cloud/**/requirements.txt
        - build_scripts/**/requirements.txt
  script:
    - /usr/local/bin/python -m pip install -r cloud/requirements.txt
    - /usr/local/bin/python -m pip install pip-licenses
    - ./cloud_helper.sh update_requirements_licenses

fail-on-python-license-check:
  extends: .fail-on
  needs: [check-python-licenses]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - cloud/**/requirements.txt
        - build_scripts/**/requirements.txt
      when: on_failure

check-node-licenses:
  image: ${NODE_JS_IMAGE}:${NODE_JS_IMAGE_TAG}
  stage: check
  needs: []
  artifacts:
    paths:
      - ci-package-license.json
    when: on_failure
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - cloud/**/package.json
        - front_end/**/package.json
  script:
    - npx recursive-check-licenses -a licenses_whitelist.json -e licenses_excluded_packages.json -ci true

fail-on-license-check:
  extends: .fail-on
  needs: [check-node-licenses]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - cloud/**/package.json
        - front_end/**/package.json
      when: on_failure
