image: nx/ci:1.12

include:
- project: "dev/ci"
  file: "pipelines/infra-templates.yml"
- local: "ci/Docker/**/.gitlab-ci.yml"

default:
  tags:
  - service

variables:
  DOCKER_REGISTRY: docker.artifactory.lan.hdw.mx:80
  JENKINS_URL: http://jenkins.lan.hdw.mx
  JENKINS_JOB_LOG: "true"
  JUNKSHOP_ENABLED: "false"
  PIP_TRUSTED_HOST: 'artifactory.lan.hdw.mx'
  PIP_INDEX_URL: 'http://artifactory.lan.hdw.mx/artifactory/api/pypi/pypi-python3.8-alpine3.12/simple'
  PIP_EXTRA_INDEX_URL: 'http://artifactory.lan.hdw.mx/artifactory/api/pypi/pypi-remote/simple'

workflow:
  rules:
    - if: CI_PROJECT_NAMESPACE != "dev"
      when: never
    # Enable for merge requests.
    - if: $CI_MERGE_REQUEST_ID
    # Enable for protected branch.
    - if: $CI_COMMIT_REF_PROTECTED
    - when: never

stages:
  - docker image
  - check
  - build
  - test

.django-python:
  image: ${DJANGO_PYTHON_IMAGE}:${DJANGO_PYTHON_IMAGE_TAG}
  services:
    - name: mysql:5.7
      alias: mysql
    - name: redis:3.2.8-alpine
      alias: redis
  variables:
    TESTING: 'true'
    MYSQL_DATABASE: 'cloudportal'
    MYSQL_ROOT_PASSWORD: ''
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_USER: 'cloud'
    MYSQL_PASSWORD: ''
  before_script:
    - cd cloud
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never

django-checks:
  extends: .django-python
  stage: check
  script:
    - if ! python manage.py makemigrations --dry-run --check ; then echo Missing above migrations && exit 1 ; fi
    - if ! python manage.py check ; then echo System check failed && exit 1 ; fi

nx-mentions-check:
  stage: check
  script: ci/nx_mentions.sh
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never

frontend-lint-check:
  image: ${NODE_JS_IMAGE}:${NODE_JS_IMAGE_TAG}
  stage: check
  script:
    - cd front_end
    - npm install
    - npm run lint:ci

django-unit-test:
  extends: .django-python
  stage: test
  script:
    - pytest -m "not integration" --create-db --junitxml=report.xml --cov="." --cov-report xml:coverage.xml --cov-report term
  coverage: /^TOTAL.+?(\d+\%)$/
  artifacts:
    when: always
    reports:
      junit: cloud/report.xml
      cobertura: cloud/coverage.xml
  # Until all tests are passing reliably
  allow_failure: true

frontend-unit-test:
  image: ${NODE_JS_IMAGE}:${NODE_JS_IMAGE_TAG}
  stage: test
  variables:
    CHROME_BIN: /usr/bin/google-chrome
  script:
    - cd front_end
    - npm install
    - npm run lang
    - npm run test:ci front-end
  artifacts:
    reports:
      junit: front_end/reports/*.xml
      cobertura: front_end/coverage/test-karma/cobertura-coverage.xml

authorization-unit-test:
  image: ${NODE_JS_IMAGE}:${NODE_JS_IMAGE_TAG}
  stage: test
  variables:
    CHROME_BIN: /usr/bin/google-chrome
  script:
    - cd front_end
    - npm install
    - npm run lang
    - npm run test:ci authorization
  artifacts:
    reports:
      junit: front_end/reports/*.xml
      cobertura: front_end/coverage/test-karma/cobertura-coverage.xml
  # Until all tests are passing reliably
  allow_failure: true

build-webadmin:
  stage: build
  image: nx/ci
  script:
  - runJenkinsJob.sh gitlab.vms.review.webadmin.build
      "BUILD_DESCRIPTION=$CI_COMMIT_TITLE"
      "GITLAB_BRANCH=$CI_COMMIT_REF_NAME"
      "GITLAB_COMMIT=$CI_COMMIT_SHORT_SHA"
      "GITLAB_PIPELINE_URL=$CI_PIPELINE_URL"
      "GITLAB_JOB_ID=$CI_JOB_ID"
      "GITLAB_JOB_PROJECT=$CI_PROJECT_PATH"
      "GITLAB_JOB_URL=$CI_JOB_URL"
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event" ||
      ($CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_PROTECTED == "true")
