# Generated by Django 2.2 on 2019-06-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
    ]
