# Generated by Django 2.2 on 2019-06-07 01:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('push_notifications', '0006_webpushdevice'),
        ('notifications', '0010_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('gcmdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='push_notifications.GCMDevice')),
                ('model', models.CharField(max_length=255)),
                ('custom_device_id', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('push_notifications.gcmdevice',),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'cloud'), (1, 'system')], default=0)),
                ('system_id', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.PushDevice')),
            ],
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('payload', models.TextField(blank=True, max_length=2000, null=True, validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('subscriptions', models.ManyToManyField(to='notifications.PushSubscription')),
            ],
        ),
    ]
