# Generated by Django 2.2 on 2019-06-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_pushdevice_pushnotification_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushsubscription',
            name='subscription_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='system_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='type',
            field=models.IntegerField(choices=[(0, 'cloud'), (1, 'local')], default=0),
        ),
    ]
