# Generated by Django 2.2 on 2019-07-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_auto_20190629_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='sender_to_be_contacted',
        ),
    ]
