# Generated by Django 2.2 on 2019-06-11 20:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_auto_20190611_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushdevice',
            name='custom_device_id',
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='body',
            field=models.TextField(max_length=4000, validators=[django.core.validators.MaxLengthValidator(4000)]),
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='payload',
            field=models.TextField(blank=True, max_length=4000, null=True, validators=[django.core.validators.MaxLengthValidator(4000)]),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.PushDevice'),
        ),
    ]
