# Generated by Django 2.2 on 2019-07-17 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_pushdevice_pushnotification_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.PushDevice'),
        ),
    ]
