# Generated by Django 2.2 on 2019-09-04 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0079_auto_20190904_2309'),
        ('notifications', '0014_auto_20190717_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='product_name',
            new_name='asset_name',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='target_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.asset'),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='target_product',
            new_name='target_asset'
        )
    ]
