# Generated by Django 2.2 on 2019-12-24 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_auto_20190905_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushsubscription',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='notifications.PushDevice'),
        ),
    ]
