# Generated by Django 2.2 on 2020-01-31 22:17

from django.db import migrations


def delete_push_objects(apps, schema_editor):
    PushDevice = apps.get_model('notifications', 'PushDevice')
    PushSubscription = apps.get_model('notifications', 'PushSubscription')
    PushNotification = apps.get_model('notifications', 'PushNotification')
    PushDevice.objects.all().delete()
    PushSubscription.objects.all().delete()
    PushNotification.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_auto_20191224_0237'),
    ]

    operations = [
        migrations.RunPython(delete_push_objects, elidable=True)
    ]
