# Generated by Django 2.2 on 2020-02-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0017_remove_old_push'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushnotification',
            name='subscriptions',
        ),
        migrations.RemoveField(
            model_name='pushsubscription',
            name='account',
        ),
        migrations.RemoveField(
            model_name='pushsubscription',
            name='active',
        ),
        migrations.RemoveField(
            model_name='pushsubscription',
            name='device',
        ),
        migrations.RemoveField(
            model_name='pushsubscription',
            name='subscription_id',
        ),
        migrations.RemoveField(
            model_name='pushsubscription',
            name='username',
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='subscriptions',
            field=models.ManyToManyField(to='notifications.PushSubscription'),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='devices',
            field=models.ManyToManyField(to='notifications.PushDevice'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='system_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
