# Generated by Django 2.2 on 2020-02-11 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0018_auto_20200202_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotification',
            name='body',
            field=models.TextField(blank=True, max_length=4000, validators=[django.core.validators.MaxLengthValidator(4000)]),
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
