# Generated by Django 2.2 on 2020-02-12 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0087_auto_20191202_2139'),
        ('notifications', '0019_auto_20200211_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='customization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Customization'),
        ),
    ]
