# Generated by Django 2.2 on 2020-02-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0020_pushnotification_customization'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushdevice',
            name='os',
            field=models.IntegerField(choices=[(0, 'Web'), (1, 'Android'), (2, 'iOS')], default=0),
        ),
    ]
