# Generated by Django 2.2 on 2020-02-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0021_pushdevice_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushdevice',
            name='type',
            field=models.IntegerField(choices=[(0, 'notification'), (1, 'data')], default=0),
        ),
    ]
