# Generated by Django 2.2 on 2020-03-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0022_pushdevice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
