# Generated by Django 2.2 on 2020-06-24 21:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0023_pushnotification_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='send_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
