# Generated by Django 2.2 on 2020-07-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0024_auto_20200624_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='state',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failure', 'Failure')], default='open', max_length=20),
        ),
    ]
