# Generated by Django 2.2.19 on 2021-04-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0025_pushnotification_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushdevice',
            name='arn',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='provider',
            field=models.IntegerField(choices=[(0, 'Firebase Legacy'), (1, 'Firebase'), (2, 'APN'), (3, 'Baidu')], default=0),
        ),
    ]
