# Generated by Django 2.2.19 on 2021-04-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0026_auto_20210421_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushdevice',
            name='provider',
            field=models.IntegerField(choices=[(0, 'Firebase Legacy'), (1, 'Firebase'), (2, 'APN'), (3, 'Baidu'), (4, 'APN Sandbox')], default=0),
        ),
    ]
