# Generated by Django 2.2.19 on 2021-04-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0027_auto_20210427_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushdevice',
            name='baidu_user_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
