# Generated by Django 2.2.24 on 2021-08-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0028_pushdevice_baidu_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user_email',
            field=models.TextField(),
        ),
    ]
