# Generated by Django 2.2.24 on 2021-10-26 18:45

from django.db import migrations, models
import jsonfield.fields
import notifications.models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0029_auto_20210819_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.TextField(blank=True, validators=[notifications.models.validate_system_id])),
                ('targets', jsonfield.fields.JSONField(validators=[notifications.models.validate_emails])),
                ('subject', models.TextField()),
                ('message_html', models.TextField(blank=True)),
                ('message_text', models.TextField(blank=True)),
                ('attachments', jsonfield.fields.JSONField(blank=True, validators=[notifications.models.validate_attachments])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('result', models.TextField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failure', 'Failure')], default='open')),
            ],
        ),
    ]
