# Generated by Django 2.2.24 on 2021-11-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0030_systememail'),
    ]

    operations = [
        migrations.AddField(
            model_name='systememail',
            name='customization',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
