# Generated by Django 2.2.24 on 2022-02-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0031_systememail_customization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotification',
            name='state',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failure', 'Failure')], db_index=True, default='open', max_length=20),
        ),
    ]
