# Generated by Django 4.0.7 on 2022-08-31 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0032_auto_20220215_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudnotification',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
    ]
