# Generated by Django 4.1.10 on 2023-10-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0033_alter_cloudnotification_sent_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='systememail',
            name='cloud_wrapper',
            field=models.BooleanField(default=False),
        ),
    ]
