"""
Django settings for channel_partners project.

Generated by 'django-admin startproject' using Django 4.2.3.

"""
import os
import sys
from pathlib import Path

from corsheaders.defaults import default_headers

from channel_partners.tools.config import get_config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
LOCAL_ENV = 'runserver' in sys.argv or os.getenv('LOCAL_ENV', False)
CI = os.getenv('CI', False)
TESTING = sys.argv[1:2] == ['test'] or os.getenv('TESTING', False)
USE_SQLITE = os.getenv('USE_SQLITE', False)
INSTANCE = os.getenv('INSTANCE_NAME', 'LOCAL')
MIGRATING = 'makemigrations' in sys.argv or 'migrate' in sys.argv
DOMAIN_NAME = os.getenv('DOMAIN_NAME', '')

if LOCAL_ENV:
    ENV_NAME = 'local'
elif CI:
    ENV_NAME = 'ci'
else:
    ENV_NAME = 'prod'


INSTANCE_CONFIG = get_config(ENV_NAME)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!gefm+0ps6f!vlc^*wqby=k6%o81$=s2jjum@qre=5pqf)d&yk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_extensions',
    'corsheaders',
    'accounts',
    'utils',
    'drf_spectacular',
    'partners'
]

AUTH_USER_MODEL = 'accounts.account'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'channel_partners.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'channel_partners.wsgi.application'

# Database

DATABASES = {
    'default': {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": INSTANCE_CONFIG.postgres.database,
        "USER": INSTANCE_CONFIG.postgres.username,
        "PASSWORD": INSTANCE_CONFIG.postgres.password,
        "HOST": INSTANCE_CONFIG.postgres.host,
        "PORT": INSTANCE_CONFIG.postgres.port,
        "CHARSET": "utf8"
    }
}

# Cache

REDIS_CACHE_BACKEND = "django.core.cache.backends.redis.RedisCache"
if not LOCAL_ENV:
    redis_host = os.getenv('REDIS_HOST', 'redis')
    REDIS_CACHE_LOCATION = f'redis://{redis_host}:6379'
else:
    REDIS_CACHE_LOCATION = 'redis://localhost:6379'

CACHES = {
    'default': {
        "BACKEND": REDIS_CACHE_BACKEND,
        "LOCATION": REDIS_CACHE_LOCATION,
        "TIMEOUT": None
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# STATIC_LOCATION = os.path.join(BASE_DIR, 'static')
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    # 'EXCEPTION_HANDLER': 'nxlicensed.utils.custom_exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'channel_partners.utils.NxAutoSchema'
}


SPECTACULAR_SETTINGS = {
    # 'SERVE_PERMISSIONS': ['licensing.views.ui.api_management.APIManagementPermission'],
    'TITLE': 'Nx Channel Partners API',
    'DESCRIPTION': '',
    'VERSION': '2.0.0',
    'GENERIC_ADDITIONAL_PROPERTIES': 'dict',
    'SERVERS': [
        {
            'url': f'https://{DOMAIN_NAME}/api/v2' if DOMAIN_NAME else '/api/v2'
        }
    ],
    'POSTPROCESSING_HOOKS': [
        'partners.authentication.system_authentication_hook'
    ],
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
        'showExtensions': True,
        'deepLinking': True,
    }
}

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_URLS_REGEX = r'^/nxlicensed/api/v2.*$'
CORS_ALLOW_HEADERS = list(default_headers) + [
    'cloud-host',
    'requestinterceptorrequest'
]


KEYS_PATH = os.path.join(BASE_DIR, 'keys')
RSA_KEY1 = open(os.path.join(KEYS_PATH, 'vms.nop.pvt')).read()
RSA_KEY2 = open(os.path.join(KEYS_PATH, 'vms2.nop.pvt')).read()
RSA_KEY3 = open(os.path.join(KEYS_PATH, 'vms3.nop.pvt')).read()
