"""
Django settings for channel_partners project.

Generated by 'django-admin startproject' using Django 4.2.3.

"""
import logging
import os
import sys
from enum import StrEnum
from pathlib import Path
from typing import (
    Literal,
    Union,
)

import environ
import structlog
from corsheaders.defaults import default_headers
from django.core.exceptions import ImproperlyConfigured
from nx_jwt.jwt_auth import get_jwk_client

from channel_partners.configuration.celery_cron_config import (
    CELERY_CRON_CONFIG,
)
from channel_partners.configuration.logging_config import configure_logging
from channel_partners.configuration.throttling_config import (
    configure_throttling,
)
from channel_partners.tools.config import (
    get_container_name,
    get_default_host,
)


env = environ.Env()


class EnvironmentEnum(StrEnum):
    ci = 'ci'
    local = 'local'
    prod = 'prod'
    private = 'private-1'


BASE_DIR = Path(__file__).resolve().parent.parent
LOCAL_ENV = (
        'runserver' in sys.argv or
        os.getenv('LOCAL_ENV', False)
)
LOCAL_DOCKER = os.getenv('LOCAL_DOCKER', False)
CI = os.getenv('CI', False)
MIGRATING = (
        'makemigrations' in sys.argv or
        'migrate' in sys.argv
)
TESTING = (
        sys.argv[1:2] == ['test'] or
        os.getenv('TESTING', False)
)
BUILD = 'collectstatic' in sys.argv
IS_CELERY = (
        'celery' in ' '.join(sys.argv) or
        'celery' in get_container_name() or
        ' beat ' in ' '.join(sys.argv)
)
IS_CELERY_BEAT = ' beat ' in ' '.join(sys.argv)
IS_DJANGO_SHELL = (
        'shell' in sys.argv and
        'manage.py' in sys.argv
)


if CI:
    ENV_NAME = EnvironmentEnum.ci
elif LOCAL_ENV:
    ENV_NAME = EnvironmentEnum.local
else:
    ENV_NAME = EnvironmentEnum.prod

env_path = os.path.join(BASE_DIR, 'config/.env.local')

if (
        (LOCAL_ENV or LOCAL_DOCKER or BUILD)
        and os.path.exists(env_path)
):
    # Load development environment.
    env.read_env(env_path)

# Loading variable from environment

BASE_COOKIE_PATH = env.str("BASE_COOKIE_PATH", "/partners")
DEBUG = env.bool("DEBUG", False)
DOMAIN_NAME = env.str('DOMAIN_NAME')
ECS_CONTAINER_METADATA_URI = env.str('ECS_CONTAINER_METADATA_URI', default=None)
INSTANCE_NAME = env.str('INSTANCE_NAME')
INSTANCE_CONFIG = env.str('INSTANCE_CONFIG', '')
IS_PRIVATE_CLOUD = INSTANCE_CONFIG == EnvironmentEnum.private
LICENSE_SERVER = env.str("LICENSE_SERVER", default="https://nxlicensed.hdw.mx")
NOTIFICATION_SECRET = env.str('NOTIFICATION_SECRET').split(':')
NOTIFICATION_SECRET_PASSWORD = NOTIFICATION_SECRET[1]
NOTIFICATION_SECRET_USER = NOTIFICATION_SECRET[0]
SILK_ENABLED = env.bool('SILK_ENABLED', False)
TRAFFIC_RELAY_DOMAIN = env.str('TRAFFIC_RELAY_DOMAIN')
if IS_PRIVATE_CLOUD:
    DEFAULT_HOST_NAME = DOMAIN_NAME
else:
    DEFAULT_HOST_NAME = get_default_host(INSTANCE_NAME, DOMAIN_NAME)
APPEND_SLASH = env.bool('APPEND_SLASH', False)

## AWS S3
if BUILD or MIGRATING or IS_DJANGO_SHELL:
    AWS_STORAGE_BUCKET_NAME = env.str('CACHE_BUCKET', '') or env.str('AWS_STORAGE_BUCKET_NAME', '')
else:
    AWS_STORAGE_BUCKET_NAME = env.str('CACHE_BUCKET', '') or env.str('AWS_STORAGE_BUCKET_NAME')
AWS_S3_CUSTOM_DOMAIN = env.str('AWS_S3_CUSTOM_DOMAIN', f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com')
AWS_S3_REGION_NAME = env.str('AWS_REGION', 'us-east-1')
## Database
DB_HOST = env.str('DB_HOST')
DB_NAME = env.str('DB_NAME')
DB_PASSWORD = env.str('DB_PASSWORD')
DB_PORT = env.str('DB_PORT', default=5432)
DB_USER = env.str('DB_USER')

## Services Authentication
AUTH_SRV_PROVIDERS = env.str('AUTH_PROVIDERS', '')
AUTH_SRV_ID = env.str('AUTH_ID', '')
AUTH_SRV_SECRET = env.str('AUTH_SECRET', '')
if (
        not IS_CELERY_BEAT
        and not IS_PRIVATE_CLOUD
        and not all([AUTH_SRV_PROVIDERS, AUTH_SRV_ID, AUTH_SRV_SECRET])
):
    raise ImproperlyConfigured("Missing required auth settings.")

## Celery
QUEUE_CELERY_BROKER_URL = env.str('QUEUE_CELERY_BROKER_URL')
QUEUE_PREFIX = env.str('QUEUE_PREFIX')
RUN_CELERY_EAGER = env.bool('RUN_CELERY_EAGER', False)

## Redis
REDIS_HOST = env.str("REDIS_HOST")
REDIS_PORT = env.int("REDIS_PORT", default=6379)

## Rate Limiting Env. Variables
ANON_RATE_LIMIT = env.str("ANON_RATE_LIMIT", None)
SYSTEM_RATE_LIMIT = env.str("SYSTEM_RATE_LIMIT", None)
USER_RATE_LIMIT = env.str("USER_RATE_LIMIT", None)

# RSA key must be required in most cases, excepting:
#  - celery service
#  - celery beat service
#  - django shell, it is needed for debugging sometimes even in containers where RSA key is missed
#  - migratw and collectstatic management commands
if IS_CELERY or IS_DJANGO_SHELL or BUILD or MIGRATING:
    RSA_KEY4 = env.str('RSA_KEY_PRIVATE', multiline=True, default='')
else:
    RSA_KEY4 = env.str('RSA_KEY_PRIVATE', multiline=True)
# End environment variables section

# Versioning
AVAILABLE_VERSIONS = [
    'v2',
    'v3',
]


# SECURITY WARNING: keep the secret key used in production secret!
if IS_PRIVATE_CLOUD:
    SECRET_KEY = env.str('SECRET_KEY')
    CACHE_SALT = env.str('CACHE_SALT')
else:
    SECRET_KEY = env.str('SECRET_KEY', 'django-insecure-!gefm+0ps6f!vlc^*wqby=k6%o81$=s2jjum@qre=5pqf)d&yk')
    CACHE_SALT = env.str('CACHE_SALT', 'just-a-salt-Jah2ro2zaex7ChieChieShaiz)ah5ieh>ieR*uku1xeecheeCh$ae3aero8w')

CONFIRMATION_CODE_LEN = 6
# SECURITY WARNING: don't run with debug turned on in production!

ALLOWED_HOSTS = ['*']
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Cookies
LANGUAGE_COOKIE_PATH = BASE_COOKIE_PATH
SESSION_COOKIE_PATH = BASE_COOKIE_PATH
CSRF_COOKIE_PATH = BASE_COOKIE_PATH

# Cookie Names (Can be found here: https://docs.djangoproject.com/en/4.2/ref/settings/#settings)
LANGUAGE_COOKIE_NAME = "channel_partners_django_language"
SESSION_COOKIE_NAME = "channel_partners_sessionid"
CSRF_COOKIE_NAME = "channel_partners_csrftoken"

# Application definition

INSTALLED_APPS = [
    'django_structlog',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'waffle',
    'storages',
    'django_extensions',
    'corsheaders',
    'accounts',
    'utils',
    'drf_spectacular',
    'partners',
    'django_celery_beat',
    'django_celery_results'
]

AUTH_USER_MODEL = 'accounts.account'

# LOGGING

MIN_LOGGING_LEVEL = (
    logging.DEBUG
    if DEBUG and (LOCAL_ENV or LOCAL_DOCKER)
    else logging.INFO
)

if MIN_LOGGING_LEVEL not in [logging.DEBUG, logging.INFO]:
    raise ValueError("MIN_LOGGING_LEVEL must be either logging.DEBUG or logging.INFO")

DJANGO_STRUCTLOG_STATUS_4XX_LOG_LEVEL = logging.INFO
DJANGO_STRUCTLOG_CELERY_ENABLED = True

"""
NOTE: 
- Until we are certain everything we want is being logged, let's not switch
  `disable_existing_loggers` to `True`
- Logging levels denoted from waffle
    - levels
        - [DEBUG] = True | 1
        - [INFO] = False | 0
    - This is because, inside middleware.py, we're doing
        - is_debug_level: bool = waffle.switch_is_active(settings.LOGGING_SWITCH_NAME)
    - test
"""

LOGGING = configure_logging(ENV_NAME, MIN_LOGGING_LEVEL)

structlog.configure(
    processors=[
        structlog.contextvars.merge_contextvars,
        structlog.stdlib.filter_by_level,
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.stdlib.add_logger_name,
        structlog.stdlib.add_log_level,
        structlog.stdlib.PositionalArgumentsFormatter(),
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
        structlog.processors.UnicodeDecoder(),
        structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
    ],
    logger_factory=structlog.stdlib.LoggerFactory(),
    cache_logger_on_first_use=True,
)

MIDDLEWARE = [
    "django_structlog.middlewares.RequestMiddleware",
    'channel_partners.logging.middleware.DBQueryLoggerMiddleware',
    "channel_partners.logging.middleware.RequestTimerMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    'partners.middleware.cloud_host_middleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.http.ConditionalGetMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'waffle.middleware.WaffleMiddleware',
]

ROOT_URLCONF = 'channel_partners.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'channel_partners.wsgi.application'

# Database

DATABASES = {
    'default': {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": DB_NAME,
        "USER": DB_USER,
        "PASSWORD": DB_PASSWORD,
        "HOST": DB_HOST,
        "PORT": DB_PORT,
        "CHARSET": "utf8",
        'ATOMIC_REQUESTS': True
    }
}

# WAFFLE SETUP
WAFFLE_CACHE_NAME = 'waffle-redis'
WAFFLE_LOCAL_CACHE_NAME = 'waffle-local'
LOGGING_SWITCH_NAME = "logging_debug_active"

# Cache
REDIS_CACHE_BACKEND = "nx_django_redis.redis_cache.RedisSyncBackend"
REDIS_CACHE_LOCATION = f'redis://{REDIS_HOST}:{REDIS_PORT}'

REDIS_THROTTLING_DB = 12
REDIS_DEPENDENT_CACHE_DB = 13
REDIS_WAFFLE_CACHE_DB = 14
REDIS_CELERY_DB = 15

REDIS_WAFFLE_TIMEOUT = 500

if MIGRATING:
    # Avoid issues with redis on migrations
    REDIS_CACHE_BACKEND = "django.core.cache.backends.dummy.DummyCache"

CACHES = {
    "local": {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'local',
        'TIMEOUT': None
    },
    "waffle-local": {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'local',
        'TIMEOUT': REDIS_WAFFLE_TIMEOUT
    },
    'waffle-redis': {
        "BACKEND": REDIS_CACHE_BACKEND,
        "LOCATION": f"{REDIS_CACHE_LOCATION}/{REDIS_WAFFLE_CACHE_DB}",
        "TIMEOUT": REDIS_WAFFLE_TIMEOUT
    },
    'default': {
        "BACKEND": REDIS_CACHE_BACKEND,
        "LOCATION": REDIS_CACHE_LOCATION,
        "TIMEOUT": None
    },
    'celery': {
        # RESERVED FOR CELERY
        "BACKEND": REDIS_CACHE_BACKEND,
        "LOCATION": f'{REDIS_CACHE_LOCATION}/{REDIS_CELERY_DB}',
        "TIMEOUT": None
    },
    "throttling": {
        "BACKEND": REDIS_CACHE_BACKEND,
        "LOCATION": f"{REDIS_CACHE_LOCATION}/{REDIS_THROTTLING_DB}",
        "TIMEOUT": None
    },
    "dependent_cache": {
        "BACKEND": REDIS_CACHE_BACKEND,
        "LOCATION": f"{REDIS_CACHE_LOCATION}/{REDIS_DEPENDENT_CACHE_DB}",
        "TIMEOUT": None
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# STATIC_LOCATION = os.path.join(BASE_DIR, 'static')
STATIC_URL = 'partners/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    # 'EXCEPTION_HANDLER': 'nxlicensed.utils.custom_exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'channel_partners.utils.NxAutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'EXCEPTION_HANDLER': 'tools.helpers.custom_exception_handler',
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer'
    ],
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
    'DEFAULT_VERSION': 'v2', # We need it for testing
    **configure_throttling(USER_RATE_LIMIT, ANON_RATE_LIMIT, SYSTEM_RATE_LIMIT)
}
DRF_STANDARDIZED_ERRORS = {"EXCEPTION_HANDLER_CLASS": "tools.helpers.CustomExceptionHandler"}

SPECTACULAR_SETTINGS = {
    # 'SERVE_PERMISSIONS': ['licensing.views.ui.api_management.APIManagementPermission'],
    'TITLE': 'Channel Partners API',
    'DESCRIPTION': '',
    'VERSION': '2.0.0',
    'GENERIC_ADDITIONAL_PROPERTIES': 'dict',
    'SERVERS': [
        {
            'url': f'https://{DOMAIN_NAME}/partners/api' if DOMAIN_NAME else '/partners/api'
        }
    ],
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
        'showExtensions': True,
        'deepLinking': True,
    },
    "ENUM_NAME_OVERRIDES": {
        "ValidationErrorEnum": "drf_standardized_errors.openapi_serializers.ValidationErrorEnum.choices",
        "ClientErrorEnum": "drf_standardized_errors.openapi_serializers.ClientErrorEnum.choices",
        "ServerErrorEnum": "drf_standardized_errors.openapi_serializers.ServerErrorEnum.choices",
        "ErrorCode401Enum": "drf_standardized_errors.openapi_serializers.ErrorCode401Enum.choices",
        "ErrorCode403Enum": "drf_standardized_errors.openapi_serializers.ErrorCode403Enum.choices",
        "ErrorCode404Enum": "drf_standardized_errors.openapi_serializers.ErrorCode404Enum.choices",
        "ErrorCode405Enum": "drf_standardized_errors.openapi_serializers.ErrorCode405Enum.choices",
        "ErrorCode406Enum": "drf_standardized_errors.openapi_serializers.ErrorCode406Enum.choices",
        "ErrorCode415Enum": "drf_standardized_errors.openapi_serializers.ErrorCode415Enum.choices",
        "ErrorCode429Enum": "drf_standardized_errors.openapi_serializers.ErrorCode429Enum.choices",
        "ErrorCode500Enum": "drf_standardized_errors.openapi_serializers.ErrorCode500Enum.choices",
    },
}

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list(default_headers) + [
    'requestinterceptorrequest'
]

if SILK_ENABLED:
    INSTALLED_APPS.append('silk')
    MIDDLEWARE.append('silk.middleware.SilkyMiddleware')

# CELERY_BROKER_URL = os.getenv('QUEUE_CELERY_BROKER_URL')
if ENV_NAME == EnvironmentEnum.prod:
    CELERY_BROKER_URL = QUEUE_CELERY_BROKER_URL
else:
    CELERY_BROKER_URL = f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_CELERY_DB}'
CELERY_BROKER_CONNECTION_MAX_RETRIES = 1
if not LOCAL_ENV:
    CELERY_BROKER_TRANSPORT_OPTIONS = {
        'queue_name_prefix': QUEUE_PREFIX,
        'region': AWS_S3_REGION_NAME
    }

CELERY_RESULT_PERSISTENT = True
CELERY_RESULT_BACKEND = 'django-db'
CELERY_RESULT_EXTENDED = True
CELERY_WORKER_SEND_TASK_EVENTS = False
# Allows worker to consume as many messages as it wants
CELERY_WORKER_PREFETCH_MULTIPLIER = 0
CELERY_BROKER_HEARTBEAT = 10  # Supposed to check connection with broker

# Run celery tasks locally if set to true
CELERY_TASK_ALWAYS_EAGER = False
if TESTING or ENV_NAME == EnvironmentEnum.ci:
    CELERY_TASK_ALWAYS_EAGER = True
elif ENV_NAME == EnvironmentEnum.local and RUN_CELERY_EAGER:
    CELERY_TASK_ALWAYS_EAGER = True

DJANGO_CELERY_BEAT_TZ_AWARE = False

CELERY_BEAT_SCHEDULE = CELERY_CRON_CONFIG

JWK_LIFESPAN = 21600
JWK_CLIENT = get_jwk_client(DEFAULT_HOST_NAME, lifespan=JWK_LIFESPAN, init_keys=False)


"""
- If i don't import the following, i'm not getting any signals. 
- If i place at the top, the following tests fail
    - TestCloudSystemViewSet::test_saas_report
    - TestSystemUsers::test_system_failure
"""
# ruff: noqa: F401, TID252
from channel_partners.logging.logging_signals import (
    bind_additional_request_metadata,
)


# AWS S3 Storage
AWS_S3_OBJECT_PARAMETERS = {
    'ContentDisposition': 'attachment',
}
AWS_S3_SIGNATURE_VERSION = 's3v4'
CACHE_STATUS_HEADER_KEY: str = "X-CPS-Cache-Status"
CACHE_ETAG_HEADER_KEY: str = "ETag"
