"""
Django settings for channel_partners project.

Generated by 'django-admin startproject' using Django 4.2.3.

"""
import logging
import os
import sys
from enum import StrEnum
from pathlib import Path

import environ
import structlog
from corsheaders.defaults import default_headers

from channel_partners.configuration.celery_cron_config import (
    CELERY_CRON_CONFIG,
)
from channel_partners.configuration.logging_config import configure_logging
from channel_partners.tools.config import get_default_host


env = environ.Env()


class EnvironmentEnum(StrEnum):
    ci = 'ci'
    local = 'local'
    prod = 'prod'


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
LOCAL_ENV = 'runserver' in sys.argv or os.getenv('LOCAL_ENV', False)
LOCAL_DOCKER = os.getenv('LOCAL_DOCKER', False)
CI = os.getenv('CI', False)
MIGRATING = 'makemigrations' in sys.argv or 'migrate' in sys.argv
TESTING = sys.argv[1:2] == ['test'] or os.getenv('TESTING', False)
BUILD = 'collectstatic' in sys.argv

MIN_LOGGING_LEVEL = logging.INFO

if CI:
    ENV_NAME = EnvironmentEnum.ci
elif LOCAL_ENV:
    ENV_NAME = EnvironmentEnum.local
else:
    ENV_NAME = EnvironmentEnum.prod

local_env_path = os.path.join(BASE_DIR, 'config/.env.local')
base_env_path = os.path.join(BASE_DIR, 'config/.env.dist')

if (
    (LOCAL_ENV or LOCAL_DOCKER or BUILD)
    and os.path.exists(local_env_path)
):
    # Load development environment.
    env.read_env(local_env_path)


# Loading variable from environment

BASE_COOKIE_PATH = env.str("BASE_COOKIE_PATH", "/partners")
DB_HOST = env.str('DB_HOST')
DB_NAME = env.str('DB_NAME')
DB_PASSWORD = env.str('DB_PASSWORD')
DB_PORT = env.str('DB_PORT', default=5432)
DB_USER = env.str('DB_USER')
DEBUG = env.bool("DEBUG", False)
DOMAIN_NAME = env.str('DOMAIN_NAME')
INSTANCE_NAME = env.str('INSTANCE_NAME')
NOTIFICATION_SECRET = env.str('NOTIFICATION_SECRET').split(':')
NOTIFICATION_SECRET_PASSWORD = NOTIFICATION_SECRET[1]
NOTIFICATION_SECRET_USER = NOTIFICATION_SECRET[0]
QUEUE_CELERY_BROKER_URL = env.str('QUEUE_CELERY_BROKER_URL')
QUEUE_PREFIX = env.str('QUEUE_PREFIX')
REDIS_HOST = env.str("REDIS_HOST")
REDIS_PORT = env.int("REDIS_PORT", default=6379)
RUN_CELERY_EAGER = env.bool('RUN_CELERY_EAGER', False)
SILK_ENABLED = env.bool('SILK_ENABLED', False)
TRAFFIC_RELAY_DOMAIN = env.str('TRAFFIC_RELAY_DOMAIN')
RSA_KEY4 = env.str('RSA_KEY_PRIVATE', multiline=True)
DEFAULT_HOST_NAME = get_default_host(INSTANCE_NAME, DOMAIN_NAME)
# End environment variables section


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!gefm+0ps6f!vlc^*wqby=k6%o81$=s2jjum@qre=5pqf)d&yk'

CACHE_SALT = 'just-a-salt-Jah2ro2zaex7ChieChieShaiz)ah5ieh>ieR*uku1xeecheeCh$ae3aero8w'

CONFIRMATION_CODE_LEN = 6
# SECURITY WARNING: don't run with debug turned on in production!

ALLOWED_HOSTS = ['*']
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Cookies
LANGUAGE_COOKIE_PATH = BASE_COOKIE_PATH
SESSION_COOKIE_PATH = BASE_COOKIE_PATH
CSRF_COOKIE_PATH = BASE_COOKIE_PATH

# Cookie Names (Can be found here: https://docs.djangoproject.com/en/4.2/ref/settings/#settings)
LANGUAGE_COOKIE_NAME = "channel_partners_django_language"
SESSION_COOKIE_NAME = "channel_partners_sessionid"
CSRF_COOKIE_NAME = "channel_partners_csrftoken"

# Application definition

INSTALLED_APPS = [
    'django_structlog',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_extensions',
    'corsheaders',
    'accounts',
    'utils',
    'drf_spectacular',
    'partners',
    'django_celery_beat',
    'django_celery_results',
]

AUTH_USER_MODEL = 'accounts.account'

# LOGGING
DJANGO_STRUCTLOG_STATUS_4XX_LOG_LEVEL = MIN_LOGGING_LEVEL
DJANGO_STRUCTLOG_CELERY_ENABLED = True

"""
NOTE: 
- Until we are certain everything we want is being logged, let's not switch
  `disable_existing_loggers` to `True`
"""

LOGGING = configure_logging(ENV_NAME, MIN_LOGGING_LEVEL)

structlog.configure(
    processors=[
        structlog.contextvars.merge_contextvars,
        structlog.stdlib.filter_by_level,
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.stdlib.add_logger_name,
        structlog.stdlib.add_log_level,
        structlog.stdlib.PositionalArgumentsFormatter(),
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
        structlog.processors.UnicodeDecoder(),
        structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
    ],
    logger_factory=structlog.stdlib.LoggerFactory(),
    cache_logger_on_first_use=True,
)

MIDDLEWARE = [
    "django_structlog.middlewares.RequestMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    'partners.middleware.cloud_host_middleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.http.ConditionalGetMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'channel_partners.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'channel_partners.wsgi.application'

# Database

DATABASES = {
    'default': {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": DB_NAME,
        "USER": DB_USER,
        "PASSWORD": DB_PASSWORD,
        "HOST": DB_HOST,
        "PORT": DB_PORT,
        "CHARSET": "utf8",
        'ATOMIC_REQUESTS': True
    }
}

# Cache
REDIS_CACHE_BACKEND = "django.core.cache.backends.redis.RedisCache"
REDIS_CACHE_LOCATION = f'redis://{REDIS_HOST}:{REDIS_PORT}'
REDIS_CELERY_DB = 15
if MIGRATING:
    # Avoid issues with redis on migrations
    REDIS_CACHE_BACKEND = "django.core.cache.backends.dummy.DummyCache"

CACHES = {
    "local": {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'local'
    },
    'default': {
        "BACKEND": REDIS_CACHE_BACKEND,
        "LOCATION": REDIS_CACHE_LOCATION,
        "TIMEOUT": None
    },
    'celery': {
        # RESERVED FOR CELERY
        "BACKEND": REDIS_CACHE_BACKEND,
        "LOCATION": f'{REDIS_CACHE_LOCATION}/{REDIS_CELERY_DB}',
        "TIMEOUT": None
    },
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# STATIC_LOCATION = os.path.join(BASE_DIR, 'static')
STATIC_URL = 'partners/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    # 'EXCEPTION_HANDLER': 'nxlicensed.utils.custom_exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'channel_partners.utils.NxAutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'EXCEPTION_HANDLER': 'tools.helpers.custom_exception_handler',
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer'
    ]
}

SPECTACULAR_SETTINGS = {
    # 'SERVE_PERMISSIONS': ['licensing.views.ui.api_management.APIManagementPermission'],
    'TITLE': 'Nx Channel Partners API',
    'DESCRIPTION': '',
    'VERSION': '2.0.0',
    'GENERIC_ADDITIONAL_PROPERTIES': 'dict',
    'SERVERS': [
        {
            'url': f'https://{DOMAIN_NAME}/partners/api/v2' if DOMAIN_NAME else '/partners/api/v2'
        }
    ],
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
        'showExtensions': True,
        'deepLinking': True,
    }
}

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list(default_headers) + [
    'requestinterceptorrequest'
]

if SILK_ENABLED:
    INSTALLED_APPS.append('silk')
    MIDDLEWARE.append('silk.middleware.SilkyMiddleware')

# CELERY_BROKER_URL = os.getenv('QUEUE_CELERY_BROKER_URL')
if ENV_NAME == EnvironmentEnum.prod:
    CELERY_BROKER_URL = QUEUE_CELERY_BROKER_URL
else:
    CELERY_BROKER_URL = f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_CELERY_DB}'
CELERY_BROKER_CONNECTION_MAX_RETRIES = 1
if not LOCAL_ENV:
    CELERY_BROKER_TRANSPORT_OPTIONS = {
        'queue_name_prefix': QUEUE_PREFIX,
        'region': env.str('AWS_REGION', 'us-east-1')
    }

CELERY_RESULT_PERSISTENT = True
CELERY_RESULT_BACKEND = 'django-db'
CELERY_WORKER_SEND_TASK_EVENTS = False
# Allows worker to consume as many messages as it wants
CELERY_WORKER_PREFETCH_MULTIPLIER = 0
CELERY_BROKER_HEARTBEAT = 10  # Supposed to check connection with broker

# Run celery tasks locally if set to true
CELERY_TASK_ALWAYS_EAGER = False
if TESTING or ENV_NAME == EnvironmentEnum.ci:
    CELERY_TASK_ALWAYS_EAGER = True
elif ENV_NAME == EnvironmentEnum.local and RUN_CELERY_EAGER:
    CELERY_TASK_ALWAYS_EAGER = True


DJANGO_CELERY_BEAT_TZ_AWARE = False

CELERY_BEAT_SCHEDULE = CELERY_CRON_CONFIG
