proxy_cache_key $scheme://$host$uri$is_args$query_string;
proxy_cache static_cache;
proxy_cache_valid 200 302 5m;
proxy_cache_lock on;
proxy_cache_background_update on;
proxy_cache_bypass $cookie_nocache $arg_nocache;
proxy_ignore_headers Cache-Control;
add_header X-Proxy-Cache $upstream_cache_status;