[global]
extra-index-url = http://artifactory.lan.hdw.mx/artifactory/api/pypi/pypi-python3.8-alpine3.12/simple
                  http://artifactory.lan.hdw.mx/artifactory/api/pypi/pypi/simple
                  http://artifactory.lan.hdw.mx/artifactory/api/pypi/pypi-remote/simple

trusted-host = artifactory.lan.hdw.mx
