[pytest]
DJANGO_SETTINGS_MODULE = channel_partners.settings
python_files = test_*.py *_tests.py
addopts = --reuse-db
env =
    D:TESTING = True
    D:LOCAL_ENV = True
markers =
    integration
    slow
    no_db
asyncio_mode = auto
