version: '2'
services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql1
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=cloudportal
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=cloud
      - MYSQL_PASSWORD=
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/custom.cnf

  redis:
    image: redis:5.0.6-alpine
    container_name: redis1
    restart: always
    ports:
      - "6379:6379"
    expose:
      - "6379"
    command:
      - redis-server
      - --databases 32

  meilisearch:
    image: getmeili/meilisearch:v0.24.0
    command: ./meilisearch --master-key=qweasd1234 --no-analytics=true
    ports:
        -   target: 7700
            published: 7700
            protocol: tcp

# ===== How to run nginx locally as proxy for django ======
# build docker image for nginx.
# cd nx_vms/cloud/deploy/cloud_portal-nginx
# comment out the following sections
# # # # # # # #
#  if (${DOLLAR}http_x_forwarded_proto != "https") {
#    set ${DOLLAR}r A;
#  }
# # # # # # # #
#  if (${DOLLAR}r = AB) {
#    return 301 https://${DOLLAR}host${DOLLAR}request_uri;
#  }
# # # # # # # #
# run './make.sh pack'
# cd nx_vms/cloud_portal/etc
# run 'docker-compose up -d'
# cd nx_vms/cloud_portal/cloud
#   run 'python manage runserver 0.0.0.0:5000'
# =========================================================

#  nginx:
#    image: nginx:1.14.0-alpine
#    container_name: cloud_portal_nginx
#    ports:
#      - "80:80"
#    environment:
#      - DATA_HOSTS_STR=https://relay.cloud-test.hdw.mx https://relay-aws.cloud-test.hdw.mx https://*.relay.cloud-test.hdw.mx https://*.relay-aws.cloud-test.hdw.mx https://nxcloud-cloud-test-integrations-static.s3.amazonaws.com  https://*.google-analytics.com https://*.hotjar.com;
#      - CUSTOMIZATION=default
#      - PORTAL_HOST=host.docker.internal
#      - PORTAL_BUCKET=cloud-portal
#
#    volumes:
#      - ../cloud/static:/app/app/static
#      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
#      - ./nginx/nginx.conf.template:/etc/nginx/conf.d/nginx.conf.template
#      - ./nginx/run_nginx.sh:/run_nginx.sh
#    command: sh /run_nginx.sh