"""
Django settings for cloud project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/

The settings are organized into four sections as follows:

Base Settings:
These are settings used/referenced by other settings. These settings
can come from either the config, as an commandline argument, env variable,
or can be static values.

Default Settings:
This is where the standard Django settings should go.

Package Settings:
This is where settings used by other modules or introduced by another package.

In House Settings:
This is where settings that don't belong to any of the previous categories should go.
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import re
import json
import sys

from botocore.config import Config

from util.config import get_config
from cloud.logger import downgrade_requests


# Base Settings


conf = get_config()
LOCAL_ENVIRONMENT = 'runserver' in sys.argv or os.getenv('LOCAL_ENV', False)
CI = os.getenv('CI', False)
TESTING = sys.argv[1:2] == ['test'] or os.getenv('TESTING', False)
USE_SQLITE = os.getenv('USE_SQLITE', False)
INSTANCE = os.getenv('INSTANCE_NAME', 'LOCAL')
MIGRATING = 'makemigrations' in sys.argv or 'migrate' in sys.argv

# Celery worker should never run in debug mode. If it is running with debug then it will hang after sometime.
CELERY_WORKER = 'celery' in sys.argv[0]
PUSH_WORKER = 'push-notification' in sys.argv

BASE_DIR = os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)))  # /app/app
# this is used for email_engine to find templates
STATIC_LOCATION = os.path.join(BASE_DIR, "static")

STATIC_ROOT = os.path.join(BASE_DIR, "static/common/static")
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'npm.finders.NpmFinder'
]

CUSTOMIZATION = os.getenv('CUSTOMIZATION')
if not CUSTOMIZATION:
    CUSTOMIZATION = conf['customization']

META_CUSTOMIZATION = 'metavms'
META = CUSTOMIZATION == META_CUSTOMIZATION

if LOCAL_ENVIRONMENT:
    STATIC_ROOT = os.path.join(BASE_DIR, "static/common")
    STATICFILES_DIRS = (
        os.path.join(STATIC_LOCATION, 'common/static'),
        os.path.join(STATIC_LOCATION, CUSTOMIZATION, "static"),
        os.path.join(STATIC_LOCATION, CUSTOMIZATION, "static/lang_en_US"),
    )
    PREVIEW_URL = '/preview/'
    PREVIEW_LOCATION = os.path.join(STATIC_LOCATION, CUSTOMIZATION, "preview")

cloud_db = conf['cloud_database']


# Default Settings


INSTALLED_APPS = (
    'dal',
    'dal_select2',
    'admin_tools',
    'admin_tools.menu',
    'admin_tools.theming',
    'admin_tools.dashboard',

    'cloud.apps.CmsAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.forms',

    'drf_yasg',
    'waffle',

    'storages',

    'django_celery_results',
    'django_celery_beat',
    'rest_framework',
    'rest_hooks',
    'oauth2_provider',
    'corsheaders',
    'push_notifications',
    'api',
    'notifications',
    'cms',
    'zapier',
    'tinymce',
    'nested_admin',
    # Needs to be last to insure file deletion isn't interrupted by other exceptions
    'django_cleanup.apps.CleanupConfig'
)


MIDDLEWARE = (
    'cloud.middleware.HeaderMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'oauth2_provider.middleware.OAuth2TokenMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'waffle.middleware.WaffleMiddleware',
    'cloud.middleware.CatchExceptionMiddleware',
    'cloud.middleware.FilterErrorMiddleware',
)

ROOT_URLCONF = 'cloud.urls'

ALLOWED_HOSTS = ['*']

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '03-b9bxxpjxsga(qln0@3szw3+xnu%6ph_l*sz-xr_4^xxrj!_'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': (
            STATIC_ROOT,
            # get rid of app/app hardcode
            os.path.join(STATIC_LOCATION, CUSTOMIZATION),
            os.path.join(STATIC_LOCATION, CUSTOMIZATION, 'templates'),
            os.path.join(BASE_DIR, 'django_templates'),
        ),
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'cloud.context_processors.flags_processor'
            ],
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
                'admin_tools.template_loaders.Loader',
            ]
        },
    },
]

FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'

WSGI_APPLICATION = 'cloud.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases


if cloud_db and cloud_db['host'] != '$DB_HOST':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'HOST': cloud_db['host'],
            'PORT': cloud_db['port'],
            'USER': cloud_db['username'],
            'PASSWORD': cloud_db['password'],
            'NAME': cloud_db['database'],
            'OPTIONS': {
                'sql_mode': 'TRADITIONAL',
                'init_command': 'SET \
                    character_set_server=utf8mb4,\
                    collation_server = utf8mb4_unicode_ci'
            }
        }
    }
    if CI:
        DATABASES['default']['HOST'] = 'mysql'

    if not LOCAL_ENVIRONMENT and not TESTING:
        DATABASES['default']['OPTIONS']['charset'] = 'utf8mb4'

    if '--test-live-db' in sys.argv or '-tld' in sys.argv and INSTANCE not in ('prod', 'stage'):
        DATABASES['default']['TEST'] = {'NAME': cloud_db['database']}

        MIGRATION_MODULES = {
            'api': None,
            'cms': None,
            'notifications': None,
            'zapier': None
        }

    elif USE_SQLITE:
        DATABASES['default'] = {
            'ENGINE': 'django.db.backends.sqlite3', 'NAME': ':memory:'}

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = conf.get('debug', LOCAL_ENVIRONMENT) and not CELERY_WORKER

REDIS_CACHE = {
    "BACKEND": "django_redis.cache.RedisCache",
    "TIMEOUT": None,
    "OPTIONS": {
        "CLIENT_CLASS": "django_redis.client.DefaultClient",
    }
}

if not LOCAL_ENVIRONMENT:
    redis_host = os.getenv('REDIS_HOST', 'redis')
    REDIS_CACHE['LOCATION'] = f'redis://{redis_host}:6379'
else:
    REDIS_CACHE['LOCATION'] = 'redis://localhost:6379'

CACHES = {
    "default": {
        "BACKEND": REDIS_CACHE['BACKEND'],
        "OPTIONS": REDIS_CACHE['OPTIONS'],
        "LOCATION": REDIS_CACHE['LOCATION'] + '/0',
        "TIMEOUT": REDIS_CACHE['TIMEOUT']
    },
    "customization": {
        "BACKEND": REDIS_CACHE['BACKEND'],
        "OPTIONS": REDIS_CACHE['OPTIONS'],
        "LOCATION": REDIS_CACHE['LOCATION'] + '/1',
        "TIMEOUT": REDIS_CACHE['TIMEOUT']
    },
    "deployment": {
        "BACKEND": REDIS_CACHE['BACKEND'],
        "OPTIONS": REDIS_CACHE['OPTIONS'],
        "LOCATION": REDIS_CACHE['LOCATION'] + '/2',
        "TIMEOUT": REDIS_CACHE['TIMEOUT']
    },
    "filters": {
        "BACKEND": REDIS_CACHE['BACKEND'],
        "OPTIONS": REDIS_CACHE['OPTIONS'],
        "LOCATION": REDIS_CACHE['LOCATION'] + '/3',
        "TIMEOUT": REDIS_CACHE['TIMEOUT']
    },
    "push_authentication": {
        "BACKEND": REDIS_CACHE['BACKEND'],
        "OPTIONS": REDIS_CACHE['OPTIONS'],
        "TIMEOUT": 60 * 60 * 24,  # 1 day
        "LOCATION": REDIS_CACHE['LOCATION'] + '/4',
        "KEY_PREFIX": "push_authentication"
    },
    "push_config": {
        "BACKEND": REDIS_CACHE['BACKEND'],
        "TIMEOUT": 15 * 60,  # 15 minutes
        "OPTIONS": REDIS_CACHE['OPTIONS'],
        "LOCATION": REDIS_CACHE['LOCATION'] + '/5',
        "KEY_PREFIX": "push_config"
    },
    "global": {
        "BACKEND": REDIS_CACHE['BACKEND'],
        "OPTIONS": REDIS_CACHE['OPTIONS'],
        "LOCATION": REDIS_CACHE['LOCATION'] + '/6',
        "KEY_PREFIX": "global"
    },
    "integrations": {
        "BACKEND": REDIS_CACHE['BACKEND'],
        "OPTIONS": REDIS_CACHE['OPTIONS'],
        "LOCATION": REDIS_CACHE['LOCATION'] + '/7',
        "KEY_PREFIX": "integrations",
        "TIMEOUT": REDIS_CACHE['TIMEOUT']
    },
    "menus": {
        "BACKEND": REDIS_CACHE['BACKEND'],
        "TIMEOUT": None,
        "OPTIONS": REDIS_CACHE['OPTIONS'],
        "LOCATION": REDIS_CACHE['LOCATION'] + '/8',
        "KEY_PREFIX": "menus"
    },
    "packages": {
        "BACKEND": REDIS_CACHE['BACKEND'],
        "OPTIONS": REDIS_CACHE['OPTIONS'],
        "LOCATION": REDIS_CACHE['LOCATION'] + '/9',
        "KEY_PREFIX": "packages",
        "TIMEOUT": 60 * 60
    },
    "documentation": {
        "BACKEND": REDIS_CACHE['BACKEND'],
        "TIMEOUT": 24 * 60 * 60,  # 1 day
        "OPTIONS": REDIS_CACHE['OPTIONS'],
        "LOCATION": REDIS_CACHE['LOCATION'] + '/10',
        "KEY_PREFIX": 'documentation'
    },
    "article": {
        "BACKEND": REDIS_CACHE['BACKEND'],
        "TIMEOUT": 24 * 60 * 60,  # 1 day
        "OPTIONS": REDIS_CACHE['OPTIONS'],
        "LOCATION": REDIS_CACHE['LOCATION'] + '/11',
        "KEY_PREFIX": 'article'
    },
    "agreement": {
        "BACKEND": REDIS_CACHE['BACKEND'],
        "TIMEOUT": None,
        "OPTIONS": REDIS_CACHE['OPTIONS'],
        "LOCATION": REDIS_CACHE['LOCATION'] + '/12',
        "KEY_PREFIX": 'agreement'
    },
    "emails": {
        "BACKEND": REDIS_CACHE['BACKEND'],
        "OPTIONS": REDIS_CACHE['OPTIONS'],
        "LOCATION": REDIS_CACHE['LOCATION'] + '/14',
        "KEY_PREFIX": "emails",
        "TIMEOUT": 60 * 60  # 1 hour
    },
    "release_notes": {
        "BACKEND": REDIS_CACHE['BACKEND'],
        "TIMEOUT": 24 * 60 * 60,  # 1 day
        "OPTIONS": REDIS_CACHE['OPTIONS'],
        "LOCATION": REDIS_CACHE['LOCATION'] + '/15',
        "KEY_PREFIX": 'release_notes'
    },
}

if DEBUG:
    CACHES["testing"] = {
        "BACKEND": REDIS_CACHE['BACKEND'],
        "TIMEOUT": None,
        "OPTIONS": REDIS_CACHE['OPTIONS'],
        "LOCATION": REDIS_CACHE['LOCATION'] + '/13',
        "KEY_PREFIX": 'testing'
    }

if TESTING:
    for key, cache in CACHES.items():
        cache['BACKEND'] = 'django.core.cache.backends.locmem.LocMemCache'
        cache['OPTIONS'] = {}
        cache['LOCATION'] = key


if LOCAL_ENVIRONMENT and not TESTING:
    INSTALLED_APPS += ('silk',)
    # MIDDLEWARE += ('silk.middleware.SilkyMiddleware',)

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False

LOG_LEVEL = 'INFO' if DEBUG else 'WARNING'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'downgrade_requests': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': downgrade_requests
        }
    },
    'formatters': {
        'verbose': {
            'format': '[%(levelname)s] %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'simple': {
            'format': '[%(levelname)s] %(message)s'
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'filters': ['downgrade_requests'],
            'formatter': 'verbose'
        },
        'mail_admins': {
            'level': 'CRITICAL',
            'class': 'cloud.logger.LimitAdminEmailHandler',
            'formatter': 'simple'
        },
    },
    'loggers': {
        '': {  # default settings for all django loggers
            'level': LOG_LEVEL,
            'propagate': True,
            'handlers': ['console']
        },
        'django.security.csrf': {
            'level': 'ERROR',
            'propagate': False,
            'handlers': ['console']
        },
        'api.views.utils': {
            'level': LOG_LEVEL,
            'propagate': False,
            'handlers': ['console']
        },
        'cloud.helpers.exceptions': {
            'level': LOG_LEVEL,
            'propagate': False,
            'handlers': ['console']
        },
        'cloud.controllers.cloud_gateway': {
            'level': LOG_LEVEL,
            'propagate': False,
            'handlers': ['console']
        },
        'notifications.tasks': {
            'level': LOG_LEVEL,
            'propagate': False,
            'handlers': ['console']
        },
        'api.account_backend': {  # explicitly mention all modules with loggers
            'level': LOG_LEVEL,
            'propagate': False,
            'handlers': ['console']
        },
        'cms.controllers.cloud_api': {
            'level': LOG_LEVEL,
            'propagate': False,
            'handlers': ['console']
        },
        'api.views.account': {
            'level': 'CRITICAL',
            'propagate': False,
            'handlers': ['console']
        },
        'cms.controllers.filldata': {
            'level': LOG_LEVEL,
            'propagate': False,
            'handlers': ['console']
        }
    }
}

# Static files (CSS, JavaScript, Images) and s3 config
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
MEDIA_ROOT = BASE_DIR + '/static/media/'
MEDIA_URL = '/media/'
LOGOUT_REDIRECT_URL = "/logout"

# whitelist for unauthorized IP addresses. Supports addresses with masks
# read more: https://docs.python.org/3/library/ipaddress.html
IP_WHITELISTS = {
    'local': (
        '127.0.0.1',        # localhost
        '74.7.76.98',       # LA office
        '95.31.136.2',      # Moscow office
        '172.17.0.0/16',    # Docker
        '192.168.0.0/16',   # local network
        '10.0.0.0/16'       # Aws VPC
    )
}

AUTH_USER_MODEL = 'api.Account'
AUTHENTICATION_BACKENDS = (
    'api.account_backend.AccountBackend',
)

SESSION_COOKIE_SECURE = not LOCAL_ENVIRONMENT
CSRF_COOKIE_SECURE = not LOCAL_ENVIRONMENT
SESSION_COOKIE_AGE = 60 * 60 * 24  # 1 day
# Don't access this directly, use function in cloud/utils
_AUTHENTICATED_SESSION_COOKIE_AGE = 60 * 60 * 24 * 30 * 2  # 2 months

ADMINS = conf['admins']

EMAIL_SUBJECT_PREFIX = ''
EMAIL_HOST = conf['smtp']['host']
EMAIL_HOST_USER = conf['smtp']['user']
EMAIL_HOST_PASSWORD = conf['smtp']['password']
EMAIL_PORT = conf['smtp']['port']
EMAIL_USE_TLS = conf['smtp']['tls']

DATA_UPLOAD_MAX_NUMBER_FIELDS = None

TEST_RUNNER = 'cloud.tests.NxRunner'


# Package Settings


# Use if you want to check user level permissions only users with the can_csv_<model_label>
# will be able to download csv files.
DJANGO_EXPORTS_REQUIRE_PERM = False
# Use if you want to disable the global django admin action. This setting is set to True by default.
DJANGO_CSV_GLOBAL_EXPORTS_ENABLED = False

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
"""
A regex which restricts the URL's for which the CORS headers will be sent.
Defaults to r'^.*$', i.e. match all URL's. Useful when you only need CORS
on a part of your site, e.g. an API at /api/.

Regex allows cors for the following api calls:
1) /api/ping
2) /api/account/login
3) /api/systems/connect
4) /api/systems/disconnect
5) /api/systems/revokeToken
6) /api/systems/{cloud_system_id}/users
7) /oauth/*
These urls need to be whitelisted because mediaserver use them.
"""
# Comment out for swagger-ui local.
CORS_URLS_REGEX = r'^(?:/oauth.*|/api/(?:account/login|ping|systems/(?:(?:dis)?connect|revokeToken|(?:[\w\d-]+/users))?))'

ADMIN_TOOLS_INDEX_DASHBOARD = 'cloud.dashboard.CustomIndexDashboard'
ADMIN_TOOLS_MENU = 'cms.menu.CustomMenu'
ADMIN_DASHBOARD = ('cms.models.Asset',
                   'cms.models.AssetCustomizationReview',
                   'api.models.AccountLoginHistory',
                   'api.models.Account',
                   'api.models.ProxyGroup'
                   )

# START s3 config
AWS_STORAGE_BUCKET_NAME = conf['bucket']
AWS_DEFAULT_ACL = 'public-read'

S3_DOMAIN = conf.get(
    's3_domain', f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com')
AWS_S3_CUSTOM_DOMAIN = S3_DOMAIN
AWS_S3_OBJECT_PARAMETERS = {
    'ContentDisposition': 'attachment',
}
# mysite is a default name for the admin site
INTEGRATION_FILE_STORAGE = 'mysite.storage_backends.MediaStorage'
# END s3

if LOCAL_ENVIRONMENT:
    AWS_STORAGE_BUCKET_NAME = 'cloud-portal'

# SNS Config
SNS_CLIENT = {
    'service_name': 'sns',
    'config': Config(
        region_name=os.getenv('SNS_REGION', 'us-east-1'),
        max_pool_connections=25
    )
}
# Uncomment if trying to use SNS from local env with credentials different from ~/.aws/credentials
# Must set AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY first
# SNS_CLIENT['aws_access_key_id'] = AWS_ACCESS_KEY_ID
# SNS_CLIENT['aws_secret_access_key'] = AWS_SECRET_ACCESS_KEY

# End SNS Config

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api.account_backend.BearerAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication'
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'EXCEPTION_HANDLER': 'cloud.drf_utils.cloud_exception_handler'
}

if DEBUG:
    REST_FRAMEWORK['DEFAULT_RENDERER_CLASSES'] += (
        'rest_framework.renderers.BrowsableAPIRenderer',)

# Used for Zapier
HOOK_EVENTS = {
    'user.send_zap_request': None
}

# Celery settings section

# Configure AWS SQS
# Broker_url = 'sqs://{aws_access_key_id}:{aws_secret_access_key}@'
# CELERY_BROKER_TRANSPORT_OPTIONS
#   queue_name_prefix allows you to name the queue for sqs
#   region allows you to specify the aws region


CELERY_BROKER_URL = os.getenv('QUEUE_CELERY_BROKER_URL')
CELERY_BROKER_CONNECTION_MAX_RETRIES = 1
if not CELERY_BROKER_URL:
    CELERY_BROKER_URL = 'sqs://'

CELERY_BROKER_TRANSPORT_OPTIONS = {
    'queue_name_prefix': conf['queue_name'] + '-',
    'region': os.getenv('AWS_REGION', 'us-east-1')
}

CELERY_RESULT_PERSISTENT = True
CELERY_RESULT_BACKEND = 'django-db'
CELERY_WORKER_SEND_TASK_EVENTS = False
# Allows worker to consume as many messages as it wants
CELERY_WORKER_PREFETCH_MULTIPLIER = 0
CELERY_BROKER_HEARTBEAT = 10  # Supposed to check connection with broker
if PUSH_WORKER:
    CELERY_WORKER_CONCURRENCY = 4
    CELERY_WORKER_PREFETCH_MULTIPLIER = 30
    CELERY_RESULT_BACKEND = None

DJANGO_CELERY_BEAT_TZ_AWARE = False


# / End of Celery settings section


# Push Notifications
# Ask Roman Barsegian for config if you need push to work locally
PUSH_NOTIFICATIONS_SETTINGS = {
    'CONFIG': 'notifications.conf.PushConfig',
    'MAX_RETRIES': 3,
    'RETRY_INTERVAL': 20
}

TINYMCE_JS_URL = STATIC_URL + 'tinymce/js/tinymce/tinymce_min.js'
TINYMCE_JS_ROOT = STATIC_ROOT + 'tinymce/js/tinymce'


NPM_ROOT_PATH = BASE_DIR
if LOCAL_ENVIRONMENT:
    NPM_FINDER_USE_CACHE = False
NPM_FILE_PATTERNS = {
    'bootstrap': ['dist/*'],
    'split.js': ['dist/*'],
    'uuid': ['dist/*'],
    'csstree-validator': ['dist/*']
}

SILKY_AUTHENTICATION = True
SILKY_AUTHORISATION = True
SILKY_PYTHON_PROFILER = True

# Waffle Settings
WAFFLE_FLAG_MODEL = 'cms.Flag'
WAFFLE_CREATE_MISSING_FLAGS = True
WAFFLE_CREATE_MISSING_SAMPLES = True
WAFFLE_CREATE_MISSING_SWITCHES = True
# End Waffle Settings


# In House Settings


DEPLOYMENT_READY = 'ready'

assert ('trafficRelay' in conf), 'Ivan, please add traffic relay to config for this instance'
assert ('bucket' in conf), 'Ivan, please add s3 bucket to config for this instance'

# {systemId}.relay-bur.vmsproxy.hdw.mx
TRAFFIC_RELAY_HOST = '{systemId}.' + conf['trafficRelay']['host']
TRAFFIC_RELAY_PROTOCOL = 'https://'

CLOUD_PORTAL_URL = conf['cloud_portal']['url'].replace('http:', 'https:')

SKINS = ['blue', 'green', 'orange']
DEFAULT_SKIN = 'blue'

if LOCAL_ENVIRONMENT:
    _HOST = 'https://dev3.cloud.hdw.mx'
    CLOUD_PORTAL_URL = _HOST
    conf["cloud_db"]["url"] = f"{_HOST}/cdb"
    conf["cloud_storage"]["url"] = f"{_HOST}/storage"
    conf["cloud_storages"]["url"] = f"{_HOST}/storages"

    # CELERY_BROKER_URL = 'sqs://...'
    # This setting is removed because every developer needs personal AWS credentials
    # Ask Ivan V to provide you with config and credentials files for AWS and save them to ~/.aws/ directory
    # Or go through file history in source control to find the last time it was here
    # (changeset 49115a0427b3 or 4923e6b2575d)

CLOUD_CONNECT = {
    'url': conf['cloud_db']['url'],
    # 'url': 'http://localhost:3346',
    # 'url': 'http://10.0.3.41:3346',
    'customization': CUSTOMIZATION,
    'password_realm': 'VMS'
}

# Cloud storage settings
CLOUD_STORAGE_URL = conf['cloud_storage']['url']
CLOUD_STORAGES_URL = conf['cloud_storages']['url']

USE_ASYNC_QUEUE = not LOCAL_ENVIRONMENT and not TESTING

LINKS_LIVE_TIMEOUT = 300  # Five minutes

PASSWORD_REQUIREMENTS = {
    'minLength': 8,
    'requiredRegex': re.compile("^[\x21-\x7E]|[\x21-\x7E][\x20-\x7E]*[\x21-\x7E]$"),
    'commonList': 'static/_source/blue/static/scripts/commonPasswordsList.json',
    'common_passwords': {}
}

common_list_file = PASSWORD_REQUIREMENTS['commonList']
if os.path.isfile(common_list_file):
    with open(common_list_file) as data_file:
        PASSWORD_REQUIREMENTS['common_passwords'] = json.load(data_file)
else:
    print(f"Warning: Can't read from {common_list_file}", file=sys.stderr)

NOTIFICATIONS_CONFIG = {
    'activate_account': {
        'engine': 'email'
    },
    'cloud_invite': {
        'engine': 'email'
    },
    'cloud_notification': {
        'engine': 'email',
        'queue': 'broadcast-notifications'
    },
    'system_notification': {
        'engine': 'email',
        'queue': 'system-notifications'
    },
    'sales_inquiry': {
        'engine': 'email'
    },
    'technical_inquiry': {
        'engine': 'email'
    },
    'integration_feedback': {
        'engine': 'email'
    },
    'ipvd_feedback': {
        'engine': 'email'
    },
    'ipvd_feedback_page': {
        'engine': 'email'
    },
    'ipvd_feedback_detail': {
        'engine': 'email'
    },
    'push_notification': {
        'queue': 'push-notification'
    },
    'restore_password': {
        'engine': 'email'
    },
    'review_version': {
        'engine': 'email'
    },
    'system_invite': {
        'engine': 'email'
    },
    'system_shared': {
        'engine': 'email'
    },
    'portal_notification': {
        'queue': 'portal-notifications'
    },
}

CONFIG_ERROR = "Customization Configuration Error. Please Notify Release Engineers."
# Can not trust DEBUG because it is automatically set False for celery workers to prevent memory leak
BROADCAST_NOTIFICATIONS_SUPERUSERS_ONLY = 'debug' in conf and conf['debug']
NOTIFICATIONS_AUTO_SUBSCRIBE = False

IPVD_CONNECT = 'https://cameras.networkoptix.com/api/v1/cacameras/'
UPDATE_JSON = 'https://updates.networkoptix.com/updates.json'
DOWNLOADS_JSON = 'http://updates.hdwitness.com.s3.amazonaws.com/{{customization}}/downloads.json'
DOWNLOADS_VERSION_JSON = 'http://updates.hdwitness.com.s3.amazonaws.com/{{customization}}/{{build}}/downloads.json'

MAX_RETRIES = conf['max_retries']
CLEAR_HISTORY_RECORDS_OLDER_THAN_X_DAYS = 15
CLEAR_HISTORY_RECORDS_CREATED_OLDER_THAN_X_DAYS = 30
CMS_MAX_FILE_SIZE = 9437184
INTEGRATION_STORE_PAGE = '/integrations'

# Filldata settings
FILLDATA_TRIES = 15
FILLDATA_TIMEOUT = 60

# Only user from this domain can have superuser permissions
SUPERUSER_DOMAIN = '@networkoptix.com'

# Instant Search Configuration
if (endpoint := os.getenv('MEILI_ENDPOINT')) and (master_key := os.getenv('MEILI_MASTER_KEY')):
    MEILISEARCH_ENDPOINT = f'http://{endpoint}:7700'
    MEILISEARCH_MASTER_KEY = master_key
else:
    MEILISEARCH_ENDPOINT = 'http://localhost:7700'
    MEILISEARCH_MASTER_KEY = 'qweasd1234'

VERSION = os.getenv('VERSION', '0')
