*** Variables ***
${CAMERAS LINK}                              //nx-menu//a[@id="cameras"]
${EDITABLE TITLE}                            //h2[@id="editable-title"]
${CAMERAS VIEW BUTTON}                       //h4//button[@id="view-camera"]
${CAMERAS DETAILED INFO BUTTON}              //h4//button[@id="detailed-info"]
${ASPECT RATIO DROPDOWN}                     //button[@id="aspect-ratios"]
${ROTATION DROPDOWN}                         //button[@id="rotations"]
${ENABLE AUDIO CHECKBOCK}                    //nx-section//nx-checkbox[@name="audioEnabled"]
${EDIT CREDENTIALS BUTTON}                   //nx-section//button[@id="update-credentials"]
${RECORING CHECK BOX}                        //nx-switch/div[@id="recording"]
${RECORD ALWAYS RADIO BUTTON}                //nx-radio//input[@id="Record Always"]
${RECORD MOTION RADIO BUTTON}                //nx-radio//input[@id="Record Motion"]
${RECORD MOTION LOW QUALITY RADIO BUTTON}    //nx-radio//input[@id="Record Motion + Low Quality"]
${FPS INPUT}                                 //input[@id="fps"]
${QUALITY DROPDOWN}                          //button[@id="recording-quality"]
${DOT-MENU}                                  //button[@class="dot-menu"]
${ENABLE MOTION DETECTION BUTTON}            //button[@id="enable-motion-detection"]