include:
  - local: "front_end/ci/.front-end-common.yml"
  - local: "front_end/ci/.scheduled.yml"

open-source:monorepo-checks:
  extends: .frontend-node
  stage: check
  script:
    - |
      pushd "front_end"
        npm run ci:open
      popd

other-frontend-checks:
  extends: .frontend-node
  stage: check
  script:
    - |
      pushd "ci"
        start_task "./nx_mentions.sh" "nx_mentions" &
      popd
      pushd "front_end"
        pushd "eslint-plugin-nx"
          start_task "npm run build-check" "eslint_plugin_build_check" &
          start_task "npm run test" "eslint_plugin_test" &
        popd
      popd

publish-storybook:
  extends: .frontend-node
  stage: build
  when: always
  rules:
  - if: !reference [ .enable_for_mr ]
    changes:
      - front_end/libs/nx-components/**/*
  script:
    - |
      pushd "front_end"
        BRANCH_NAME="mr_$CI_MERGE_REQUEST_ID"
        npx nx run nx-components:build-storybook
        npx chromatic --project-token=chpt_fe9845fefe57026 -d=dist/nx-components-storybook --exit-zero-on-changes --branch-name="$BRANCH_NAME"
              COMMENTS=$(curl -s --header "PRIVATE-TOKEN: $CANCEL_PIPELINE_ACCESS_TOKEN" "https://gitlab.nxvms.dev/api/v4/projects/$CI_MERGE_REQUEST_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes")
        STORYBOOK_URL="https://$BRANCH_NAME--668572a3e0db1b2fc73844d3.chromatic.com/"

        if echo $COMMENTS | grep -q $STORYBOOK_URL; then
          exit 0;
        fi

        curl --location --request POST "https://gitlab.nxvms.dev/api/v4/projects/$CI_MERGE_REQUEST_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes" --header "PRIVATE-TOKEN: $CANCEL_PIPELINE_ACCESS_TOKEN" --header "Content-Type: application/json" --data-raw "{ \"body\": \"Storybook deployed to [$STORYBOOK_URL]($STORYBOOK_URL). If you haven't already created an account on chromatic use the [invitation link](https://www.chromatic.com/start?inviteToken=chpi_e204b780790c4ff192bf2e2349b45dfb&appId=668572a3e0db1b2fc73844d3) to sign up.\" }"
      popd

frontend-lint:
  extends: .frontend-node
  stage: check
  script:
    - |
      pushd "front_end"
        LINT_STATUS=$(npm run lint:ci; echo $?)
        echo $LINT_STATUS
        EXIT_FROM_LINT=$(echo "$LINT_STATUS" | tail -n1)

        if [ $EXIT_FROM_LINT == 0 ]; then
          echo "Lint passed"
        else
          echo "Lint failed with exit code $EXIT_FROM_LINT, attempting to fix automatically"
          npm run lint:ci -- --fix
        fi
      popd
      COMMIT_MESSAGE="FE lint auto fixed"
    - !reference [".commit-changes", "script"]

frontend-tests:
  extends: .frontend-node
  stage: test
  coverage: /^TOTAL.+?(\d+\%)$/
  artifacts:
    when: always
    reports:
      junit:
        - front_end/junit/**/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: front_end/coverage/**/cobertura-coverage.xml
  script:
    - |
      pushd "front_end"
        npm run test:ci
      popd
