include:
  - local: "ci/Docker/.version-enforced.yml"

variables:
  NODE_JS_IMAGE: '${DOCKER_REGISTRY}/nx/cloud_portal_node_js'
  NODE_IMAGE_VERSION: '44593'
  NODE_JS_IMAGE_TAG: '${NODE_IMAGE_VERSION}'
  DOCKER_DIR: 'ci/Docker/node-chrome'

docker:build-node-chrome:
  extends: .version-enforced-docker
  variables:
    IMAGE_VERSION: '${NODE_IMAGE_VERSION}'
  before_script:
  - !reference [".version-enforced-docker", "before_script"]
  - |
    touch build.env

    echo "NODE_JS_IMAGE_TAG=${NODE_JS_IMAGE_TAG}" > build.env

    TARGET_IMAGE="${NODE_JS_IMAGE}"
    TARGET_IMAGE_TAG="${NODE_JS_IMAGE_TAG}"
  artifacts:
    reports:
      # `dotenv` is used to register `NODE_JS_IMAGE_TAG` as a runtime-created variable
      # to use it at the next pipeline stages.
      dotenv: build.env
    # set expire time to match docker image retention period
    # artifact is required to allow to restart pipeline
    # when docker image modified
    expire_in: 14 days
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event" ||
      ($CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_PROTECTED == "true")
    changes:
      - ci/Docker/node-chrome/*
      - front_end/**/package*.json
      - open/**/package*.json
      - open_candidate/**/package*.json

docker:build-node-chrome-pulled:
  stage: docker pull
  needs:
    - job: docker:build-node-chrome
  image:
    name: ${NODE_JS_IMAGE}:${NODE_JS_IMAGE_TAG}
    pull_policy: always
  rules:
    - !reference ["docker:build-node-chrome", "rules"]
  script:
    - echo "Pulling ${NODE_JS_IMAGE}:${NODE_JS_IMAGE_TAG}"
    - echo "Build commit $BUILD_COMMIT"