[global]
extra-index-url = http://artifactory.us.nxteam.dev/artifactory/api/pypi/pypi-local/simple http://artifactory.us.nxteam.dev/artifactory/api/pypi/pypi-remote/simple
trusted-host = artifactory.us.nxteam.dev
