import { generateCssVariableName } from '../theme-provider';

export const commonColors = {
    '--nxc-brand': generateCssVariableName('brand'),
    '--nxc-dark1': generateCssVariableName('core', 'dark1'),
    '--nxc-dark2': generateCssVariableName('core', 'dark2'),
    '--nxc-dark3': generateCssVariableName('core', 'dark3'),
    '--nxc-dark4': generateCssVariableName('core', 'dark4'),
    '--nxc-dark5': generateCssVariableName('core', 'dark5'),
    '--nxc-dark6': generateCssVariableName('core', 'dark6'),
    '--nxc-dark7': generateCssVariableName('core', 'dark7'),
    '--nxc-dark8': generateCssVariableName('core', 'dark8'),
    '--nxc-dark9': generateCssVariableName('core', 'dark9'),
    '--nxc-dark10': generateCssVariableName('core', 'dark10'),
    '--nxc-dark11': generateCssVariableName('core', 'dark11'),
    '--nxc-dark12': generateCssVariableName('core', 'dark12'),
    '--nxc-dark13': generateCssVariableName('core', 'dark13'),
    '--nxc-dark14': generateCssVariableName('core', 'dark14'),
    '--nxc-dark15': generateCssVariableName('core', 'dark15'),
    '--nxc-dark16': generateCssVariableName('core', 'dark16'),
    '--nxc-dark17': generateCssVariableName('core', 'dark17'),
    '--nxc-dark18': generateCssVariableName('core', 'dark18'),
    '--nxc-light1': generateCssVariableName('core', 'light1'),
    '--nxc-light2': generateCssVariableName('core', 'light2'),
    '--nxc-light3': generateCssVariableName('core', 'light3'),
    '--nxc-light4': generateCssVariableName('core', 'light4'),
    '--nxc-light5': generateCssVariableName('core', 'light5'),
    '--nxc-light6': generateCssVariableName('core', 'light6'),
    '--nxc-light7': generateCssVariableName('core', 'light7'),
    '--nxc-light8': generateCssVariableName('core', 'light8'),
    '--nxc-light9': generateCssVariableName('core', 'light9'),
    '--nxc-light10': generateCssVariableName('core', 'light10'),
    '--nxc-light11': generateCssVariableName('core', 'light11'),
    '--nxc-light12': generateCssVariableName('core', 'light12'),
    '--nxc-light13': generateCssVariableName('core', 'light13'),
    '--nxc-light14': generateCssVariableName('core', 'light14'),
    '--nxc-light15': generateCssVariableName('core', 'light15'),
    '--nxc-light16': generateCssVariableName('core', 'light16'),
    '--nxc-light17': generateCssVariableName('core', 'light17'),
    '--nxc-light18': generateCssVariableName('core', 'light18'),
} as const;
