# Generated by Django 4.2.4 on 2023-08-16 20:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import partners.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelPartner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('state', models.IntegerField(choices=[(0, 'Active'), (1, 'Suspended'), (2, 'Shutdown')], default=0)),
                ('monthly_additional_service_limit', models.BigIntegerField(blank=True, default=None, null=True)),
                ('attributes', models.JSONField(default=dict)),
                ('can_create_sub_channels', models.BooleanField(default=True)),
            ],
            options={
                'permissions': [('configure_channel_partner', 'Change CP account settings if we have any'), ('manage_users', 'Add/Remove users from CP account, assign them permissions, including Administrator permissions'), ('add_remove_sub_channel_partners', 'A permission that allows to manage sub-CP accounts. This permission allow CP user to create/delete only direct children of their CP account.'), ('add_remove_organizations', 'Create and delete Organizations for CP account.'), ('alter_state_sub_channel_partners', 'Suspend & Shutdown Sub Channel Partners'), ('alter_state_organizations', 'Suspend & Shutdown Organizations'), ('administer_organization_systems', "Access/administer organization's systems. Final access is determined by organization's settings."), ('view_service_reports', 'Ability to view how many services are consumed by direct children of the CP. With a breakdown for each organization by services, by systems and system groups, for each Sub-CP by services.'), ('add_remove_service_quantities', 'Change the quantity of services for child organizations')],
            },
            bases=(partners.models.ChannelPartnerStates, models.Model),
        ),
        migrations.CreateModel(
            name='ChannelPartnerService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(0, 'Local Recording'), (1, 'Cloud Storage'), (2, 'Analytics')])),
                ('state', models.IntegerField(choices=[(0, 'Active'), (1, 'Obsolete')])),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('parameters', models.JSONField(default=dict)),
                ('created_by_channel_partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='partners.channelpartner')),
                ('parent_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.channelpartnerservice')),
            ],
        ),
        migrations.CreateModel(
            name='CloudHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CloudInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CloudSystemId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.UUIDField()),
                ('usage_issue_detected', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('state', models.IntegerField(choices=[(0, 'Active'), (1, 'Suspended'), (2, 'Shutdown')], default=0)),
                ('current_services', models.JSONField(default=dict)),
                ('last_usage_check', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_usage_report', models.DateTimeField(default=django.utils.timezone.now)),
                ('security_statuses', models.JSONField(default=dict)),
                ('cloud_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.cloudhost')),
            ],
            bases=(partners.models.ChannelPartnerStates, models.Model),
        ),
        migrations.CreateModel(
            name='CloudUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('state', models.IntegerField(choices=[(0, 'Active'), (1, 'Suspended'), (2, 'Shutdown')], default=0)),
                ('channel_partner_can_administer', models.BooleanField(default=False)),
                ('attributes', models.JSONField(default=dict)),
                ('channel_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='partners.channelpartner')),
            ],
            options={
                'permissions': [('manage_systems', 'Can add and remove systems to the Organization and create, edit, delete groups'), ('manage_users', 'Add/Remove users from the Organization, assign them permissions, including Administrator permissions'), ('configure_organization', 'Edit Organization settings'), ('view_service_reports', 'Ability to view how many services are consumed by this Organization.'), ('view_health_monitoring', 'View health monitoring information'), ('access_systems', "Access Organization’s systems with system role's permissions")],
            },
            bases=(partners.models.ChannelPartnerStates, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_ts', models.DateTimeField()),
                ('to_ts', models.DateTimeField()),
                ('cloud_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_usages', to='partners.cloudsystemid')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.channelpartnerservice')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceToSubChannelProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('channel_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_properties', to='partners.channelpartner')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_partners_properties', to='partners.channelpartnerservice')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceToOrganizationProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_properties', to='partners.organization')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_properties', to='partners.channelpartnerservice')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.JSONField(default=list)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.clouduser')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('system_role', models.CharField(blank=True, default='', max_length=100)),
                ('permissions', models.ManyToManyField(to='auth.permission')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationExternalId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_external_ids', to='partners.channelpartner')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='partners.organization')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='organizations', through='partners.OrganizationToUser', to='partners.clouduser'),
        ),
        migrations.CreateModel(
            name='LocalRecordingUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_ts', models.DateTimeField()),
                ('to_ts', models.DateTimeField()),
                ('cloud_system_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_recording_usages', to='partners.cloudsystemid')),
            ],
        ),
        migrations.AddField(
            model_name='cloudsystemid',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cloud_systems', to='partners.organization'),
        ),
        migrations.CreateModel(
            name='CloudSystemExternalId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(max_length=100)),
                ('cloud_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='partners.cloudsystemid')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_external_ids', to='partners.channelpartner')),
            ],
        ),
        migrations.AddField(
            model_name='cloudhost',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.cloudinstance'),
        ),
        migrations.CreateModel(
            name='ChannelPartnerToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.JSONField(default=list)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('channel_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.channelpartner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.clouduser')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelPartnerServiceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('effective_ts', models.DateTimeField()),
                ('in_effect', models.BooleanField(default=False)),
                ('cloud_system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_records', to='partners.cloudsystemid')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.clouduser')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partners.channelpartnerservice')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelPartnerServiceExternalId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(max_length=100)),
                ('channel_partner_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='partners.channelpartnerservice')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_external_ids', to='partners.channelpartner')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelPartnerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('permissions', models.ManyToManyField(to='auth.permission')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelPartnerExternalId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(max_length=100)),
                ('channel_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='partners.channelpartner')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_external_ids', to='partners.channelpartner')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelPartnerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField(choices=[(0, 'Service Changed'), (1, 'System Updated')])),
                ('cloud_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.cloudinstance')),
                ('cloud_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.cloudsystemid')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.channelpartnerservice')),
            ],
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.cloudinstance'),
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='parent_channel_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_partners', to='partners.channelpartner'),
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='channel_partners', through='partners.ChannelPartnerToUser', to='partners.clouduser'),
        ),
        migrations.CreateModel(
            name='BillingModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=150)),
                ('distribution_type', models.IntegerField(choices=[(0, 'Service Changed'), (1, 'System Updated')])),
                ('grace_period_months', models.IntegerField()),
                ('prepaid_period_months', models.IntegerField()),
                ('regular_period_type', models.IntegerField(choices=[(0, 'Full'), (1, 'Fractional')])),
                ('invoice_type', models.IntegerField(choices=[(0, 'First Day of Month'), (1, 'Fixed Date'), (2, 'First Purchase Date')])),
                ('fixed_invoice_date', models.DateField(blank=True, help_text='If invoice_type is "Fixed Date"', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.channelpartner')),
            ],
        ),
        migrations.AddConstraint(
            model_name='servicetosubchannelproperties',
            constraint=models.UniqueConstraint(fields=('channel_partner', 'service'), name='unique_channel_partner_service_properties'),
        ),
        migrations.AddConstraint(
            model_name='servicetoorganizationproperties',
            constraint=models.UniqueConstraint(fields=('organization', 'service'), name='unique_organization_service_properties'),
        ),
        migrations.AddConstraint(
            model_name='organizationtouser',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='unique_organization_user'),
        ),
        migrations.AddConstraint(
            model_name='organizationexternalid',
            constraint=models.UniqueConstraint(fields=('created_by', 'custom_id'), name='organization_unique_external_id'),
        ),
        migrations.AddConstraint(
            model_name='cloudsystemid',
            constraint=models.UniqueConstraint(fields=('system_id', 'cloud_host'), name='unique_cloud_system'),
        ),
        migrations.AddConstraint(
            model_name='cloudsystemexternalid',
            constraint=models.UniqueConstraint(fields=('created_by', 'custom_id'), name='cloudsystem_unique_external_id'),
        ),
        migrations.AddConstraint(
            model_name='channelpartnertouser',
            constraint=models.UniqueConstraint(fields=('channel_partner', 'user'), name='unique_channel_partner_user'),
        ),
        migrations.AddConstraint(
            model_name='channelpartnerserviceexternalid',
            constraint=models.UniqueConstraint(fields=('created_by', 'custom_id'), name='channelpartnerservice_unique_external_id'),
        ),
        migrations.AddConstraint(
            model_name='channelpartnerexternalid',
            constraint=models.UniqueConstraint(fields=('created_by', 'custom_id'), name='channelpartner_unique_external_id'),
        ),
    ]
