# Generated by Django 4.2.4 on 2023-08-17 00:39

from django.db import migrations

instances = {
    'cloud-test': [
        'cloud-test.hdw.mx'
    ],
    'test': [
        'test.cloud.hdw.mx'
    ],
    'test2': [
        'test2.cloud.hdw.mx'
    ],
    'stage': [
        'stage.nxvms.com'
    ],
    'prod': [
        'nxvms.com'
    ]
}


def forward(apps, schema_editor):
    CloudHost = apps.get_model('partners', 'CloudHost')
    CloudInstance = apps.get_model('partners', 'CloudInstance')

    for instance_name, hosts in instances.items():
        instance = CloudInstance.objects.get_or_create(name=instance_name)[0]
        for host in hosts:
            CloudHost.objects.get_or_create(instance=instance, hostname=host)


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_authtoken'),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop)
    ]
