# Generated by Django 4.2.4 on 2023-08-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_add_hosts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelpartnerservice',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
