# Generated by Django 4.2.4 on 2023-08-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_alter_channelpartnerservice_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelpartnerservice',
            name='state',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Obsolete')], default=0),
        ),
    ]
