# Generated by Django 4.2.4 on 2023-09-13 19:31

from django.db import migrations, models

FULL = 0
PRIVACY_MODE = 100
NO_ACCESS = 200


def forwards(apps, schema_editor):
    Organization = apps.get_model('partners', 'organization')
    for organization in Organization.objects.all():
        if organization.channel_partner_can_administer:
            organization.channel_partner_access_level = FULL
        else:
            organization.channel_partner_access_level = NO_ACCESS
        organization.save()


def backwards(apps, schema_editor):
    Organization = apps.get_model('partners', 'organization')
    for organization in Organization.objects.all():
        if organization.channel_partner_access_level == NO_ACCESS:
            organization.channel_partner_can_administer = False
        else:
            organization.channel_partner_can_administer = True
        organization.save()


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_create_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='channel_partner_access_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(forwards, reverse_code=backwards),
        migrations.RemoveField(
            model_name='organization',
            name='channel_partner_can_administer',
        ),
    ]
