# Generated by Django 4.2.4 on 2023-09-13 19:31
import uuid
from uuid import UUID

from django.db import migrations, models, transaction

FULL = 0
PRIVACY_MODE = 100
NO_ACCESS = 200


ORG_ROLES = [
    (1, 'Organization Administrator', '00000000-0000-0000-0000-100000000000'),
    (2, 'Administrator', '00000000-0000-0000-0000-100000000000'),
    (3, 'Power User', '00000000-0000-0000-0000-100000000001'),
    (4, 'System Health Viewer', '00000000-0000-0000-0000-100000000005'),
    (5, 'Advanced Viewer', '00000000-0000-0000-0000-100000000002'),
    (6, 'Viewer', '00000000-0000-0000-0000-100000000003'),
    (7, 'Live Viewer', '00000000-0000-0000-0000-100000000004'),
    (8, 'System Groups', ''),
]

CP_ROLES = [
    (1, 'Administrator'),
    (2, 'Manager'),
    (3, 'Accountant'),
]


def fix_roles_ids(apps, *args, **kwargs):
    OrganizationRole = apps.get_model('partners', 'organizationrole')
    ChannelPartnerRole = apps.get_model('partners', 'channelpartnerrole')
    with transaction.atomic():
        for idx, role_name, sys_role_uuid in ORG_ROLES:
            role = OrganizationRole.objects.filter(name=role_name).first()
            if not role:
                role = OrganizationRole(name=role_name, id=1000000)
            role.uuid = UUID(int=idx, version=4)
            role.system_role_uuid = sys_role_uuid
            role.save()
    with transaction.atomic():
        for idx, role_name in CP_ROLES:
            role = ChannelPartnerRole.objects.filter(name=role_name).first()
            if not role:
                role = OrganizationRole(name=role_name, id=1000000)
            role.uuid = UUID(int=idx, version=4)
            role.save()

def forwards(apps, schema_editor):
    Organization = apps.get_model('partners', 'organization')
    for organization in Organization.objects.all():
        if organization.channel_partner_can_administer:
            organization.channel_partner_access_level_id = UUID(int=1, version=4)
        else:
            organization.channel_partner_access_level_id = None
        organization.save()


def backwards(apps, schema_editor):
    Organization = apps.get_model('partners', 'organization')
    for organization in Organization.objects.all():
        if organization.channel_partner_access_level_id == None:
            organization.channel_partner_can_administer = False
        else:
            organization.channel_partner_can_administer = True
        organization.save()


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_create_roles'),
    ]
    operations = [
        migrations.AlterField(
            model_name='organizationrole',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='organizationrole',
            name='permissions',
        ),
        migrations.AddField(
            model_name='organizationrole',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.RemoveField(
            model_name='channelpartnerrole',
            name='permissions',
        ),
        migrations.AddField(
            model_name='channelpartnerrole',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='organizationrole',
            name='system_role_uuid',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.RunPython(fix_roles_ids),
        migrations.RemoveField(
            model_name='organizationrole',
            name='id',
        ),
        migrations.RenameField(
            model_name='organizationrole',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='channelpartnerrole',
            name='id',
        ),
        migrations.RenameField(
            model_name='channelpartnerrole',
            old_name='uuid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='organizationrole',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='channelpartnerrole',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='channel_partner_access_level',
            field=models.ForeignKey(default=uuid.UUID('00000000-0000-4000-8000-000000000001'), limit_choices_to={
                'id__in': [uuid.UUID('00000000-0000-4000-8000-000000000001'),
                           uuid.UUID('00000000-0000-4000-8000-000000000004')]}, null=True,
                                    on_delete=models.deletion.SET_NULL, to='partners.organizationrole'),
        ),
        migrations.RunPython(forwards, reverse_code=backwards),
        migrations.RemoveField(
            model_name='organization',
            name='channel_partner_can_administer',
        ),
        migrations.AddField(
            model_name='organizationrole',
            name='permissions',
            field=models.ManyToManyField(to='auth.permission'),
        ),
        migrations.AddField(
            model_name='channelpartnerrole',
            name='permissions',
            field=models.ManyToManyField(to='auth.permission'),
        ),
    ]

