# Generated by Django 4.2.4 on 2023-09-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_remove_organization_channel_partner_can_administer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelpartner',
            name='support_information',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
