# Generated by Django 4.2.4 on 2023-09-29 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_channelpartner_support_information'),
        ('partners', '0008_organizationrole_permissions'),
    ]

    operations = [
    ]
