# Generated by Django 4.2.4 on 2023-10-06 21:55

from django.db import migrations, models
import django.db.models.deletion


def forward(apps, schema_editor):
    CloudSystemId = apps.get_model('partners', 'CloudSystemId')
    for system in CloudSystemId.objects.filter(organization__isnull=False):
        if system.organization:
            system.service_records.all().update(organization=system.organization)



class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_merge_20230929_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelpartnerservicerecord',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_records', to='partners.organization'),
        ),
        migrations.RunPython(forward, migrations.RunPython.noop)
    ]
