# Generated by Django 4.2.4 on 2023-09-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_merge_20230929_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelpartner',
            name='allow_changing_services',
            field=models.BooleanField(default=False),
        ),
    ]
