# Generated by Django 4.2.4 on 2023-09-14 00:30
from django.db import migrations, models
import django.db.models.deletion


def default_host():
    from django.apps import apps

    return apps.get_model('partners', 'cloudhost').objects.first()


def partner_forwards(apps, schema_editor):
    ChannelPartner = apps.get_model('partners', 'ChannelPartner')
    for partner in ChannelPartner.objects.all():
        partner.cloud_host = partner.instance.cloudhost_set.first()
        partner.save()


def event_forwards(apps, schema_editor):
    ChannelPartnerEvent = apps.get_model('partners', 'ChannelPartnerEvent')
    for event in ChannelPartnerEvent.objects.all():
        event.cloud_host = event.cloud_instance.cloudhost_set.first()
        event.save()


def partner_backwards(apps, schema_editor):
    ChannelPartner = apps.get_model('partners', 'ChannelPartner')
    for partner in ChannelPartner.objects.all():
        partner.instance = partner.cloud_host.instance
        partner.save()


def event_backwards(apps, schema_editor):
    ChannelPartnerEvent = apps.get_model('partners', 'ChannelPartnerEvent')
    for event in ChannelPartnerEvent.objects.all():
        event.cloud_instance = event.cloud_host.instance
        event.save()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('partners', '0010_channelpartner_allow_changing_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelpartner',
            name='cloud_host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.cloudhost'),
        ),
        migrations.AddField(
            model_name='channelpartnerevent',
            name='cloud_host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='partners.cloudhost'),
            preserve_default=False,
        ),
        migrations.RunPython(partner_forwards, reverse_code=partner_backwards),
        migrations.RunPython(event_forwards, reverse_code=event_backwards),
        migrations.RemoveField(
            model_name='channelpartner',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='channelpartnerevent',
            name='cloud_instance',
        ),
    ]
