# Generated by Django 4.2.4 on 2023-10-12 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_channelpartnerservicerecord_organization'),
        ('partners', '0011_remove_channelpartner_instance_and_more'),
    ]

    operations = [
    ]
