# Generated by Django 4.2.4 on 2023-10-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0012_merge_20231012_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudsystemid',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
