# Generated by Django 4.2.4 on 2023-10-17 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0014_channelpartner_created_ts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelpartner',
            name='cloud_host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.cloudhost'),
        ),
        migrations.AlterField(
            model_name='cloudhost',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.cloudinstance'),
        ),
    ]
