# Generated by Django 4.2.4 on 2023-10-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0015_alter_channelpartner_cloud_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelpartner',
            name='effective_state',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Suspended'), (2, 'Shutdown')], default=0),
        ),
        migrations.AddField(
            model_name='cloudsystemid',
            name='effective_state',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Suspended'), (2, 'Shutdown')], default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='effective_state',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Suspended'), (2, 'Shutdown')], default=0),
        ),
    ]
