# Generated by Django 4.2.4 on 2023-11-09 21:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0016_channelpartner_effective_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='organizationtouser',
            name='unique_organization_user',
        ),
        migrations.AddField(
            model_name='systemgroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='partners.organization'),
        ),
        migrations.AddField(
            model_name='systemgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='partners.systemgroup'),
        ),
        migrations.AddField(
            model_name='cloudsystemid',
            name='system_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cloud_systems', to='partners.systemgroup'),
        ),
        migrations.AddField(
            model_name='organizationtouser',
            name='system_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.systemgroup'),
        ),
        migrations.AddConstraint(
            model_name='organizationtouser',
            constraint=models.UniqueConstraint(fields=('organization', 'user', 'system_group'),
                                               name='unique_organization_user'),
        )
    ]
