# Generated by Django 4.2.4 on 2023-11-10 00:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0017_systemgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemgroup',
            name='created_ts',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
