# Generated by Django 4.2.4 on 2023-11-08 22:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0018_systemgroup_created_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='channel_partner_access_level',
            field=models.ForeignKey(default=uuid.UUID('00000000-0000-4000-8000-000000000001'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.organizationrole'),
        ),
    ]
