# Generated by Django 4.2.7 on 2023-11-16 01:39

from django.db import migrations, models


def set_nulls(apps, *args, **kwargs):
    OrganizationRole = apps.get_model('partners', 'OrganizationRole')
    OrganizationRole.objects.filter(system_role_uuid='').update(system_role_uuid=None)


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0019_alter_organization_channel_partner_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationrole',
            name='system_role_uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(set_nulls),
        migrations.AlterField(
            model_name='organizationrole',
            name='system_role_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
