# Generated by Django 4.2.7 on 2023-11-17 20:38

import django.contrib.postgres.fields
from django.db import migrations, models


def fill_roles(apps, *args, **kwargs):
    ChannelPartnerToUser = apps.get_model('partners', 'ChannelPartnerToUser')
    ChannelPartnerRole = apps.get_model('partners', 'ChannelPartnerRole')
    OrganizationToUser = apps.get_model('partners', 'OrganizationToUser')
    OrganizationRole = apps.get_model('partners', 'OrganizationRole')
    cp_roles = {r.name: r.id for r in ChannelPartnerRole.objects.all()}
    org_roles = {r.name: r.id for r in OrganizationRole.objects.all()}
    cp_users = ChannelPartnerToUser.objects.all()
    org_users = OrganizationToUser.objects.all()
    for user in cp_users:
        user.roles_uuid = [cp_roles[r] for r in user.roles]
        user.save()
    for user in org_users:
        user.roles_uuid = [org_roles[r] for r in user.roles]
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0020_alter_organizationrole_system_role_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelpartnertouser',
            name='roles_uuid',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='organizationtouser',
            name='roles_uuid',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, size=None),
        ),
        migrations.RunPython(fill_roles),
        migrations.RemoveField(
            model_name='channelpartnertouser',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='organizationtouser',
            name='roles',
        ),
        migrations.RenameField(
            model_name='channelpartnertouser',
            old_name='roles_uuid',
            new_name='roles',
        ),
        migrations.RenameField(
            model_name='organizationtouser',
            old_name='roles_uuid',
            new_name='roles',
        ),
    ]
