# Generated by Django 4.2.4 on 2023-11-07 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0021_channelpartnertouser_roles_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelpartner',
            name='allow_changing_services',
        ),
        migrations.RemoveField(
            model_name='channelpartner',
            name='can_create_sub_channels',
        ),
    ]
