# Generated by Django 4.2.7 on 2023-11-16 17:40
import uuid

import django.contrib.postgres.fields
from django.db import migrations, models

from tools.helpers import get_path_from_parent


def fill_channel_partner(apps, partner):
    Organization = apps.get_model('partners', 'organization')
    CloudSystemId = apps.get_model('partners', 'CloudSystemId')
    partner_path = get_path_from_parent(parent=partner)
    Organization.objects.filter(channel_partner_id=partner.id).update(path=partner_path)
    for organization in Organization.objects.filter(channel_partner_id=partner.id):
        systems = CloudSystemId.objects.filter(organization_id=organization.id, system_group_id__isnull=True)
        organization = get_path_from_parent(parent=organization)
        systems.update(path=organization)
    ChannelPartner = apps.get_model('partners', 'channelpartner')
    ChannelPartner.objects.filter(parent_channel_partner_id=partner.id).update(path=partner_path)
    for child in ChannelPartner.objects.filter(parent_channel_partner_id=partner.id):
        fill_channel_partner(apps, child)


def fill_systems_groups(apps, parent_group=None):
    SystemGroup = apps.get_model('partners', 'SystemGroup')
    CloudSystemId = apps.get_model('partners', 'CloudSystemId')
    groups = SystemGroup.objects.filter(parent=parent_group)
    for group in groups:
        if group.parent:
            group.path = get_path_from_parent(group.parent)
        else:
            group.path = get_path_from_parent(group.organization)
        CloudSystemId.objects.filter(system_group=group).update(path=get_path_from_parent(group))
        SystemGroup.objects.bulk_update([group], fields=['path'], batch_size=100)
        fill_systems_groups(apps, group)


def fill_path(apps, *args, **kwargs):
    ChannelPartner = apps.get_model('partners', 'channelpartner')
    for root in ChannelPartner.objects.filter(parent_channel_partner__isnull=True):
        fill_channel_partner(apps, partner=root)
    fill_systems_groups(apps)


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0022_remove_channelpartner_allow_changing_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelpartner',
            name='path',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='cloudsystemid',
            name='path',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='organization',
            name='path',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='systemgroup',
            name='path',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), null=True, size=None),
            preserve_default=False,
        ),
        migrations.RunPython(fill_path),
        migrations.AddIndex(
            model_name='systemgroup',
            index=django.contrib.postgres.indexes.GinIndex(fields=['path'], name='systemgroup_path_gin',
                                                           opclasses=['array_ops']),
        ),
        migrations.AddIndex(
            model_name='channelpartner',
            index=django.contrib.postgres.indexes.GinIndex(fields=['path'], name='channelpartner_path_gin',
                                                           opclasses=['array_ops']),
        ),
        migrations.AddIndex(
            model_name='cloudsystemid',
            index=django.contrib.postgres.indexes.GinIndex(fields=['path'], name='cloudsystemid_path_gin',
                                                           opclasses=['array_ops']),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=django.contrib.postgres.indexes.GinIndex(fields=['path'], name='organization_path_gin',
                                                           opclasses=['array_ops']),
        ),
    ]