# Generated by Django 4.2.7 on 2023-11-28 02:42

import django.contrib.postgres.indexes
from django.db import migrations


def remove_role(apps, *args, **kwargs):
    role_id = '00000000-0000-4000-8000-000000000008'
    OrganizationRole = apps.get_model('partners', 'OrganizationRole')
    OrganizationRole.objects.filter(id=role_id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0023_channelpartner_path_cloudsystemid_path_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='channelpartnertouser',
            index=django.contrib.postgres.indexes.GinIndex(fields=['roles'], name='channelpartnertouser_roles_gin', opclasses=['array_ops']),
        ),
        migrations.AddIndex(
            model_name='organizationtouser',
            index=django.contrib.postgres.indexes.GinIndex(fields=['roles'], name='organizationtouser_roles_gin', opclasses=['array_ops']),
        ),
        migrations.RunPython(remove_role),
    ]
