# Generated by Django 4.2.4 on 2023-09-28 17:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

CHANNEL_PARTNER_FIEDLS_PERMS = [
    ('field_access_cp_admin', 'field_access_cp_admin'),
    ('field_access_cp_manager', 'field_access_cp_manager'),
    ('field_access_cp_accountant', 'field_access_cp_accountant'),
    ('field_access_org_admin', 'field_access_org_admin'),
    ('field_access_org_power_user', 'field_access_org_power_user'),
    ('field_access_org_other', 'field_access_org_other'),
]

def create_perms(apps, schema_editor):
    ChannelPartner = apps.get_model('partners', 'ChannelPartner')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    content_type = ContentType.objects.get(model='channelpartner')
    perms = [Permission(content_type=content_type, name=perm_name, codename=perm_code)
             for perm_code, perm_name in CHANNEL_PARTNER_FIEDLS_PERMS]
    Permission.objects.bulk_create(perms)
    for role in apps.get_model('partners', 'channelpartnerrole').objects.all():
        if role.name == 'Administrator':
            role.permissions.add(Permission.objects.get(codename='field_access_cp_admin'))
        if role.name == 'Manager':
            role.permissions.add(Permission.objects.get(codename='field_access_cp_manager'))
        if role.name == 'Accountant':
            role.permissions.add(Permission.objects.get(codename='field_access_cp_accountant'))
    for role in apps.get_model('partners', 'organizationrole').objects.all():
        if role.name == 'Organization Administrator':
            role.permissions.add(Permission.objects.get(codename='field_access_org_admin'))
            continue
        if role.name in ['Administrator', 'Power User', 'System Health Viewer']:
            role.permissions.add(Permission.objects.get(codename='field_access_org_power_user'))
            continue
        role.permissions.add(Permission.objects.get(codename='field_access_org_other'))


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('partners', '0024_channelpartnertouser_channelpartnertouser_roles_gin_and_more'),
    ]

    operations = [
        migrations.RunPython(create_perms)
    ]
