# Generated by Django 4.2.7 on 2023-12-06 23:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0025_contentpermissionlevels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelpartner',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='organization',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
