# Generated by Django 4.2.7 on 2023-12-07 19:39

from django.db import migrations, models

from partners.models import ChannelPartnerStates, CloudSystemStates


def fill_state(apps, *args, **kwargs):
    CloudSystemId = apps.get_model('partners', 'CloudSystemId')
    for sys in (qs := CloudSystemId.objects.all()):
        if sys.activated:
            sys.system_state = CloudSystemStates.ACTIVATED
        else:
            sys.system_state = CloudSystemStates.NOT_ACTIVATED
    CloudSystemId.objects.bulk_update(qs, fields=['system_state'], batch_size=400)


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0026_alter_channelpartner_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudsystemid',
            name='system_state',
            field=models.IntegerField(blank=True, choices=[(2, 'notActivated'), (4, 'activated'), (6, 'deleted')], default=2),
        ),
        migrations.RunPython(fill_state),
        migrations.RemoveField(
            model_name='cloudsystemid',
            name='activated',
        ),
    ]
