# Generated by Django 4.2.7 on 2023-12-20 21:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0027_cloudsystemid_system_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='channel_partner_access_level',
            field=models.ForeignKey(default=uuid.UUID('00000000-0000-4000-8000-000000000001'), limit_choices_to={'id__in': [uuid.UUID('00000000-0000-4000-8000-000000000001'), uuid.UUID('00000000-0000-4000-8000-000000000004')]}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.organizationrole'),
        ),
    ]
