# Generated by Django 4.2.7 on 2023-12-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0028_alter_organization_channel_partner_access_level'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cloudsystemid',
            constraint=models.UniqueConstraint(fields=('system_id',), name='unique_system_id'),
        ),
    ]
