# Generated by Django 4.2.7 on 2023-12-28 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0029_cloudsystemid_unique_system_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cloudsystemid',
            name='unique_cloud_system',
        ),
    ]
