# Generated by Django 4.2.7 on 2023-12-07 02:39

from django.db import migrations, models
import partners.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0030_remove_cloudsystemid_unique_cloud_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.IntegerField(choices=[(0, 'pending'), (10, 'confirmed'), (20, 'expired')], default=0)),
                ('action', models.IntegerField(choices=[(0, 'Channel Partner State Change'), (1, 'Channel Partner State Change')])),
                ('target_id', models.UUIDField()),
                ('changes', models.JSONField(null=True)),
                ('code', models.CharField(default=partners.models.gen_confirmation_code, max_length=40)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.EmailField(max_length=254)),
                ('confirmed_ts', models.DateTimeField(null=True)),
            ],
        ),
    ]
