# Generated by Django 4.2.7 on 2024-01-06 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0031_actionconfirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudhost',
            name='instance',
        ),
        migrations.DeleteModel(
            name='CloudInstance',
        ),
    ]
