# Generated by Django 4.2.7 on 2024-01-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0031_actionconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelpartnerservice',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channelpartnerservice',
            name='sub_type',
            field=models.IntegerField(choices=[(0, 'Regular'), (1, 'Demo'), (2, 'Trial')], default=0),
        ),
    ]
