# Generated by Django 4.2.7 on 2024-01-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0032_remove_cloudhost_instance_delete_cloudinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudhost',
            name='hostname',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
