# Generated by Django 4.2.7 on 2024-01-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0033_alter_cloudhost_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelpartnertouser',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
