# Generated by Django 4.2.7 on 2024-01-31 18:20

from django.db import migrations

DELETED = 6
SHUTDOWN = 2

def check_deleted_sytems(apps, schema_editor):
    CloudSystemId = apps.get_model('partners', 'CloudSystemId')
    deleted_systems = CloudSystemId.objects.filter(system_state=6)
    for system in deleted_systems:
        # cache won't be cleared, so counters need to be
        # invalidated by changes or timeout
        system.disconnect_system()

class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0034_channelpartnertouser_attributes"),
    ]

    operations = [
        migrations.RunPython(check_deleted_sytems)
    ]
