# Generated by Django 4.2.7 on 2024-02-02 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0032_channelpartnerservice_duration_and_more'),
        ('partners', '0034_channelpartnertouser_attributes'),
    ]

    operations = [
    ]
