# Generated by Django 4.2.7 on 2024-01-24 01:10

from django.db import migrations, models
import django.db.models.deletion

def fill_service_type(apps, schema_editor):
    ServiceUsage = apps.get_model('partners', 'ServiceUsage')
    all_usages = ServiceUsage.objects.all().select_related('service')
    for usage in all_usages:
        usage.service_type = usage.service.type
    ServiceUsage.objects.bulk_update(all_usages, fields=['service_type'], batch_size=400)

class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0035_auto_20240131_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceusage',
            name='service_type',
            field=models.IntegerField(choices=[(0, 'Local Recording'), (1, 'Cloud Storage'), (2, 'Analytics')], default=0),
        ),
        migrations.AlterField(
            model_name='serviceusage',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.channelpartnerservice'),
        ),
        migrations.RunPython(fill_service_type),
        migrations.AlterField(
            model_name="serviceusage",
            name="service_type",
            field=models.IntegerField(
                choices=[(0, "Local Recording"), (1, "Cloud Storage"), (2, "Analytics")]
            ),
        ),
    ]

