# Generated by Django 4.2.7 on 2024-02-02 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0035_merge_20240202_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelpartnerservice',
            name='conversion_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='converting_services', to='partners.channelpartnerservice'),
        ),
    ]
