# Generated by Django 4.2.7 on 2024-01-26 02:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0036_serviceusage_service_type_alter_serviceusage_service"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LocalRecordingUsage",
        ),
    ]
