# Generated by Django 4.2.7 on 2024-02-02 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0036_channelpartnerservice_conversion_service'),
        ('partners', '0037_delete_localrecordingusage'),
    ]

    operations = [
    ]
