# Generated by Django 4.2.7 on 2024-02-06 01:12
import uuid
from django.db import migrations

REPORTS_VIEWER = uuid.UUID('00000000-0000-4000-8000-000000000003')


def change_role_name(apps, schema_editor):
    ChannelPartnerRole = apps.get_model('partners', 'ChannelPartnerRole')
    ChannelPartnerRole.objects.filter(id=REPORTS_VIEWER).update(name='Reports Viewer')

class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0038_merge_20240202_0607"),
    ]

    operations = [
        migrations.RunPython(change_role_name)
    ]
