# Generated by Django 4.2.7 on 2024-02-09 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0039_auto_20240206_0112"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelpartnerservicerecord",
            name="negation_record",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="partners.channelpartnerservicerecord",
            ),
        ),
        migrations.AddField(
            model_name="channelpartnerservicerecord",
            name="record_type",
            field=models.IntegerField(
                choices=[
                    (1, "regular"),
                    (2, "negation"),
                    (3, "conversion"),
                    (4, "licence_migration"),
                ],
                default=1,
            ),
        ),
    ]
