# Generated by Django 4.2.7 on 2024-02-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0040_channelpartnerservicerecord_negation_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clouduser',
            name='full_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
