# Generated by Django 4.2.7 on 2024-02-06 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0041_clouduser_full_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="MigrationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_key", models.CharField(max_length=128)),
                (
                    "service_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="partners.channelpartnerservicerecord",
                    ),
                ),
            ],
        ),
    ]
