# Generated by Django 4.2.7 on 2024-02-16 01:28

from django.db import migrations, models
import django.db.models.deletion


def remove_unallocated(apps, schema_editor):
    ServiceUsage = apps.get_model('partners', 'ServiceUsage')
    ServiceUsage.objects.filter(service_id__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0042_migrationrecord"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceusage",
            name="service_type",
        ),
        migrations.RunPython(remove_unallocated),
        migrations.AlterField(
            model_name="serviceusage",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="partners.channelpartnerservice",
            ),
        ),
    ]
