# Generated by Django 4.2.7 on 2024-02-28 01:57

from django.db import migrations

from tools.helpers import get_path_from_parent


def fix_paths(apps, schema_editor):
    SystemGroup = apps.get_model('partners', 'SystemGroup')
    CloudSystemId = apps.get_model('partners', 'CloudSystemId')
    Organization = apps.get_model('partners', 'Organization')

    def fix_group_path(group):
        correct_path = get_path_from_parent(group.parent or group.organization)
        if group.path != correct_path:
            group.path = correct_path
            group.save()
        sub_groups = (SystemGroup.objects
                      .filter(parent=group)
                      .select_related('organization', 'parent'))
        for sub_group in sub_groups:
            fix_group_path(sub_group)

    for organization in Organization.objects.all():
        for group in organization.groups.filter(parent__isnull=True):
            fix_group_path(group)

    all_systems = (CloudSystemId.objects
                   .exclude(organization_id__isnull=True, system_group_id__isnull=True)
                   .select_related('organization', 'system_group')
                   .iterator(chunk_size=500))
    updated_systems = []
    for system in all_systems:
        correct_path = get_path_from_parent(system.system_group or system.organization)
        if system.path != correct_path:
            system.path = correct_path
            updated_systems.append(system)
    CloudSystemId.objects.bulk_update(updated_systems, fields=['path'], batch_size=100)


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0043_remove_serviceusage_service_type"),
    ]

    operations = [
        migrations.RunPython(fix_paths)
    ]
