# Generated by Django 4.2.7 on 2024-03-23 02:21

from django.db import migrations, models
import django.db.models.deletion
import rest_framework.utils.encoders


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0044_auto_20240228_0157"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.SmallIntegerField(
                        choices=[
                            (1, "system_regular_report"),
                            (20, "organization_system_reports"),
                            (21, "organization_regular_service_reports"),
                            (22, "organization_regular_detail_table"),
                            (23, "organization_usage_report"),
                            (40, "channel_partner_organization_usages"),
                            (41, "channel_partner_channel_partner_usages"),
                            (42, "channel_partner_regular_detail_table"),
                            (43, "channel_partner_regular_service_report"),
                            (44, "channel_partner_usage_report"),
                        ]
                    ),
                ),
                ("entity_id", models.UUIDField()),
                ("start_date", models.DateField(db_index=True)),
                ("provisional", models.BooleanField(default=False)),
                ("created_ts", models.DateTimeField(auto_now_add=True)),
                ("updated_ts", models.DateTimeField(auto_now=True)),
                (
                    "report_data",
                    models.JSONField(encoder=rest_framework.utils.encoders.JSONEncoder),
                ),
                (
                    "service",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="partners.channelpartnerservice",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("entity_id", "report_type", "service_id", "start_date")
                },
            },
        ),
    ]
