# Generated by Django 4.2.7 on 2024-03-29 21:57

from django.db import migrations, models
import django.db.models.deletion


def fill_organization(apps, schema_editor):
    ReportSnapshot = apps.get_model("partners", "ReportSnapshot")
    CloudSystemId = apps.get_model("partners", "CloudSystemId")
    system_reports = ReportSnapshot.objects.filter(report_type=1)
    for system_report in system_reports:
        system = CloudSystemId.objects.get(system_id=system_report.entity_id)
        system_report.organization = system.organization

    ReportSnapshot.objects.bulk_update(system_reports, ["organization"], batch_size=100)

class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0045_reportsnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportsnapshot",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="partners.organization",
            ),
        ),
        migrations.RunPython(fill_organization)
    ]
