# Generated by Django 4.2.7 on 2024-04-09 20:42
import datetime

from dateutil.relativedelta import relativedelta
from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.utils import timezone


def fill_history(apps, schema_editor):
    CloudSystemHistory = apps.get_model('partners', 'CloudSystemHistory')
    CloudSystemId = apps.get_model('partners', 'CloudSystemId')
    records = []
    from_ts = datetime.datetime(2023, 6,1, tzinfo=datetime.timezone.utc)
    for system in CloudSystemId.objects.all():
        records.append(CloudSystemHistory(
            cloud_system=system,
            organization=system.organization,
            from_ts=from_ts
        ))
    CloudSystemHistory.objects.bulk_create(records, batch_size=500)


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0046_reportsnapshot_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudSystemHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("from_ts", models.DateTimeField()),
                ("to_ts", models.DateTimeField(blank=True, null=True)),
                (
                    "cloud_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="partners.cloudsystemid",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="partners.organization",
                        null=True,
                        blank=True,
                    ),
                ),
            ],
        ),
        migrations.RunPython(fill_history)
    ]
