# Generated by Django 4.2.7 on 2024-04-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0046_reportsnapshot_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsnapshot',
            name='report_type',
            field=models.SmallIntegerField(choices=[(1, 'system_regular_report'), (2, 'system_expiring_report'), (20, 'organization_regular_system_reports'), (21, 'organization_regular_service_report'), (22, 'organization_regular_detail_table'), (23, 'organization_usage_report'), (24, 'organization_expiring_system_reports'), (25, 'organization_expiring_service_report'), (26, 'organization_expiring_detail_table'), (40, 'channel_partner_organization_regular_usages'), (45, 'channel_partner_organization_expiring_usages'), (41, 'channel_partner_channel_partner_regular_usages'), (46, 'channel_partner_channel_partner_expiring_usages'), (42, 'channel_partner_regular_detail_table'), (47, 'channel_partner_expiring_detail_table'), (43, 'channel_partner_regular_service_report'), (48, 'channel_partner_expiring_service_report'), (44, 'channel_partner_usage_report')]),
        ),
    ]
