# Generated by Django 4.2.7 on 2024-04-17 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0047_alter_reportsnapshot_report_type'),
        ('partners', '0047_cloudsystemhistory'),
    ]

    operations = [
    ]
