# Generated by Django 4.2.7 on 2024-04-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0048_merge_20240417_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelpartnerservice',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
