# Generated by Django 4.2.7 on 2024-05-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0049_channelpartnerservice_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelpartner",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="channelpartnertouser",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="organizationtouser",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
