# Generated by Django 4.2.7 on 2024-05-24 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0050_channelpartner_last_modified_ts_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemServiceCurrentQuantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("updated_ts", models.DateTimeField(auto_now=True)),
                (
                    "cloud_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="partners.cloudsystemid",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="partners.organization",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="partners.channelpartnerservice",
                    ),
                ),
            ],
            options={
                "unique_together": {("cloud_system", "organization", "service")},
            },
        ),
    ]
