# Generated by Django 4.2.7 on 2024-05-29 01:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0051_systemservicecurrentquantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemservicecurrentquantity",
            name="cloud_system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="system_service_current_quantities",
                to="partners.cloudsystemid",
            ),
        ),
        migrations.CreateModel(
            name="OrganizationPriceChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                ("created_ts", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "service_properties",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="partners.servicetoorganizationproperties",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChannelPartnerPriceChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                ("created_ts", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "service_properties",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="partners.servicetosubchannelproperties",
                    ),
                ),
            ],
        ),
    ]
