# Generated by Django 4.2.7 on 2024-05-28 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0051_systemservicecurrentquantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemservicecurrentquantity",
            name="cloud_system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="system_service_current_quantities",
                to="partners.cloudsystemid",
            ),
        ),
    ]
