# Generated by Django 4.2.7 on 2024-06-04 20:52

from django.db import migrations

from partners.models import OrganizationRoles


def alter_role_name(apps, schema_editor):
    OrganizationRole = apps.get_model("partners", "OrganizationRole")
    OrganizationRole.objects.filter(id=OrganizationRoles.SYSTEM_ADMINISTRATOR).update(name='Systems Administrator')


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0052_alter_systemservicecurrentquantity_cloud_system_and_more"),
    ]

    operations = [
        migrations.RunPython(alter_role_name),
    ]
