# Generated by Django 4.2.7 on 2024-06-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0053_auto_20240604_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelpartner',
            name='descendant_version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cloudsystemid',
            name='version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clouduser',
            name='version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='descendant_version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemgroup',
            name='descendant_version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemgroup',
            name='version',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
