# Generated by Django 4.2.7 on 2024-06-10 16:51

from django.db import migrations, models

from partners.tasks.services import new_channel_partner_service_created


def set_cloned_services(apps, schema_editor):
    ChannelPartnerService = apps.get_model("partners", "ChannelPartnerService")
    ChannelPartnerService.objects.filter(parent_service__isnull=False).update(cloned=True)


def propagate_cloned_services(apps, schema_editor):
    ChannelPartnerService = apps.get_model("partners", "ChannelPartnerService")
    root_services = ChannelPartnerService.objects.filter(parent_service__isnull=True)
    for root_service in root_services:
        new_channel_partner_service_created(root_service.pk)


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0054_channelpartner_descendant_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelpartnerservice",
            name="cloned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="channelpartnerservice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cloned", True)),
                fields=("created_by_channel_partner", "parent_service"),
                name="cloned_service_unique",
            ),
        ),
        migrations.RunPython(set_cloned_services),
        migrations.RunPython(propagate_cloned_services),
    ]
