# Generated by Django 4.2.7 on 2024-06-25 20:32

from django.db import migrations

from partners.models import VmsRoles


def add_system_disconnect_permission(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    OrganizationRole = apps.get_model("partners", "OrganizationRole")
    Organization = apps.get_model("partners", "Organization")
    organization_content_type = ContentType.objects.get_for_model(model=Organization)
    disconnect_systems, _ = Permission.objects.get_or_create(
        codename="disconnect_systems", content_type=organization_content_type)
    disconnect_systems.name = "Can disconnect systems from the Organization"
    disconnect_systems.save()
    manage_systems, _ = Permission.objects.get_or_create(
        codename="manage_systems")
    manage_systems.name = "Can add systems to the Organization and create, edit, delete groups"
    manage_systems.save()
    vms_system_administrators = OrganizationRole.objects.filter(system_role_uuid=VmsRoles.ADMINISTRATOR)
    for role in vms_system_administrators:
        role.permissions.add(disconnect_systems)


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0055_channelpartnerservice_cloned_and_more"),
    ]

    operations = [
        migrations.RunPython(add_system_disconnect_permission),
    ]
