# Generated by Django 4.2.7 on 2024-07-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0056_auto_20240625_2032"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportsnapshot",
            name="schema_version",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
