# Generated by Django 4.2.7 on 2024-10-02 17:23

from django.db import migrations

LOCAL_RECORDING = 0
TRIAL = 2

def change_trial_period(apps, schema_editor):
    ChannelPartnerService = apps.get_model("partners", "ChannelPartnerService")
    trail_services = ChannelPartnerService.objects.filter(type=LOCAL_RECORDING, sub_type=TRIAL)
    trail_services.update(duration=24)

class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0056_auto_20240625_2032"),
    ]

    operations = [
        migrations.RunPython(change_trial_period),
    ]
