# Generated by Django 4.2.7 on 2024-08-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0057_reportsnapshot_schema_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clouduser",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
