# Generated by Django 4.2.7 on 2024-08-09 18:58

from django.db import migrations

from partners.models import OrganizationRoles


def rename_role(apps, schema_editor):
    OrganizationRole = apps.get_model("partners", "OrganizationRole")
    OrganizationRole.objects.filter(id=OrganizationRoles.SYSTEM_ADMINISTRATOR).update(name='System Administrator')

def rollback_rename_role(apps, schema_editor):
    OrganizationRole = apps.get_model("partners", "OrganizationRole")
    OrganizationRole.objects.filter(id=OrganizationRoles.SYSTEM_ADMINISTRATOR).update(name='Systems Administrator')
class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0058_alter_clouduser_email"),
    ]

    operations = [
        migrations.RunPython(rename_role, rollback_rename_role),
    ]
