# Generated by Django 4.2.7 on 2024-08-09 21:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0059_auto_20240809_1858"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportsnapshot",
            name="schema_version",
        ),
    ]
