# Generated by Django 4.2.7 on 2024-08-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0060_remove_reportsnapshot_schema_version"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reportsnapshot",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="reportsnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("service_id__isnull", True)),
                fields=("entity_id", "report_type", "start_date"),
                name="unique_report_snapshot_usage",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportsnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("organization_id__isnull", True), ("service_id__isnull", False)
                ),
                fields=("entity_id", "report_type", "service_id", "start_date"),
                name="unique_report_snapshot_service",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportsnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("organization_id__isnull", False), ("service_id__isnull", False)
                ),
                fields=(
                    "entity_id",
                    "report_type",
                    "service_id",
                    "organization_id",
                    "start_date",
                ),
                name="unique_report_snapshot_system",
            ),
        ),
    ]
