# Generated by Django 4.2.7 on 2024-09-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0062_add_default_logging_switch_to_waffle"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetoorganizationproperties",
            name="expiring_at",
            field=models.DateTimeField(null=True),
        ),
    ]
