# Generated by Django 4.2.7 on 2024-09-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0063_update_service_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelpartnerservice',
            name='sub_type',
            field=models.IntegerField(choices=[(0, 'Regular'), (1, 'Demo'), (2, 'Credit')], default=0),
        ),
    ]
