# Generated by Django 4.2.7 on 2024-09-25 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0064_alter_channelpartnerservice_sub_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceToSystemProperties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expiration_date", models.DateTimeField(null=True)),
                (
                    "cloud_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_properties",
                        to="partners.cloudsystemid",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="system_properties",
                        to="partners.channelpartnerservice",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="servicetosystemproperties",
            constraint=models.UniqueConstraint(
                fields=("service", "cloud_system"),
                name="unique_service_system_properties",
            ),
        ),
    ]
