# Generated by Django 4.2.7 on 2024-10-02 21:33

from django.db import migrations, models
import partners.validators


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0065_servicetosystemproperties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionconfirmation',
            name='changes',
            field=models.JSONField(null=True, validators=[partners.validators.validate_dict_max_size]),
        ),
        migrations.AlterField(
            model_name='channelpartner',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, validators=[partners.validators.validate_dict_max_size]),
        ),
        migrations.AlterField(
            model_name='channelpartnerservice',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, validators=[partners.validators.validate_dict_max_size]),
        ),
        migrations.AlterField(
            model_name='channelpartnertouser',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, validators=[partners.validators.validate_dict_max_size]),
        ),
        migrations.AlterField(
            model_name='cloudsystemid',
            name='current_services',
            field=models.JSONField(default=dict, validators=[partners.validators.validate_dict_max_size]),
        ),
        migrations.AlterField(
            model_name='cloudsystemid',
            name='security_statuses',
            field=models.JSONField(default=dict, validators=[partners.validators.validate_dict_max_size]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, validators=[partners.validators.validate_dict_max_size]),
        ),
    ]
