# Generated by Django 4.2.7 on 2024-10-02 23:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0057_auto_20241002_1723"),
        ("partners", "0066_alter_actionconfirmation_changes_and_more"),
    ]

    operations = []
