# Generated by Django 4.2.7 on 2024-10-09 18:53

from django.db import migrations

"""
This migration is empty and is here to fix the migration name.
There was made mistake in follow-up requests and merge migration 
was committed to develop and 23.3.4 branches with different name. 
To avoid issue with further follow-up request we need to make 
last migrations names similar in those branches.
"""

class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0067_merge_20241002_2341"),
    ]

    operations = []
