# Generated by Django 4.2.7 on 2024-10-17 00:29

from django.db import migrations

LOCAL_RECORDING = 0
REGULAR = 0
DEMO = 1
CREDIT = 2

def rename_services(apps, schema_editor):
    ChannelPartnerService = apps.get_model("partners", "ChannelPartnerService")
    local_recordings = ChannelPartnerService.objects.filter(type=LOCAL_RECORDING)
    local_recordings.filter(sub_type=REGULAR).update(name="Core")
    local_recordings.filter(sub_type=DEMO).update(name="Demo Core")
    local_recordings.filter(sub_type=CREDIT).update(name="Credit Core")


def fallback(apps, schema_editor):
    ChannelPartnerService = apps.get_model("partners", "ChannelPartnerService")
    local_recordings = ChannelPartnerService.objects.filter(type=LOCAL_RECORDING)
    local_recordings.filter(sub_type=REGULAR).update(name="Device Service")
    local_recordings.filter(sub_type=DEMO).update(name="Demo Device Service")
    local_recordings.filter(sub_type=CREDIT).update(name="Credit Device Service")


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0068_fix_migration_name_20241009_1853"),
    ]

    operations = [
        migrations.RunPython(rename_services, reverse_code=fallback),
    ]
