# Generated by Django 4.2.16 on 2024-11-07 22:40

from django.db import migrations
from django.db.models import Count
from django.db.models.functions import Lower
import partners

def make_email_lowercase(apps, schema_editor):
    CloudUser = apps.get_model("partners", "CloudUser")
    incorrect_emails = CloudUser.objects.exclude(email=Lower('email'))
    incorrect_emails.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0069_auto_20241017_0029"),
    ]

    operations = [
        migrations.RunPython(make_email_lowercase),
        migrations.AlterField(
            model_name="clouduser",
            name="email",
            field=partners.utils.db.LowerCaseEmailField(max_length=255, unique=True),
        ),
    ]
