import LABEL_FORMATS from './label_formats'
import { SECOND, MINUTE, HOUR, DAY, ROUGH_YEAR, ROUGH_MONTH } from '../intervals/regularLengthIntervals'

export const primaryRulerDateFormats = {
  [SECOND]: LABEL_FORMATS.SECONDS_ONLY,
  [5 * SECOND]: LABEL_FORMATS.SECONDS_ONLY,
  [10 * SECOND]: LABEL_FORMATS.SECONDS_ONLY,
  [30 * SECOND]: LABEL_FORMATS.SECONDS_ONLY,
  [MINUTE]: LABEL_FORMATS.HOURS_24_SECONDS,
  [5 * MINUTE]: LABEL_FORMATS.HOURS_24,
  [10 * MINUTE]: LABEL_FORMATS.HOURS_24,
  [30 * MINUTE]: LABEL_FORMATS.HOURS_24,
  [HOUR]: LABEL_FORMATS.HOURS_24,
  [3 * HOUR]: LABEL_FORMATS.HOURS_24,
  [6 * HOUR]: LABEL_FORMATS.HOURS_24,
  [12 * HOUR]: LABEL_FORMATS.HOURS_24,
  [DAY]: LABEL_FORMATS.DAY,

  [ROUGH_MONTH]: LABEL_FORMATS.MONTH,
  [3 * ROUGH_MONTH]: LABEL_FORMATS.MONTH,
  [6 * ROUGH_MONTH]: LABEL_FORMATS.MONTH,
  [ROUGH_YEAR]: LABEL_FORMATS.YEAR,
  [10 * ROUGH_YEAR]: LABEL_FORMATS.YEAR,
  [100 * ROUGH_YEAR]: LABEL_FORMATS.YEAR,

  month: LABEL_FORMATS.MONTH,
  'quarter-year': LABEL_FORMATS.MONTH,
  'half-year': LABEL_FORMATS.MONTH,
  'year': LABEL_FORMATS.YEAR,
  'decade': LABEL_FORMATS.YEAR,
  'century': LABEL_FORMATS.YEAR,
}

export default primaryRulerDateFormats
