from RobotVariables import RobotVariables

rb = RobotVariables("en_US")

GOOD_PASSWORDS = [
    rb.LOWER_UPPER_NUMBER_PASSWORD,
    rb.LOWER_UPPER_SYMBOL_PASSWORD,
    rb.LOWER_NUMBER_SYMBOL_PASSWORD,
    rb.UPPER_NUMBER_SYMBOL_PASSWORD,
    rb.BASE_PASSWORD
    ]

WEAK_PASSWORDS = [
    rb.UPPERCASE_PASSWORD, 
    rb.LOWERCASE_PASSWORD, 
    rb.COMMON_PASSWORD, 
    rb.NUMBERS_PASSWORD, 
    rb.SYMBOL_ONLY_PASSWORD
    ]

FAIR_PASSWORDS = [
    rb.LOWER_UPPER_PASSWORD,
    rb.LOWER_NUMBER_PASSWORD,
    rb.LOWER_SYMBOL_PASSWORD,
    rb.UPPER_NUMBER_PASSWORD,
    rb.UPPER_SYMBOL_PASSWORD,
    rb.NUMBER_SYMBOL_PASSWORD,
    rb.SYMBOL_PASSWORD
    ]

INCORRECT_PASSWORDS = [
    rb.CYRILLIC_TEXT,
    rb.SMILEY_TEXT,
    rb.GLYPH_TEXT,
    rb.TM_TEXT,
    f' {rb.BASE_PASSWORD}',
    f'{rb.BASE_PASSWORD} '
]