variables_dict = {
    "ALERT": "//div[contains(@class,'toast')]//span[contains(@class,'toast-content')]",
    "ALERT_CLOSE": "//div[contains(@class,'toast')]/button[contains(@class,'close') and @data-dismiss='alert']",
    "BROWSER": "Chrome",
    "LANGUAGE_DROPDOWN": "//header//nx-header-language-select//button[@data-testid='dropdownMenuButton']",
    "LANGUAGE": "en_US",
    "LANGUAGE_TO_SELECT": "//header//nx-header-language-select//span[@lang='{LANGUAGE}']/..",
    "DOWNLOAD_LINK": "//footer//a[@href='/download']",
    "ACCOUNT_DOES_NOT_EXIST_TEXT": "Account does not exist.",
    "YOU_CAN_CREATE_ACCOUNT_TEXT": "You can create an account with this email address or try to enter a different one.",
    "ACCOUNT_CREATION_EMAIL_SUCCESS": "//nx-authorize-component//nx-authorize-activate-account-component//main//h3",
    "MODAL_DIALOG": "//nx-modal-generic-content",
    "LOGGED_IN_CLOSE_BUTTON": "//nx-modal-generic-content//button//span[@class='close-icon']/../..",
    "ENV": "https://cloud-test.hdw.mx/",
    "LOG_IN_MODAL": "//nx-authorize-component/div[@class='authorize-main main-w']",
    "LOG_IN_NEXT_BUTTON": "//nx-authorize-component//nx-process-button[@data-testid='btnLogin']",
    "EMAIL_INPUT": "//nx-authorize-component//input[@id='authorizeEmail']",
    "PASSWORD_INPUT": "//nx-authorize-component//input[@id='authorizePassword' and @name='password' and @type='password']",
    "LOG_IN_BUTTON": "//nx-authorize-component//nx-process-button[@data-testid='btnLogin']",
    "YOU_CAN_CREATE_AN_ACCOUNT": "//nx-authorize-component//p[contains(text(),'{YOU_CAN_CREATE_ACCOUNT_TEXT}')]",
    "ACCOUNT_DOES_NOT_EXIST": "//nx-authorize-component//p[contains(text(),'{ACCOUNT_DOES_NOT_EXIST_TEXT}')]",
    "LOG_IN_BUTTON_TEXT": "Log In",
    "LOG_IN_NAV_BAR": "//header//a[contains(text(),'{LOG_IN_BUTTON_TEXT}')]/..",
    "HEADER_ICON_LINK": "//nx-header/header//div[@class='app-header-left']//a[contains(@class, 'navbar-brand')]",
    "LOGO_ICON": "//nx-header/header//div[@class='app-header-left']//a[contains(@class, 'navbar-brand')]/img",
    "ERROR_COLOR": "rgb(240, 44, 44)",
    "ERROR_COLOR_WITH_OPACITY":"rgba(240, 44, 44, 1)",
    "TEST_EMAIL"  : "noptixautoqa",
    "BASE_EMAIL" : "{TEST_EMAIL}+sendemail@gmail.com",
    'CUST_LANGUAGE_LIST' : "/Users/clandrum/cloud_portal/robot_tests/customizations/default_lang_list.json",
    'FORGOT_PASSWORD_BUTTON' : "//button//span[contains(text(), '{FORGOT_PASSWORD_TEXT}')]",
    'RESTORE_PASSWORD_EMAIL_INPUT' : """//nx-authorize-reset-request-component//input[@type="email" and @id="resetPasswordEmail"]""",
    'RESET_PASSWORD_PAGE_BUTTON': "//nx-authorize-reset-request-component//footer//nx-process-button//button[contains(text(), '{RESET PASSWORD BUTTON TEXT}')]",
    'RESET_PASSWORD_BUTTON' : """//button[contains(@class,"btn btn-primary") and contains(text(), "{RESET_PASSWORD_BUTTON_TEXT}")]""",
    'BASE_HOST' : 'imap.gmail.com',
    'BASE_EMAIL_PASSWORD' : 'lvhnwgmuoofzmvza',
    'BASE_EMAIL' : 'noptixautoqa@gmail.com',
    'BASE_EMAIL_SENDEMAIL' : 'noptixautoqa+sendemail@gmail.com',
    'BASE_PORT' : '993',
    'ANONYMOUS_BODY' : """//body[contains(@class,'anonymous')]//h1[@data-testid="welcomeCaption" or @id="welcomeCaption"]""",
    'BASE_EMAIL_DEFAULT' : False ,
    'CREATE_ACCOUNT_BODY' : "//nx-landing-component//a[@href='/authorize?client_type=create']",
    "COPYRIGHT SYMBOL" : "©",
    "COMPANY" : "Network Optix",
    "PRIVACY_POLICY_FULL_URL" : "https://www.networkoptix.com/privacy-policy"
}
variables = {
    'url': 'ENV',
    'EXISTING_EMAIL': 'noptixautoqa+viewer@gmail.com',
    'VALID_EMAIL': 'noptixqa+valid@gmail.com',
    'BASE_PASSWORD': 'qweasd 123',
    'password': '{BASE_PASSWORD}',
    'ANONYMOUS_BODY': '//body[contains(@class,"anonymous")]//h1[@data-testid="welcomeCaption" or @id="welcomeCaption"]',
    'REGISTER_FORM': '//nx-authorize-create-account-component',
    'REGISTER_FIRST_NAME_INPUT': '{REGISTER_FORM}//form//input[@id="firstName"]',
    'REGISTER_LAST_NAME_INPUT': '{REGISTER_FORM}//form//input[@id="lastName"]',
    'REGISTER_EMAIL_INPUT': '{REGISTER_FORM}//form//nx-email-input/input[@id="email"]',
    'REGISTER_EMAIL_INPUT_LOCKED': '{REGISTER_FORM}//form//input[@name="registerEmailLocked"]',
    'REGISTER_PASSWORD_INPUT': '{REGISTER_FORM}//form//nx-password-input//input[@id="createAccountPassword"]',
    'REGISTER_LOG_IN_BUTTON': '{REGISTER_FORM}//button[@id="btnActivateLogin"]',
    'REGISTER_BACK_BUTTON': '{REGISTER_FORM}//button/span[text()="{BACK_TEXT}"]/..',
    'REGISTER_NOT_ACTIVATED': '//nx-authorize-component//form[@name="emailForm"]//p[contains(text(),"{ACCOUNT_NOT_ACTIVATED}")]',
    'TERMS_AND_CONDITIONS_CHECKBOX_VISIBLE': '{REGISTER_FORM}//nx-checkbox[@name="termsAndConditions"]',
    'TERMS_AND_CONDITIONS_CHECKBOX_REAL': '{TERMS_AND_CONDITIONS_CHECKBOX_VISIBLE}//input[@id="termsAndConditions"]',
    'CREATE_ACCOUNT_BUTTON': '{REGISTER_FORM}//button[contains(text(),"{CREATE_ACCOUNT_BUTTON_TEXT}")]',
    'TERMS_AND_CONDITIONS_LINK': '{REGISTER_FORM}//a[@href="/content/eula"]',
    'TERMS_AND_CONDITIONS_ERROR': '{REGISTER_FORM}//nx-checkbox/../following-sibling::p[contains(@class,"error-label") and contains(text(),"{REQUIRED_TEXT}")]',
    'PRIVACY_POLICY_LINK': '{REGISTER_FORM}//a[@href="{PRIVACY_POLICY_URL_HREF}"]',
    'RESEND_ACTIVATION_LINK_BUTTON': '//nx-authorize-email-component//p[contains(@class,"fake-link") and contains(text(),"{RESEND_ACTIVATION_LINK_BUTTON_TEXT}")]',
    'REGISTER_EYE_ICON_OPEN': '{REGISTER_FORM}{EYE_ICON_OPEN}',
    'REGISTER_EYE_ICON_CLOSED': '{REGISTER_FORM}{EYE_ICON_CLOSED}',
    'INVITED_TO_SYSTEM_EMAIL_SUBJECT_UNREGISTERED': '{{message.sharer_name}} invites you to %PRODUCT_NAME%',
    'ACCOUNT_CREATION_SUCCESS': '//nx-authorize-activate-account-component',
    'ACCOUNT_CREATION_SUCCESS_ICON': '//div[@name="ACCOUNT_CREATED"]/svg-icon',
    'ACCOUNT_CREATION_CONFIRMATION': '{ACCOUNT_CREATION_SUCCESS}/following-sibling::div[@name="ACCOUNT_CREATED"]',
    'FROM_EMAIL_DEFAULT': False,
    'PASSWORD_BADGE': '//nx-password-input-tag-validation',
    'PASSWORD_IS_WEAK_BADGE': '{PASSWORD_BADGE}//nx-tag//a[contains(@class,badge) and contains(text(),"{PASSWORD_IS_WEAK_BADGE_TEXT}")]',
    'PASSWORD_IS_FAIR_BADGE': '{PASSWORD_BADGE}//nx-tag//a[contains(@class,badge) and contains(text(),"{PASSWORD_IS_FAIR_BADGE_TEXT}")]',
    'PASSWORD_IS_GOOD_BADGE': '{PASSWORD_BADGE}//nx-tag//a[contains(@class,badge) and contains(text(),"{PASSWORD_IS_GOOD_BADGE_TEXT}")]',
    'PASSWORD_IS_TOO_SHORT_BADGE': '{PASSWORD_BADGE}//nx-tag//a[contains(@class,badge) and contains(text(),"{PASSWORD_IS_TOO_SHORT_BADGE_TEXT}")]',
    'PASSWORD_IS_TOO_COMMON_BADGE': '{PASSWORD_BADGE}//nx-tag//a[contains(@class,badge) and contains(text(),"{PASSWORD_IS_TOO_COMMON_BADGE_TEXT}")]',
    'PASSWORD_INCORRECT_BADGE': '{PASSWORD_BADGE}//nx-tag//a[contains(@class,badge) and contains(text(),"{PASSWORD_INCORRECT_BADGE_TEXT}")]',
    'PASSWORD_BADGE_TOOLTIP': '//nx-tooltip-component',
    'COMMON_PASSWORD': 'qweasd123',
    'SYMBOL_PASSWORD': 'pass!@#$%^&*()_-+=;:''`~,./\|?[]{}',
    'LOWERCASE_PASSWORD': 'adrhartjad',
    'UPPERCASE_PASSWORD': 'ADRHARTJAD',
    'NUMBERS_PASSWORD': '13462344',
    'SEVENCHAR_PASSWORD': 'asdfghj',
    'SYMBOL_ONLY_PASSWORD': '!@#$%^&*()_-+=',
    'SEVEN_CHAR_PASSWORD': 'asdfghj',
    'LOWER_UPPER_PASSWORD': 'multPASS',
    'LOWER_NUMBER_PASSWORD': 'mult1234',
    'LOWER_SYMBOL_PASSWORD': 'mult!@#$',
    'UPPER_NUMBER_PASSWORD': 'MULT1234',
    'UPPER_SYMBOL_PASSWORD': 'MULT!@#$',
    'NUMBER_SYMBOL_PASSWORD': '1234!@#$',
    'LOWER_UPPER_NUMBER_PASSWORD': 'qweASD123',
    'LOWER_UPPER_SYMBOL_PASSWORD': 'qweASD!@#',
    'LOWER_NUMBER_SYMBOL_PASSWORD': 'qwe123!@#',
    'UPPER_NUMBER_SYMBOL_PASSWORD': 'QWE123!@#',
    'COMBO_TEXT': 'Кенг☿☂⊗⅓您都可以`~!@#$%계정이 이',
    'CYRILLIC_TEXT': 'Кенгшщзх',
    'SMILEY_TEXT': '☠☿☂⊗⅓∠∩λ℘웃♞⊀☻★',
    'GLYPH_TEXT': '您都可以享受源源不あなたのアカウント',
    'SYMBOL_TEXT': "`~!@#$%^&*()_:;'{}[]+<>?,./\"",
    'TM_TEXT': 'qweasdzxc123®™',
    'KOREAN_TEXT': '계정이 이미 활성',
    'FIRST_NAME_IS_REQUIRED': '{REGISTER_FIRST_NAME_INPUT}/following-sibling::p[contains(@class,error-label) and contains(text(),"{REQUIRED_TEXT}")]',
    'LAST_NAME_IS_REQUIRED': '{REGISTER_LAST_NAME_INPUT}/following-sibling::p[contains(@class,error-label) and contains(text(),"{REQUIRED_TEXT}")]',
    'EMAIL_IS_REQUIRED': '{REGISTER_EMAIL_INPUT}/../following-sibling::p[contains(@class,error-label) and contains(text(),"{REQUIRED_TEXT}")]',
    'EMAIL_ALREADY_REGISTERED': '//p[contains(@class,error-label) and contains(text(),"{EMAIL_ALREADY_REGISTERED_TEXT}")]',
    'EMAIL_INVALID': '//p[contains(@class,error-label) and contains(text(),"{EMAIL_INVALID_TEXT}")]',
    'PASSWORD_SPECIAL_CHARS': '//div[contains(@class,input-error) and contains(text(),"{PASSWORD_SPECIAL_CHARS_TEXT}")]',
    'PASSWORD_IS_WEAK': '//div[contains(@class,input-error) and contains(text(),"{PASSWORD_IS_WEAK_TEXT}")]',
    'PASSWORD_TOO_SHORT': '//div[contains(@class,input-error) and contains(text(),"{PASSWORD_TOO_SHORT_TEXT}")]',
    'PASSWORD_TOO_COMMON': '//div[contains(@class,input-error) and contains(text(),"{PASSWORD_TOO_COMMON_TEXT}")]',
    'PASSWORD_IS_REQUIRED': '//div[contains(@class, input-error) and contains(text(),"{REQUIRED_TEXT}")]',
    'TERMS_AND_CONDITIONS_CHECKBOX_VISIBLE': '{REGISTER_FORM}//nx-checkbox[@name="termsAndConditions"]',
    'TERMS_AND_CONDITIONS_CHECKBOX_REAL': '{TERMS_AND_CONDITIONS_CHECKBOX_VISIBLE}//input[@id="termsAndConditions"]',
    'TERMS_AND_CONDITIONS_LINK': '{REGISTER_FORM}//a[@href=/content/eula]',
    'TERMS_AND_CONDITIONS_ERROR': '{REGISTER_FORM}//nx-checkbox/../following-sibling::p[contains(@class,error-label) and contains(text(),"{REQUIRED_TEXT}")]'
}



