include:
  - local: "ci/Docker/.version-enforced.yml"

variables:
  DJANGO_PYTHON_IMAGE: '${DOCKER_REGISTRY}/nx/cloud_portal_django_python'
  CLOUD_IMAGE_VERSION: '45833'
  DJANGO_PYTHON_IMAGE_TAG: '${CLOUD_IMAGE_VERSION}'


# Required CI/CD variables, which should be defined on Gitlab instance layer
# https://docs.gitlab.com/ee/ci/variables/#add-a-cicd-variable-to-an-instance:
# - PIP_TRUSTED_HOST
# - PIP_INDEX_URL
# - ARTIFACTORY_URL
docker:build-django-python:
  extends: .version-enforced-docker
  interruptible: true
  variables:
    IMAGE_VERSION: '${CLOUD_IMAGE_VERSION}'
    BUILD_OPTIONS: |
      --build-arg PIP_TRUSTED_HOST=${PIP_TRUSTED_HOST}
      --build-arg PIP_INDEX_URL=${ARTIFACTORY_URL}/api/pypi/pypi-python3.8-alpine3.12/simple
      --build-arg PIP_EXTRA_INDEX_URL=${PIP_INDEX_URL}
  before_script:
  - !reference [".version-enforced-docker", "before_script"]
  - |
    DOCKER_DIR="ci/Docker/django-python"
    touch build-django.env

    echo "DJANGO_PYTHON_IMAGE_TAG=${DJANGO_PYTHON_IMAGE_TAG}" > build-django.env

    TARGET_IMAGE="${DJANGO_PYTHON_IMAGE}"
    TARGET_IMAGE_TAG="${DJANGO_PYTHON_IMAGE_TAG}"
  artifacts:
    reports:
      dotenv: build-django.env
    expire_in: 14 days
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event" ||
      ($CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_PROTECTED == "true")
    changes:
    - ci/Docker/django-python/*
    - build_scripts/**/requirements.txt
    - cloud/**/pyproject.toml
    - cloud/**/poetry.lock
    - cloud/**/poetry.toml
    - cloud/**/allowed_licenses.txt
