variables:
  DJANGO_PYTHON_IMAGE: "nx/cloud_portal_django_python"
  DJANGO_PYTHON_IMAGE_TAG: "1.1"

docker:build-django-python:
  extends: .docker.template
  before_script:
  - |
    DOCKER_DIR="ci/Docker/django-python"
    cp deploy/cloud_portal/docker/pip.conf .
    cp cloud/requirements.txt .
    touch build-django.env
    if [[ "${CI_PIPELINE_SOURCE}" == "merge_request_event" ]]; then
      DJANGO_PYTHON_IMAGE_TAG="${DJANGO_PYTHON_IMAGE_TAG}.${CI_MERGE_REQUEST_ID}.SNAPSHOT"
      echo "DJANGO_PYTHON_IMAGE_TAG=${DJANGO_PYTHON_IMAGE_TAG}" > build-django.env
    fi
    TARGET_IMAGE="${DJANGO_PYTHON_IMAGE}"
    TARGET_IMAGE_TAG="${DJANGO_PYTHON_IMAGE_TAG}"
  artifacts:
    reports:
      dotenv: build-django.env
    expire_in: 14 days
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event" ||
      ($CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_PROTECTED == "true")
    changes:
    - ci/Docker/django-python/*
    - cloud/requirements.txt
