export function setupCameras(): unknown[] {
    return [
        {
            audioEnabled: false,
            backupType: 'CameraBackupDisabled',
            controlEnabled: false,
            dewarpingParams: '',
            disableDualStreaming: false,
            failoverPriority: 'Never',
            groupId: '',
            groupName: '',
            licenseUsed: false,
            logicalId: '',
            mac: '00-00-00-00-00-00',
            manuallyAdded: false,
            maxArchiveDays: -30,
            minArchiveDays: -1,
            model: 'DWC-MV72i28V',
            motionMask: '',
            motionType: '0',
            name: 'DWC-MV72i28V',
            physicalId: 'urn_uuid_333236313337-3335-2d33-3233-312d3330',
            preferredServerId: '{00000000-0000-0000-0000-000000000000}',
            recordAfterMotionSec: 0,
            recordBeforeMotionSec: 0,
            scheduleEnabled: false,
            scheduleTasks: [],
            status: 'Unauthorized',
            statusFlags: 'CSF_NoFlags',
            typeId: '{eb1e8a6a-da43-5c75-c08f-72f94205e0d9}',
            url: 'http://10.1.5.186:8080/onvif/device_service',
            userDefinedGroupName: '',
            id: '{3ed289c8-27da-aeba-4c47-6a69b3b983a7}',
            parentId: '{2d624ba5-a762-f38a-60ba-14240c70276f}',
            dayOfWeek: 4,
            maxFps: 15,
            addParamsRaw: [
                {
                    name: 'DeviceUrl',
                    value: 'http://10.1.5.186:8080/onvif/device_service',
                },
                {
                    name: 'compatibleAnalyticsEngines',
                    value: '[]',
                },
                {
                    name: 'defaultCredentials',
                    value: 'admin:******',
                },
                {
                    name: 'driverClass',
                    value: 'QnDigitalWatchdogResource',
                },
                {
                    name: 'firmware',
                    value: '',
                },
            ],
            motionEnabled: true,
            recordingSettings: {
                recording: false,
                quality: 'high',
                fps: 15,
                motionEnabled: true,
                modes: [
                    {
                        name: 'always',
                        id: 'RT_Always',
                        value: 0,
                        enabled: true,
                    },
                    {
                        name: 'motion',
                        id: 'RT_MetadataOnly',
                        value: 0,
                        enabled: true,
                    },
                    {
                        name: 'motionLowRes',
                        id: 'RT_MetadataAndLowQuality',
                        value: 0,
                        enabled: true,
                    },
                ],
            },
            parsedAddParams: {},
            isAudioSupported: false,
            secondsToday: 74956,
            parentName: 'Server dev',
            previewUrl:
                'https://c27aaff0-0694-469b-a8d6-c43cd8a9648c.relay.vmsproxy.hdw.mx/ec2/cameraThumbnail?ignoreExternalArchive&cameraId=3ed289c8-27da-aeba-4c47-6a69b3b983a7&time=LATEST&height=120&rotate=0&auth=MTVkNDdlZjc0YTk0NDJkMzgzODE1MDA2ZGM1YzBlN2UtMzQyNTcyODY4NzpuaXdYNUlkcEJuaUFsNXNGelRYYTFoZmdvbHJVVTg9aHp4cHBjOjRlNWUxMGFiZmZiNmYwMjRhNzkzODk3OTQ4ODk5OTJm',
            vendor: 'Digital Watchdog',
            isStream: false,
        },
        {
            audioEnabled: false,
            backupType: 'CameraBackupDisabled',
            controlEnabled: false,
            dewarpingParams: '',
            disableDualStreaming: false,
            failoverPriority: 'Never',
            groupId: '',
            groupName: '',
            licenseUsed: false,
            logicalId: '',
            mac: '00-00-00-00-00-00',
            manuallyAdded: false,
            maxArchiveDays: -30,
            minArchiveDays: -1,
            model: 'VIVOTEK',
            motionMask: '',
            motionType: '0',
            name: 'FD9165-HTVIVOTEK',
            physicalId: 'urn_uuid_d56c909c-019b-bf01-2208-59ac5a4c08fe',
            preferredServerId: '{00000000-0000-0000-0000-000000000000}',
            recordAfterMotionSec: 0,
            recordBeforeMotionSec: 0,
            scheduleEnabled: false,
            scheduleTasks: [],
            status: 'Unauthorized',
            statusFlags: 'CSF_NoFlags',
            typeId: '{9a55ee6b-a595-5807-a5ba-d4aff697dc12}',
            url: 'http://10.1.5.198:80/onvif/device_service',
            userDefinedGroupName: '',
            id: '{838a6c54-76aa-cd65-e20c-79e5bfd3b85f}',
            parentId: '{2d624ba5-a762-f38a-60ba-14240c70276f}',
            dayOfWeek: 4,
            maxFps: 15,
            addParamsRaw: [
                {
                    name: 'DeviceUrl',
                    value: 'http://10.1.5.198:80/onvif/device_service',
                },
                {
                    name: 'cameraCapabilities',
                    value: '65536',
                },
                {
                    name: 'compatibleAnalyticsEngines',
                    value: '[]',
                },
                {
                    name: 'defaultCredentials',
                    value: 'admin:******',
                },
                {
                    name: 'driverClass',
                    value: 'QnPlOnvifResource',
                },
                {
                    name: 'firmware',
                    value: '',
                },
            ],
            motionEnabled: true,
            recordingSettings: {
                recording: false,
                quality: 'high',
                fps: 15,
                motionEnabled: true,
                modes: [
                    {
                        name: 'always',
                        id: 'RT_Always',
                        value: 0,
                        enabled: true,
                    },
                    {
                        name: 'motion',
                        id: 'RT_MetadataOnly',
                        value: 0,
                        enabled: true,
                    },
                    {
                        name: 'motionLowRes',
                        id: 'RT_MetadataAndLowQuality',
                        value: 0,
                        enabled: true,
                    },
                ],
            },
            parsedAddParams: {},
            isAudioSupported: false,
            secondsToday: 74956,
            parentName: 'Server dev',
            previewUrl:
                'https://c27aaff0-0694-469b-a8d6-c43cd8a9648c.relay.vmsproxy.hdw.mx/ec2/cameraThumbnail?ignoreExternalArchive&cameraId=838a6c54-76aa-cd65-e20c-79e5bfd3b85f&time=LATEST&height=120&rotate=0&auth=MTVkNDdlZjc0YTk0NDJkMzgzODE1MDA2ZGM1YzBlN2UtMzQyNTcyODY4NzpuaXdYNUlkcEJuaUFsNXNGelRYYTFoZmdvbHJVVTg9aHp4cHBjOjRlNWUxMGFiZmZiNmYwMjRhNzkzODk3OTQ4ODk5OTJm',
            vendor: 'FD9165-HT',
            isStream: false,
        },
        {
            audioEnabled: false,
            backupType: 'CameraBackupDisabled',
            controlEnabled: false,
            dewarpingParams: '',
            disableDualStreaming: false,
            failoverPriority: 'Never',
            groupId: '',
            groupName: '',
            licenseUsed: false,
            logicalId: '',
            mac: '00-0D-F1-20-B5-02',
            manuallyAdded: false,
            maxArchiveDays: -30,
            minArchiveDays: -1,
            model: 'IP-Camera',
            motionMask: '',
            motionType: '0',
            name: 'IP-Camera',
            physicalId: 'urn_uuid_32306235-3032-6666-3238-000df120b502',
            preferredServerId: '{00000000-0000-0000-0000-000000000000}',
            recordAfterMotionSec: 0,
            recordBeforeMotionSec: 0,
            scheduleEnabled: false,
            scheduleTasks: [],
            status: 'Online',
            statusFlags: 'CSF_NoFlags',
            typeId: '{9a55ee6b-a595-5807-a5ba-d4aff697dc12}',
            url: 'http://10.1.5.116/onvif/device_service',
            userDefinedGroupName: '',
            id: '{b9544f11-e84a-9c1d-c58d-320d6898f9bd}',
            parentId: '{2d624ba5-a762-f38a-60ba-14240c70276f}',
            dayOfWeek: 4,
            maxFps: 30,
            addParamsRaw: [
                {
                    name: 'DeviceUrl',
                    value: 'http://10.1.5.116/onvif/device_service',
                },
                {
                    name: 'VideoLayout',
                    value: '',
                },
                {
                    name: 'cameraAdvancedParams',
                    value: '{"groups":[{"aux":"","description":"","groups":[{"aux":"","description":"","groups":[],"name":"Primary","params":[{"aux":"","availableInOffline":false,"bindDefaultToMinimum":false,"compact":false,"confirmation":"","dataType":"Enumeration","dependencies":[],"description":"","group":"","id":"primaryStream.codec","internalRange":"","keepInitialValue":false,"name":"Codec","notes":"","range":"H264,MJPEG","readCmd":"","readOnly":false,"resync":false,"showRange":false,"tag":"","unit":"","writeCmd":""},{"aux":"","availableInOffline":false,"bindDefaultToMinimum":false,"compact":false,"confirmation":"","dataType":"Enumeration","dependencies":[{"conditions":[{"paramId":"primaryStream.codec","type":"value","value":"H264"}],"id":"1b30d789-a517-c2bf-2241-70ce0c5eb978","internalRange":"","range":"1280x720,1920x1080","type":"Range","valuesToAddToRange":[],"valuesToRemoveFromRange":[]},{"conditions":[{"paramId":"primaryStream.codec","type":"value","value":"MJPEG"}],"id":"46ee1d72-dea0-c792-a632-5f57ab637689","internalRange":"","range":"1280x720,1920x1080","type":"Range","valuesToAddToRange":[],"valuesToRemoveFromRange":[]}],"description":"","group":"","id":"primaryStream.resolution","internalRange":"","keepInitialValue":false,"name":"Resolution","notes":"","range":"","readCmd":"","readOnly":false,"resync":false,"showRange":false,"tag":"","unit":"","writeCmd":""},{"aux":"","availableInOffline":false,"bindDefaultToMinimum":false,"compact":false,"confirmation":"Are you sure you want to set defaults for this stream?","dataType":"Button","dependencies":[],"description":"","group":"","id":"primaryStream.resetToDefaults","internalRange":"","keepInitialValue":false,"name":"Reset to Defaults","notes":"","range":"","readCmd":"","readOnly":false,"resync":true,"showRange":false,"tag":"","unit":"","writeCmd":""}]},{"aux":"","description":"","groups":[],"name":"Secondary","params":[{"aux":"","availableInOffline":false,"bindDefaultToMinimum":false,"compact":false,"confirmation":"","dataType":"Enumeration","dependencies":[],"description":"","group":"","id":"secondaryStream.codec","internalRange":"","keepInitialValue":false,"name":"Codec","notes":"","range":"H264,MJPEG","readCmd":"","readOnly":false,"resync":false,"showRange":false,"tag":"","unit":"","writeCmd":""},{"aux":"","availableInOffline":false,"bindDefaultToMinimum":false,"compact":false,"confirmation":"","dataType":"Enumeration","dependencies":[{"conditions":[{"paramId":"secondaryStream.codec","type":"value","value":"H264"}],"id":"315669a2-0c3a-1adb-d1ec-829dd145429b","internalRange":"","range":"352x240,352x288,640x480,704x480,704x576","type":"Range","valuesToAddToRange":[],"valuesToRemoveFromRange":[]},{"conditions":[{"paramId":"secondaryStream.codec","type":"value","value":"MJPEG"}],"id":"444c6f98-00ce-0ef5-05ab-11da6ae81dad","internalRange":"","range":"352x240,352x288,640x480,704x480,704x576","type":"Range","valuesToAddToRange":[],"valuesToRemoveFromRange":[]}],"description":"","group":"","id":"secondaryStream.resolution","internalRange":"","keepInitialValue":false,"name":"Resolution","notes":"","range":"","readCmd":"","readOnly":false,"resync":false,"showRange":false,"tag":"","unit":"","writeCmd":""},{"aux":"","availableInOffline":false,"bindDefaultToMinimum":false,"compact":false,"confirmation":"","dataType":"Number","dependencies":[{"conditions":[{"paramId":"secondaryStream.codec","type":"value","value":"H264"},{"paramId":"secondaryStream.resolution","type":"value","value":"352x240"}],"id":"a5c63aac-e409-be91-610e-801ed616c392","internalRange":"","range":"192,758.737","type":"Range","valuesToAddToRange":[],"valuesToRemoveFromRange":[]},{"conditions":[{"paramId":"secondaryStream.codec","type":"value","value":"H264"},{"paramId":"secondaryStream.resolution","type":"value","value":"352x288"}],"id":"d427bce5-dcbd-f1f7-db8e-f99c2eac3494","internalRange":"","range":"192,862.022","type":"Range","valuesToAddToRange":[],"valuesToRemoveFromRange":[]},{"conditions":[{"paramId":"secondaryStream.codec","type":"value","value":"H264"},{"paramId":"secondaryStream.resolution","type":"value","value":"640x480"}],"id":"c267f328-9cdb-4cfa-e1c1-10b3fbe9a5a2","internalRange":"","range":"192,1873.09","type":"Range","valuesToAddToRange":[],"valuesToRemoveFromRange":[]},{"conditions":[{"paramId":"secondaryStream.codec","type":"value","value":"H264"},{"paramId":"secondaryStream.resolution","type":"value","value":"704x480"}],"id":"ce77d286-4be5-cbf7-59c5-c3951caa34b4","internalRange":"","range":"192,2002.32","type":"Range","valuesToAddToRange":[],"valuesToRemoveFromRange":[]},{"conditions":[{"paramId":"secondaryStream.codec","type":"value","value":"H264"},{"paramId":"secondaryStream.resolution","type":"value","value":"704x576"}],"id":"2b4cc2c7-e971-3540-3fef-92c174b6263b","internalRange":"","range":"192,2274.89","type":"Range","valuesToAddToRange":[],"valuesToRemoveFromRange":[]},{"conditions":[{"paramId":"secondaryStream.codec","type":"value","value":"MJPEG"},{"paramId":"secondaryStream.resolution","type":"value","value":"352x240"}],"id":"08702485-1fc2-9b3b-26e8-7b6bccf31321","internalRange":"","range":"192,1517.47","type":"Range","valuesToAddToRange":[],"valuesToRemoveFromRange":[]},{"conditions":[{"paramId":"secondaryStream.codec","type":"value","value":"MJPEG"},{"paramId":"secondaryStream.resolution","type":"value","value":"352x288"}],"id":"57b0e016-c4dc-5700-bbdf-869f0672b2de","internalRange":"","range":"192,1724.04","type":"Range","valuesToAddToRange":[],"valuesToRemoveFromRange":[]},{"conditions":[{"paramId":"secondaryStream.codec","type":"value","value":"MJPEG"},{"paramId":"secondaryStream.resolution","type":"value","value":"640x480"}],"id":"2c496134-7781-2f2f-aab9-f31c9200351d","internalRange":"","range":"192,3746.18","type":"Range","valuesToAddToRange":[],"valuesToRemoveFromRange":[]},{"conditions":[{"paramId":"secondaryStream.codec","type":"value","value":"MJPEG"},{"paramId":"secondaryStream.resolution","type":"value","value":"704x480"}],"id":"2beb3013-9815-d03a-ccc8-3ce212f74af5","internalRange":"","range":"192,4004.64","type":"Range","valuesToAddToRange":[],"valuesToRemoveFromRange":[]},{"conditions":[{"paramId":"secondaryStream.codec","type":"value","value":"MJPEG"},{"paramId":"secondaryStream.resolution","type":"value","value":"704x576"}],"id":"3edc260d-2a05-b793-e98f-9958e9139cf7","internalRange":"","range":"192,4549.78","type":"Range","valuesToAddToRange":[],"valuesToRemoveFromRange":[]}],"description":"","group":"","id":"secondaryStream.bitrateKbps","internalRange":"","keepInitialValue":false,"name":"Bitrate","notes":"","range":"1,100000","readCmd":"","readOnly":false,"resync":false,"showRange":false,"tag":"","unit":"Kbps","writeCmd":""},{"aux":"","availableInOffline":false,"bindDefaultToMinimum":false,"compact":false,"confirmation":"","dataType":"Number","dependencies":[{"conditions":[{"paramId":"secondaryStream.codec","type":"value","value":"H264"},{"paramId":"secondaryStream.resolution","type":"value","value":"352x240"}],"id":"17b6f6ea-0bf9-2a04-0f5d-c3649825b072","internalRange":"","range":"1,30","type":"Range","valuesToAddToRange":[],"valuesToRemoveFromRange":[]},{"conditions":[{"paramId":"secondaryStream.codec","type":"value","value":"H264"},{"paramId":"secondaryStream.resolution","type":"value","value":"352x288"}],"id":"790c864b-77c0-9ddc-3c9b-21c2c2a4ae3f","internalRange":"","range":"1,30","type":"Range","valuesToAddToRange":[],"valuesToRemoveFromRange":[]},{"conditions":[{"paramId":"secondaryStream.codec","type":"value","value":"H264"},{"paramId":"secondaryStream.resolution","type":"value","value":"640x480"}],"id":"0b00cb63-56cf-72cd-c3e6-982e895ea3c9","internalRange":"","range":"1,30","type":"Range","valuesToAddToRange":[],"valuesToRemoveFromRange":[]},{"conditions":[{"paramId":"secondaryStream.codec","type":"value","value":"H264"},{"paramId":"secondaryStream.resolution","type":"value","value":"704x480"}],"id":"f6b186a6-119a-67f1-fd16-dad57cd80e99","internalRange":"","range":"1,30","type":"Range","valuesToAddToRange":[],"valuesToRemoveFromRange":[]},{"conditions":[{"paramId":"secondaryStream.codec","type":"value","value":"H264"},{"paramId":"secondaryStream.resolution","type":"value","value":"704x576"}],"id":"20e8b75a-e715-82c2-18d4-c23066ed75f3","internalRange":"","range":"1,30","type":"Range","valuesToAddToRange":[],"valuesToRemoveFromRange":[]},{"conditions":[{"paramId":"secondaryStream.codec","type":"value","value":"MJPEG"},{"paramId":"secondaryStream.resolution","type":"value","value":"352x240"}],"id":"e5285ca8-5176-77b3-e66d-b586f57225f0","internalRange":"","range":"1,30","type":"Range","valuesToAddToRange":[],"valuesToRemoveFromRange":[]},{"conditions":[{"paramId":"secondaryStream.codec","type":"value","value":"MJPEG"},{"paramId":"secondaryStream.resolution","type":"value","value":"352x288"}],"id":"e2af8198-04cc-1b08-a0ce-928e24fdbf4f","internalRange":"","range":"1,30","type":"Range","valuesToAddToRange":[],"valuesToRemoveFromRange":[]},{"conditions":[{"paramId":"secondaryStream.codec","type":"value","value":"MJPEG"},{"paramId":"secondaryStream.resolution","type":"value","value":"640x480"}],"id":"93e36af0-8b9d-f210-38f8-29c80ca3b222","internalRange":"","range":"1,30","type":"Range","valuesToAddToRange":[],"valuesToRemoveFromRange":[]},{"conditions":[{"paramId":"secondaryStream.codec","type":"value","value":"MJPEG"},{"paramId":"secondaryStream.resolution","type":"value","value":"704x480"}],"id":"01d253aa-1dab-5fd2-c6ef-67c99ae33ad0","internalRange":"","range":"1,30","type":"Range","valuesToAddToRange":[],"valuesToRemoveFromRange":[]},{"conditions":[{"paramId":"secondaryStream.codec","type":"value","value":"MJPEG"},{"paramId":"secondaryStream.resolution","type":"value","value":"704x576"}],"id":"0dd08920-32ac-af5b-67d1-bfc204eed0b9","internalRange":"","range":"1,30","type":"Range","valuesToAddToRange":[],"valuesToRemoveFromRange":[]}],"description":"","group":"","id":"secondaryStream.fps","internalRange":"","keepInitialValue":false,"name":"FPS","notes":"","range":"1,100","readCmd":"","readOnly":false,"resync":false,"showRange":false,"tag":"","unit":"Frames per Second","writeCmd":""},{"aux":"","availableInOffline":false,"bindDefaultToMinimum":false,"compact":false,"confirmation":"Are you sure you want to set defaults for this stream?","dataType":"Button","dependencies":[],"description":"","group":"","id":"secondaryStream.resetToDefaults","internalRange":"","keepInitialValue":false,"name":"Reset to Defaults","notes":"","range":"","readCmd":"","readOnly":false,"resync":true,"showRange":false,"tag":"","unit":"","writeCmd":""}]}],"name":"Video Streams Configuration","params":[]},{"aux":"","description":"","groups":[{"aux":"","description":"","groups":[],"name":"Exposure","params":[{"aux":"","availableInOffline":false,"bindDefaultToMinimum":false,"compact":false,"confirmation":"","dataType":"Enumeration","dependencies":[],"description":"Exposure Mode. Enable or disable the exposure algorithm on the device.","group":"","id":"ieMode","internalRange":"","keepInitialValue":false,"name":"Mode","notes":"","range":"Auto,Manual","readCmd":"","readOnly":false,"resync":false,"showRange":false,"tag":"","unit":"","writeCmd":""},{"aux":"","availableInOffline":false,"bindDefaultToMinimum":false,"compact":false,"confirmation":"","dataType":"Enumeration","dependencies":[],"description":"The exposure priority mode.","group":"","id":"iePriority","internalRange":"","keepInitialValue":false,"name":"Priority","notes":"","range":"LowNoise,FrameRate","readCmd":"","readOnly":false,"resync":false,"showRange":false,"tag":"","unit":"","writeCmd":""},{"aux":"","availableInOffline":false,"bindDefaultToMinimum":false,"compact":false,"confirmation":"","dataType":"Number","dependencies":[],"description":"The fixed exposure time used by the image sensor (?s).","group":"","id":"ieETime","internalRange":"","keepInitialValue":false,"name":"Exposure Time","notes":"","range":"31,66666","readCmd":"","readOnly":false,"resync":false,"showRange":false,"tag":"","unit":"","writeCmd":""}]},{"aux":"","description":"","groups":[],"name":"Wide Dynamic Range","params":[{"aux":"","availableInOffline":false,"bindDefaultToMinimum":false,"compact":false,"confirmation":"","dataType":"Enumeration","dependencies":[],"description":"Wide dynamic range mode.","group":"","id":"iwdrMode","internalRange":"","keepInitialValue":false,"name":"Mode","notes":"","range":"Off,On","readCmd":"","readOnly":false,"resync":false,"showRange":false,"tag":"","unit":"","writeCmd":""}]},{"aux":"","description":"","groups":[],"name":"White Balance","params":[{"aux":"","availableInOffline":false,"bindDefaultToMinimum":false,"compact":false,"confirmation":"","dataType":"Enumeration","dependencies":[],"description":"White Balance.","group":"","id":"iwbMode","internalRange":"","keepInitialValue":false,"name":"Mode","notes":"","range":"Auto,Manual","readCmd":"","readOnly":false,"resync":false,"showRange":false,"tag":"","unit":"","writeCmd":""},{"aux":"","availableInOffline":false,"bindDefaultToMinimum":false,"compact":false,"confirmation":"","dataType":"Number","dependencies":[],"description":"","group":"","id":"iwbYrGain","internalRange":"","keepInitialValue":false,"name":"Yr Gain","notes":"","range":"0,100","readCmd":"","readOnly":false,"resync":false,"showRange":false,"tag":"","unit":"","writeCmd":""},{"aux":"","availableInOffline":false,"bindDefaultToMinimum":false,"compact":false,"confirmation":"","dataType":"Number","dependencies":[],"description":"","group":"","id":"iwbYbGain","internalRange":"","keepInitialValue":false,"name":"Yb Gain","notes":"","range":"0,100","readCmd":"","readOnly":false,"resync":false,"showRange":false,"tag":"","unit":"","writeCmd":""}]}],"name":"Imaging","params":[{"aux":"","availableInOffline":false,"bindDefaultToMinimum":false,"compact":false,"confirmation":"","dataType":"Number","dependencies":[],"description":"Image brightness.","group":"","id":"iBri","internalRange":"","keepInitialValue":false,"name":"Brightness","notes":"","range":"0,100","readCmd":"","readOnly":false,"resync":false,"showRange":false,"tag":"","unit":"","writeCmd":""},{"aux":"","availableInOffline":false,"bindDefaultToMinimum":false,"compact":false,"confirmation":"","dataType":"Number","dependencies":[],"description":"Color saturation of the image.","group":"","id":"iCS","internalRange":"","keepInitialValue":false,"name":"Color Saturation","notes":"","range":"0,100","readCmd":"","readOnly":false,"resync":false,"showRange":false,"tag":"","unit":"","writeCmd":""},{"aux":"","availableInOffline":false,"bindDefaultToMinimum":false,"compact":false,"confirmation":"","dataType":"Number","dependencies":[],"description":"Contrast of the image.","group":"","id":"iCon","internalRange":"","keepInitialValue":false,"name":"Contrast","notes":"","range":"0,100","readCmd":"","readOnly":false,"resync":false,"showRange":false,"tag":"","unit":"","writeCmd":""},{"aux":"","availableInOffline":false,"bindDefaultToMinimum":false,"compact":false,"confirmation":"","dataType":"Enumeration","dependencies":[],"description":"Infrared Cutoff Filter settings.","group":"","id":"iIrCut","internalRange":"","keepInitialValue":false,"name":"Ir Cut Filter Mode","notes":"","range":"On, Off, Auto","readCmd":"","readOnly":false,"resync":false,"showRange":false,"tag":"","unit":"","writeCmd":""},{"aux":"","availableInOffline":false,"bindDefaultToMinimum":false,"compact":false,"confirmation":"","dataType":"Number","dependencies":[],"description":"Sharpness of the Video image.","group":"","id":"iSha","internalRange":"","keepInitialValue":false,"name":"Sharpness","notes":"","range":"0,100","readCmd":"","readOnly":false,"resync":false,"showRange":false,"tag":"","unit":"","writeCmd":""}]},{"aux":"","description":"","groups":[],"name":"Maintenance","params":[{"aux":"","availableInOffline":true,"bindDefaultToMinimum":false,"compact":false,"confirmation":"Are you sure you want to reboot the device?","dataType":"Button","dependencies":[],"description":"This operation reboots the device.","group":"","id":"mReboot","internalRange":"","keepInitialValue":false,"name":"System Reboot","notes":"","range":"","readCmd":"","readOnly":false,"resync":false,"showRange":false,"tag":"","unit":"","writeCmd":""},{"aux":"","availableInOffline":true,"bindDefaultToMinimum":false,"compact":false,"confirmation":"Are you sure you want to reset all settings (except network) to default?","dataType":"Button","dependencies":[],"description":"This operation reloads all parameters on the device to their factory default values, except basic network settings like IP address, subnet and gateway or DHCP settings.","group":"","id":"mSoftReset","internalRange":"","keepInitialValue":false,"name":"Soft Factory Reset","notes":"","range":"","readCmd":"","readOnly":false,"resync":false,"showRange":false,"tag":"","unit":"","writeCmd":""},{"aux":"","availableInOffline":true,"bindDefaultToMinimum":false,"compact":false,"confirmation":"Are you sure you want to reset all settings (including network) to default?","dataType":"Button","dependencies":[],"description":"This operation reloads all parameters on the device to their factory default values.","group":"","id":"mHardReset","internalRange":"","keepInitialValue":false,"name":"Hard Factory Reset","notes":"","range":"","readCmd":"","readOnly":false,"resync":false,"showRange":false,"tag":"","unit":"","writeCmd":""}]}],"name":"primaryStreamConfiguration, secondaryStreamConfiguration, ONVIF","packet_mode":false,"unique_id":"971009D8-384D-43C1-85BF-44A2B99253D5, 971009D8-384D-43C1-85BF-44A2B99253D5, 53148996-d4d8-4e90-985e-24c6c63c5150","version":"1.0, 1.0, 1"}',
                },
                {
                    name: 'cameraCapabilities',
                    value: '196608',
                },
                {
                    name: 'compatibleAnalyticsEngines',
                    value: '[]',
                },
                {
                    name: 'defaultCredentials',
                    value: 'admin:******',
                },
                {
                    name: 'driverClass',
                    value: 'QnPlOnvifResource',
                },
                {
                    name: 'firmware',
                    value: 'A1.0.5',
                },
                {
                    name: 'hasDualStreaming',
                    value: '1',
                },
                {
                    name: 'ioSettings',
                    value: '[]',
                },
                {
                    name: 'isAudioSupported',
                    value: '0',
                },
                {
                    name: 'mediaCapabilities',
                    value: '{"hasAudio":false,"hasDualStreaming":false,"streamCapabilities":[{"key":"primary","value":{"defaultBitrateKbps":0,"defaultFps":30,"maxBitrateKbps":7129.6982421875,"maxFps":30,"minBitrateKbps":192}},{"key":"secondary","value":{"defaultBitrateKbps":0,"defaultFps":30,"maxBitrateKbps":1873.0894775390625,"maxFps":30,"minBitrateKbps":192}}]}',
                },
                {
                    name: 'mediaStreams',
                    value: '{"streams":[{"codec":28,"customStreamParams":{},"encoderIndex":1,"resolution":"640x480","transcodingRequired":false,"transports":["rtsp","hls"]},{"codec":28,"customStreamParams":{},"encoderIndex":0,"resolution":"1920x1080","transcodingRequired":false,"transports":["rtsp","hls"]},{"codec":0,"customStreamParams":{},"encoderIndex":-1,"resolution":"*","transcodingRequired":true,"transports":["rtsp","mjpeg","webm"]}]}',
                },
            ],
            motionEnabled: true,
            recordingSettings: {
                recording: false,
                quality: 'high',
                fps: 30,
                motionEnabled: true,
                modes: [
                    {
                        name: 'always',
                        id: 'RT_Always',
                        value: 0,
                        enabled: true,
                    },
                    {
                        name: 'motion',
                        id: 'RT_MetadataOnly',
                        value: 0,
                        enabled: true,
                    },
                    {
                        name: 'motionLowRes',
                        id: 'RT_MetadataAndLowQuality',
                        value: 0,
                        enabled: true,
                    },
                ],
            },
            parsedAddParams: {},
            isAudioSupported: true,
            secondsToday: 74956,
            parentName: 'Server dev',
            previewUrl:
                'https://c27aaff0-0694-469b-a8d6-c43cd8a9648c.relay.vmsproxy.hdw.mx/ec2/cameraThumbnail?ignoreExternalArchive&cameraId=b9544f11-e84a-9c1d-c58d-320d6898f9bd&time=LATEST&height=120&rotate=0&auth=MTVkNDdlZjc0YTk0NDJkMzgzODE1MDA2ZGM1YzBlN2UtMzQyNTcyODY4NzpuaXdYNUlkcEJuaUFsNXNGelRYYTFoZmdvbHJVVTg9aHp4cHBjOjRlNWUxMGFiZmZiNmYwMjRhNzkzODk3OTQ4ODk5OTJm',
            mediaCapabilities:
                '{"hasAudio":false,"hasDualStreaming":false,"streamCapabilities":[{"key":"primary","value":{"defaultBitrateKbps":0,"defaultFps":30,"maxBitrateKbps":7129.6982421875,"maxFps":30,"minBitrateKbps":192}},{"key":"secondary","value":{"defaultBitrateKbps":0,"defaultFps":30,"maxBitrateKbps":1873.0894775390625,"maxFps":30,"minBitrateKbps":192}}]}',
            vendor: 'N5Fx-ALAH2',
            isStream: false,
        },
        {
            audioEnabled: false,
            backupType: 'CameraBackupDisabled',
            controlEnabled: false,
            dewarpingParams: '',
            disableDualStreaming: false,
            failoverPriority: 'Never',
            groupId: '',
            groupName: '',
            licenseUsed: false,
            logicalId: '',
            mac: '00-50-1A-2D-2F-6F',
            manuallyAdded: false,
            maxArchiveDays: -30,
            minArchiveDays: -1,
            model: 'IQ032S',
            motionMask: '',
            motionType: '0',
            name: 'IQ032S',
            physicalId: '00-50-1A-2D-2F-6F',
            preferredServerId: '{00000000-0000-0000-0000-000000000000}',
            recordAfterMotionSec: 0,
            recordBeforeMotionSec: 0,
            scheduleEnabled: false,
            scheduleTasks: [],
            status: 'Online',
            statusFlags: 'CSF_NoFlags',
            typeId: '{2a21aeb6-48c1-0313-30c2-8ee6dceda70d}',
            url: '10.1.5.208',
            userDefinedGroupName: '',
            id: '{785d421b-62a6-47fc-7fe8-9df96682284c}',
            parentId: '{2d624ba5-a762-f38a-60ba-14240c70276f}',
            dayOfWeek: 4,
            maxFps: 15,
            addParamsRaw: [
                {
                    name: 'cameraCapabilities',
                    value: '65536',
                },
                {
                    name: 'compatibleAnalyticsEngines',
                    value: '[]',
                },
                {
                    name: 'defaultCredentials',
                    value: 'root:******',
                },
                {
                    name: 'driverClass',
                    value: 'QnPlIqResource',
                },
                {
                    name: 'mediaStreams',
                    value: '{"streams":[{"codec":8,"customStreamParams":{},"encoderIndex":0,"resolution":"1920x1080","transcodingRequired":false,"transports":["mjpeg"]},{"codec":0,"customStreamParams":{},"encoderIndex":-1,"resolution":"*","transcodingRequired":true,"transports":["rtsp","mjpeg","webm"]}]}',
                },
            ],
            motionEnabled: true,
            recordingSettings: {
                recording: false,
                quality: 'high',
                fps: 15,
                motionEnabled: true,
                modes: [
                    {
                        name: 'always',
                        id: 'RT_Always',
                        value: 0,
                        enabled: true,
                    },
                    {
                        name: 'motion',
                        id: 'RT_MetadataOnly',
                        value: 0,
                        enabled: true,
                    },
                    {
                        name: 'motionLowRes',
                        id: 'RT_MetadataAndLowQuality',
                        value: 0,
                        enabled: true,
                    },
                ],
            },
            parsedAddParams: {},
            isAudioSupported: false,
            secondsToday: 74956,
            parentName: 'Server dev',
            previewUrl:
                'https://c27aaff0-0694-469b-a8d6-c43cd8a9648c.relay.vmsproxy.hdw.mx/ec2/cameraThumbnail?ignoreExternalArchive&cameraId=785d421b-62a6-47fc-7fe8-9df96682284c&time=LATEST&height=120&rotate=0&auth=MTVkNDdlZjc0YTk0NDJkMzgzODE1MDA2ZGM1YzBlN2UtMzQyNTcyODY4NzpuaXdYNUlkcEJuaUFsNXNGelRYYTFoZmdvbHJVVTg9aHp4cHBjOjRlNWUxMGFiZmZiNmYwMjRhNzkzODk3OTQ4ODk5OTJm',
            vendor: 'IqEye',
            isStream: false,
        },
        {
            audioEnabled: false,
            backupType: 'CameraBackupDisabled',
            controlEnabled: false,
            dewarpingParams: '',
            disableDualStreaming: false,
            failoverPriority: 'Never',
            groupId: '',
            groupName: '',
            licenseUsed: false,
            logicalId: '',
            mac: '64-76-57-80-0C-44',
            manuallyAdded: false,
            maxArchiveDays: -30,
            minArchiveDays: -1,
            model: 'ISDcam',
            motionMask: '',
            motionType: '0',
            name: 'ISDcam',
            physicalId: '64-76-57-80-0C-44',
            preferredServerId: '{00000000-0000-0000-0000-000000000000}',
            recordAfterMotionSec: 0,
            recordBeforeMotionSec: 0,
            scheduleEnabled: false,
            scheduleTasks: [],
            status: 'Unauthorized',
            statusFlags: 'CSF_NoFlags',
            typeId: '{7d2af20d-04f2-149f-ef37-ad585281e3b7}',
            url: 'http://10.1.5.100:80',
            userDefinedGroupName: '',
            id: '{1de10ba8-3ed7-5ee1-f3d6-8e0d1b9d0036}',
            parentId: '{2d624ba5-a762-f38a-60ba-14240c70276f}',
            dayOfWeek: 4,
            maxFps: 15,
            addParamsRaw: [
                {
                    name: 'cameraCapabilities',
                    value: '65536',
                },
                {
                    name: 'compatibleAnalyticsEngines',
                    value: '[]',
                },
                {
                    name: 'defaultCredentials',
                    value: 'root:******',
                },
                {
                    name: 'driverClass',
                    value: 'QnPlIsdResource',
                },
            ],
            motionEnabled: true,
            recordingSettings: {
                recording: false,
                quality: 'high',
                fps: 15,
                motionEnabled: true,
                modes: [
                    {
                        name: 'always',
                        id: 'RT_Always',
                        value: 0,
                        enabled: true,
                    },
                    {
                        name: 'motion',
                        id: 'RT_MetadataOnly',
                        value: 0,
                        enabled: true,
                    },
                    {
                        name: 'motionLowRes',
                        id: 'RT_MetadataAndLowQuality',
                        value: 0,
                        enabled: true,
                    },
                ],
            },
            parsedAddParams: {},
            isAudioSupported: false,
            secondsToday: 74956,
            parentName: 'Server dev',
            previewUrl:
                'https://c27aaff0-0694-469b-a8d6-c43cd8a9648c.relay.vmsproxy.hdw.mx/ec2/cameraThumbnail?ignoreExternalArchive&cameraId=1de10ba8-3ed7-5ee1-f3d6-8e0d1b9d0036&time=LATEST&height=120&rotate=0&auth=MTVkNDdlZjc0YTk0NDJkMzgzODE1MDA2ZGM1YzBlN2UtMzQyNTcyODY4NzpuaXdYNUlkcEJuaUFsNXNGelRYYTFoZmdvbHJVVTg9aHp4cHBjOjRlNWUxMGFiZmZiNmYwMjRhNzkzODk3OTQ4ODk5OTJm',
            vendor: 'ISD',
            isStream: false,
        },
        {
            audioEnabled: false,
            backupType: 'CameraBackupDisabled',
            controlEnabled: false,
            dewarpingParams: '',
            disableDualStreaming: false,
            failoverPriority: 'Never',
            groupId: '',
            groupName: '',
            licenseUsed: false,
            logicalId: '',
            mac: '00-09-18-66-01-7F',
            manuallyAdded: false,
            maxArchiveDays: -30,
            minArchiveDays: -1,
            model: 'PNM-9002VQ',
            motionMask: '',
            motionType: '0',
            name: 'PNM-9002VQ',
            physicalId: '00-09-18-66-01-7F',
            preferredServerId: '{00000000-0000-0000-0000-000000000000}',
            recordAfterMotionSec: 0,
            recordBeforeMotionSec: 0,
            scheduleEnabled: false,
            scheduleTasks: [],
            status: 'Unauthorized',
            statusFlags: 'CSF_NoFlags',
            typeId: '{6ae785e6-b7d2-832a-a6a0-6072f796d6af}',
            url: 'http://10.1.5.168:80',
            userDefinedGroupName: '',
            id: '{2375d7f9-4372-adc2-07a4-ade8ff55052e}',
            parentId: '{2d624ba5-a762-f38a-60ba-14240c70276f}',
            dayOfWeek: 4,
            maxFps: 15,
            addParamsRaw: [
                {
                    name: 'cameraCapabilities',
                    value: '66048',
                },
                {
                    name: 'compatibleAnalyticsEngines',
                    value: '["{d018384f-8f08-6a40-70a8-1405ba18b455}"]',
                },
                {
                    name: 'defaultCredentials',
                    value: 'admin:******',
                },
                {
                    name: 'driverClass',
                    value: 'nx::vms::server::plugins::HanwhaResource',
                },
            ],
            motionEnabled: true,
            recordingSettings: {
                recording: false,
                quality: 'high',
                fps: 15,
                motionEnabled: true,
                modes: [
                    {
                        name: 'always',
                        id: 'RT_Always',
                        value: 0,
                        enabled: true,
                    },
                    {
                        name: 'motion',
                        id: 'RT_MetadataOnly',
                        value: 0,
                        enabled: true,
                    },
                    {
                        name: 'motionLowRes',
                        id: 'RT_MetadataAndLowQuality',
                        value: 0,
                        enabled: true,
                    },
                ],
            },
            parsedAddParams: {},
            isAudioSupported: false,
            secondsToday: 74956,
            parentName: 'Server dev',
            previewUrl:
                'https://c27aaff0-0694-469b-a8d6-c43cd8a9648c.relay.vmsproxy.hdw.mx/ec2/cameraThumbnail?ignoreExternalArchive&cameraId=2375d7f9-4372-adc2-07a4-ade8ff55052e&time=LATEST&height=120&rotate=0&auth=MTVkNDdlZjc0YTk0NDJkMzgzODE1MDA2ZGM1YzBlN2UtMzQyNTcyODY4NzpuaXdYNUlkcEJuaUFsNXNGelRYYTFoZmdvbHJVVTg9aHp4cHBjOjRlNWUxMGFiZmZiNmYwMjRhNzkzODk3OTQ4ODk5OTJm',
            vendor: 'Hanwha Techwin',
            isStream: false,
        },
        {
            audioEnabled: false,
            backupType: 'CameraBackupDisabled',
            controlEnabled: false,
            dewarpingParams: '',
            disableDualStreaming: false,
            failoverPriority: 'Never',
            groupId: '',
            groupName: '',
            licenseUsed: false,
            logicalId: '',
            mac: '00-09-18-52-1A-FC',
            manuallyAdded: false,
            maxArchiveDays: -30,
            minArchiveDays: -1,
            model: 'PNM-9080VQ',
            motionMask: '',
            motionType: '0',
            name: 'PNM-9080VQ',
            physicalId: '00-09-18-52-1A-FC',
            preferredServerId: '{00000000-0000-0000-0000-000000000000}',
            recordAfterMotionSec: 0,
            recordBeforeMotionSec: 0,
            scheduleEnabled: false,
            scheduleTasks: [],
            status: 'Unauthorized',
            statusFlags: 'CSF_NoFlags',
            typeId: '{6ae785e6-b7d2-832a-a6a0-6072f796d6af}',
            url: 'http://10.1.5.178:80',
            userDefinedGroupName: '',
            id: '{162ff0a3-32fd-e049-f037-2ee378df5a8b}',
            parentId: '{2d624ba5-a762-f38a-60ba-14240c70276f}',
            dayOfWeek: 4,
            maxFps: 15,
            addParamsRaw: [
                {
                    name: 'cameraCapabilities',
                    value: '66048',
                },
                {
                    name: 'compatibleAnalyticsEngines',
                    value: '["{d018384f-8f08-6a40-70a8-1405ba18b455}"]',
                },
                {
                    name: 'defaultCredentials',
                    value: 'admin:******',
                },
                {
                    name: 'driverClass',
                    value: 'nx::vms::server::plugins::HanwhaResource',
                },
            ],
            motionEnabled: true,
            recordingSettings: {
                recording: false,
                quality: 'high',
                fps: 15,
                motionEnabled: true,
                modes: [
                    {
                        name: 'always',
                        id: 'RT_Always',
                        value: 0,
                        enabled: true,
                    },
                    {
                        name: 'motion',
                        id: 'RT_MetadataOnly',
                        value: 0,
                        enabled: true,
                    },
                    {
                        name: 'motionLowRes',
                        id: 'RT_MetadataAndLowQuality',
                        value: 0,
                        enabled: true,
                    },
                ],
            },
            parsedAddParams: {},
            isAudioSupported: false,
            secondsToday: 74956,
            parentName: 'Server dev',
            previewUrl:
                'https://c27aaff0-0694-469b-a8d6-c43cd8a9648c.relay.vmsproxy.hdw.mx/ec2/cameraThumbnail?ignoreExternalArchive&cameraId=162ff0a3-32fd-e049-f037-2ee378df5a8b&time=LATEST&height=120&rotate=0&auth=MTVkNDdlZjc0YTk0NDJkMzgzODE1MDA2ZGM1YzBlN2UtMzQyNTcyODY4NzpuaXdYNUlkcEJuaUFsNXNGelRYYTFoZmdvbHJVVTg9aHp4cHBjOjRlNWUxMGFiZmZiNmYwMjRhNzkzODk3OTQ4ODk5OTJm',
            vendor: 'Hanwha Techwin',
            isStream: false,
        },
        {
            audioEnabled: false,
            backupType: 'CameraBackupDisabled',
            controlEnabled: false,
            dewarpingParams: '',
            disableDualStreaming: false,
            failoverPriority: 'Never',
            groupId: '',
            groupName: '',
            licenseUsed: false,
            logicalId: '',
            mac: 'E4-30-22-01-1B-B3',
            manuallyAdded: false,
            maxArchiveDays: -30,
            minArchiveDays: -1,
            model: 'XND-L6080R',
            motionMask: '',
            motionType: '0',
            name: 'XND-L6080RV',
            physicalId: 'E4-30-22-01-1B-B3',
            preferredServerId: '{00000000-0000-0000-0000-000000000000}',
            recordAfterMotionSec: 0,
            recordBeforeMotionSec: 0,
            scheduleEnabled: false,
            scheduleTasks: [],
            status: 'Unauthorized',
            statusFlags: 'CSF_NoFlags',
            typeId: '{6ae785e6-b7d2-832a-a6a0-6072f796d6af}',
            url: 'http://10.1.5.112:80',
            userDefinedGroupName: '',
            id: '{92076a14-15c1-3ad9-b089-dc7a9ffb6ecd}',
            parentId: '{2d624ba5-a762-f38a-60ba-14240c70276f}',
            dayOfWeek: 4,
            maxFps: 15,
            addParamsRaw: [
                {
                    name: 'cameraCapabilities',
                    value: '66048',
                },
                {
                    name: 'compatibleAnalyticsEngines',
                    value: '["{d018384f-8f08-6a40-70a8-1405ba18b455}"]',
                },
                {
                    name: 'defaultCredentials',
                    value: 'admin:******',
                },
                {
                    name: 'driverClass',
                    value: 'nx::vms::server::plugins::HanwhaResource',
                },
            ],
            motionEnabled: true,
            recordingSettings: {
                recording: false,
                quality: 'high',
                fps: 15,
                motionEnabled: true,
                modes: [
                    {
                        name: 'always',
                        id: 'RT_Always',
                        value: 0,
                        enabled: true,
                    },
                    {
                        name: 'motion',
                        id: 'RT_MetadataOnly',
                        value: 0,
                        enabled: true,
                    },
                    {
                        name: 'motionLowRes',
                        id: 'RT_MetadataAndLowQuality',
                        value: 0,
                        enabled: true,
                    },
                ],
            },
            parsedAddParams: {},
            isAudioSupported: false,
            secondsToday: 74956,
            parentName: 'Server dev',
            previewUrl:
                'https://c27aaff0-0694-469b-a8d6-c43cd8a9648c.relay.vmsproxy.hdw.mx/ec2/cameraThumbnail?ignoreExternalArchive&cameraId=92076a14-15c1-3ad9-b089-dc7a9ffb6ecd&time=LATEST&height=120&rotate=0&auth=MTVkNDdlZjc0YTk0NDJkMzgzODE1MDA2ZGM1YzBlN2UtMzQyNTcyODY4NzpuaXdYNUlkcEJuaUFsNXNGelRYYTFoZmdvbHJVVTg9aHp4cHBjOjRlNWUxMGFiZmZiNmYwMjRhNzkzODk3OTQ4ODk5OTJm',
            vendor: 'Hanwha Techwin',
            isStream: false,
        },
        {
            audioEnabled: false,
            backupType: 'CameraBackupDisabled',
            controlEnabled: false,
            dewarpingParams: '',
            disableDualStreaming: false,
            failoverPriority: 'Never',
            groupId: '',
            groupName: '',
            licenseUsed: false,
            logicalId: '',
            mac: '00-09-18-64-EE-7D',
            manuallyAdded: false,
            maxArchiveDays: -30,
            minArchiveDays: -1,
            model: 'XNV-9082R',
            motionMask: '',
            motionType: '0',
            name: 'XNV-9082R',
            physicalId: '00-09-18-64-EE-7D',
            preferredServerId: '{00000000-0000-0000-0000-000000000000}',
            recordAfterMotionSec: 0,
            recordBeforeMotionSec: 0,
            scheduleEnabled: false,
            scheduleTasks: [],
            status: 'Unauthorized',
            statusFlags: 'CSF_NoFlags',
            typeId: '{6ae785e6-b7d2-832a-a6a0-6072f796d6af}',
            url: 'https://10.1.5.162:443',
            userDefinedGroupName: '',
            id: '{b2bcc440-6ab2-0844-3213-505994c94b52}',
            parentId: '{2d624ba5-a762-f38a-60ba-14240c70276f}',
            dayOfWeek: 4,
            maxFps: 15,
            addParamsRaw: [
                {
                    name: 'cameraCapabilities',
                    value: '66048',
                },
                {
                    name: 'compatibleAnalyticsEngines',
                    value: '["{d018384f-8f08-6a40-70a8-1405ba18b455}"]',
                },
                {
                    name: 'defaultCredentials',
                    value: 'admin:******',
                },
                {
                    name: 'driverClass',
                    value: 'nx::vms::server::plugins::HanwhaResource',
                },
            ],
            motionEnabled: true,
            recordingSettings: {
                recording: false,
                quality: 'high',
                fps: 15,
                motionEnabled: true,
                modes: [
                    {
                        name: 'always',
                        id: 'RT_Always',
                        value: 0,
                        enabled: true,
                    },
                    {
                        name: 'motion',
                        id: 'RT_MetadataOnly',
                        value: 0,
                        enabled: true,
                    },
                    {
                        name: 'motionLowRes',
                        id: 'RT_MetadataAndLowQuality',
                        value: 0,
                        enabled: true,
                    },
                ],
            },
            parsedAddParams: {},
            isAudioSupported: false,
            secondsToday: 74956,
            parentName: 'Server dev',
            previewUrl:
                'https://c27aaff0-0694-469b-a8d6-c43cd8a9648c.relay.vmsproxy.hdw.mx/ec2/cameraThumbnail?ignoreExternalArchive&cameraId=b2bcc440-6ab2-0844-3213-505994c94b52&time=LATEST&height=120&rotate=0&auth=MTVkNDdlZjc0YTk0NDJkMzgzODE1MDA2ZGM1YzBlN2UtMzQyNTcyODY4NzpuaXdYNUlkcEJuaUFsNXNGelRYYTFoZmdvbHJVVTg9aHp4cHBjOjRlNWUxMGFiZmZiNmYwMjRhNzkzODk3OTQ4ODk5OTJm',
            vendor: 'Hanwha Techwin',
            isStream: false,
        },
    ];
}
