import { Auth, MenuNode } from '@services/menus.service.types';

export const headerNodes: Partial<MenuNode[]> = [
    {
        subtitle: '',
        url: '',
        asset_id: null,
        accepted: true,
        pending: false,
        draft: null,
        asset_type: null,
        related_asset_ids: [],
        next_item: false,
        new_window: false,
        icon: 'services.svg',
        authentication: Auth.BOTH,
        order: 1,
        name: 'Services',
        name_raw: 'Services',
        display_name: 'Services',
        invisible: false,
        nodes: [
            {
                subtitle: '',
                url: '/download',
                asset_id: null,
                accepted: true,
                pending: false,
                draft: null,
                asset_type: null,
                related_asset_ids: [],
                next_item: false,
                new_window: false,
                icon: '',
                authentication: Auth.BOTH,
                order: 0,
                name: 'Downloads',
                name_raw: 'Downloads',
                display_name: 'Downloads',
                nodes: [],
                breadcrumbs: [],
                queryParamsHandling: '',
                urlified: '',
                invisible: false
            },
            {
                subtitle: '',
                url: '/ipvd',
                asset_id: null,
                accepted: true,
                pending: false,
                draft: null,
                asset_type: null,
                related_asset_ids: [],
                next_item: false,
                new_window: false,
                icon: '',
                authentication: Auth.BOTH,
                order: 1,
                name: 'Supported Devices',
                name_raw: 'Supported Devices',
                display_name: 'Supported Devices',
                nodes: [],
                breadcrumbs: [],
                queryParamsHandling: '',
                urlified: '',
                invisible: false
            },
            {
                subtitle: '',
                url: '/health-report/viewer',
                asset_id: null,
                accepted: true,
                pending: false,
                draft: null,
                asset_type: null,
                related_asset_ids: [],
                next_item: false,
                new_window: false,
                icon: '',
                authentication: Auth.BOTH,
                order: 2,
                name: 'Health Report Viewer',
                name_raw: 'Health Report Viewer',
                display_name: 'Health Report Viewer',
                nodes: [],
                breadcrumbs: [],
                queryParamsHandling: '',
                urlified: '',
                invisible: false
            }
        ],
        breadcrumbs: [],
        queryParamsHandling: '',
        urlified: ''
    }
];
