import re
import logging

from django.core.exceptions import PermissionDenied, ValidationError
from django.urls import reverse
from django.conf import settings
from django.utils import timezone
from django.contrib import messages
from django.shortcuts import redirect

from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes, throttle_classes
from rest_framework.permissions import AllowAny, IsAuthenticated

from drf_yasg import openapi
from drf_yasg.utils import swagger_auto_schema

from cloud.helpers.exceptions import handle_exceptions, APIRequestException, APIServiceException, \
    api_success, ErrorCodes, get_client_ip, APITooManyRequestsException
from api.models import Account
from cms.models import Customization, Asset, UserGroupsToAssetPermissions, cloud_portal_customization_cache
from cms.permissions import IsSuperuser
from notifications import notifications_api
from notifications.models import *
from notifications.tasks import send_to_all_users
from util.throttling import NotificationRateThrottle

logger = logging.getLogger(__name__)

MESSAGE_TYPES = MessageTypes()


# Swagger Schemas for body
asset__body = openapi.Schema(description=f"The asset that the message is about. This is required for "
                                         f"{MESSAGE_TYPES.ipvd_feedback_page} and {MESSAGE_TYPES.ipvd_feedback_device}",
                             type=openapi.TYPE_NUMBER)
type__body = openapi.Schema(description="Determines the subject of the message. Options listed as possible subjects",
                            type=openapi.TYPE_STRING)
message__body = openapi.Schema(type=openapi.TYPE_STRING)
user_email__body = openapi.Schema(
    type=openapi.TYPE_STRING, description="The sender's email.")
user_name__body = openapi.Schema(
    type=openapi.TYPE_STRING, description="The sender's name.")


customization__body = openapi.Schema(type=openapi.TYPE_STRING,
                                     description="Customizes the branding of a message to match a customization.")
external_id__query_param = openapi.Parameter('external_id', openapi.IN_QUERY, type=openapi.TYPE_STRING,
                                             description="An id for the message generated by an external "
                                                         "service generated. If there is a match no "
                                                         "notification is sent")
notification_type__body = openapi.Schema(
    type=openapi.TYPE_STRING, description="Determines the subject of the message.")
notification_user_email__body = openapi.Schema(
    type=openapi.TYPE_STRING, description="Who the email will be sent to.")
notification_user_name__body = openapi.Schema(type=openapi.TYPE_STRING,
                                              description="The full name of who the email will be sent to.")


customizations__body = openapi.Schema(type=openapi.TYPE_ARRAY, items=openapi.TYPE_STRING,
                                      description="Customizations that should receive the cloud notification. "
                                                  "If this field is blank the current cloud portal's customization "
                                                  "is used.")
preview__body = openapi.Schema(type=openapi.TYPE_STRING,
                               description="If flag is present a preview of the notification will be sent to you.")
save__body = openapi.Schema(type=openapi.TYPE_STRING,
                            description="If this flag is present the notification will be saved.")
send__body = openapi.Schema(type=openapi.TYPE_STRING,
                            description="If this flag is present the notification will be sent to the "
                                        "target customizations")


# Replaces </p> and <br> with \n and then remove all html tags
def html_to_text(html):
    new_line = re.compile(r'<(\/p|br)>')
    tags = re.compile(r'<[\w\=\'\"\:\;\_\-\,\!\/\ ]+>')
    return tags.sub('', new_line.sub('\n', html))


def add_brs(html):
    br = re.compile(r'\n')
    return br.sub('<br>', html)


def format_message(notification):
    message = dict()
    message['subject'] = notification.subject
    message['html_body'] = add_brs(notification.body)
    message['text_body'] = html_to_text(notification.body)
    return message


def update_or_create_notification(data, customizations=None):
    if not data['id']:
        notification = CloudNotification(
            subject=data['subject'], body=data['body'])
    else:
        notification = CloudNotification.objects.get(id=data['id'])
        notification.subject = data['subject']
        notification.body = data['body']
        notification.save()
        if customizations:
            notification.customizations.set(
                Customization.objects.filter(name__in=customizations))
    notification.save()
    return notification.id


@swagger_auto_schema(method="POST",  auto_schema=None,
                     operation_description=f"Sends a message that is about ipvd or integrations."
                                           f"The possible subjects are {','.join(MESSAGE_TYPES.keys())}",
                     request_body=openapi.Schema(
                         type=openapi.TYPE_OBJECT,
                         properties={
                             "asset": asset__body,
                             "message": message__body,
                             "type": type__body,
                             "userEmail": user_email__body,
                             "userName": user_name__body
                         },
                         required=["message", "type", "userEmail", "userName"]
                     ))
@api_view(['POST'])
@permission_classes((AllowAny, ))
def send_event(request):
    feedback_enabled = cloud_portal_customization_cache(
        request.CUSTOMIZATION, 'config').get('feedback_enabled', False)
    if not feedback_enabled:
        raise APIServiceException(
            'Feedback is currently unavailable', ErrorCodes.service_unavailable)

    try:
        validation_error = False
        error_data = {}

        if 'type' not in request.data or not request.data['type']:
            validation_error = True
            error_data['type'] = ['This field is required.']

        if 'type' in request.data\
            and request.data['type'] not in [MESSAGE_TYPES.ipvd_feedback_page,
                                             MESSAGE_TYPES.ipvd_feedback_device]\
                and 'asset' not in request.data:
            validation_error = True
            error_data['asset'] = ['This field is required.']

        if 'message' not in request.data:
            validation_error = True
            error_data['message'] = ['This field is required.']

        if 'userEmail' not in request.data:
            validation_error = True
            error_data['userEmail'] = ['This field is required.']

        if 'userName' not in request.data:
            validation_error = True
            error_data['userName'] = ['This field is required.']

        if validation_error:
            raise APIRequestException('Not enough parameters in request', ErrorCodes.wrong_parameters,
                                      error_data=error_data)

        asset_id = ''
        if request.data['type'] not in [MESSAGE_TYPES.ipvd_feedback_page,
                                        MESSAGE_TYPES.ipvd_feedback_device]:
            asset = Asset.objects.filter(id=request.data['asset']).first()
            if asset:
                request.data['asset'] = asset.name
                asset_id = asset.id
        else:
            request.data['type'] = MESSAGE_TYPES.ipvd_feedback

        request.data['sender_email'] = request.data['userEmail']
        request.data['sender_name'] = request.data['userName']

        ip = get_client_ip(request)
        logging.info(
            f"ip: {ip}\t user: {request.user}\nrequest data: {request.data}")

        notifications_api.send_feedback(
            request.data['type'], asset_id, request.data, request=request)

    except ValidationError as error:
        error_data = error.detail if hasattr(error, 'detail') else None
        raise APIRequestException(
            error.message, ErrorCodes.wrong_parameters, error_data=error_data)
    return api_success()


@swagger_auto_schema(method="POST",  auto_schema=None,
                     operation_description="Sends an email to the target user. Mainly used by clouddb.",
                     manual_parameters=[external_id__query_param],
                     request_body=openapi.Schema(
                         type=openapi.TYPE_OBJECT,
                         properties={
                             "customization": customization__body,
                             "message": message__body,
                             "type": notification_type__body,
                             "user_email": notification_user_email__body,
                             "userFullName": notification_user_name__body
                         },
                         required=["customization",
                                   "message", "type", "user_email"]
                     ))
@api_view(['POST'])
@permission_classes((AllowAny, ))
def send_notification(request):
    try:
        validation_error = False
        error_data = {}

        external_id = request.data.get('id')
        if external_id:  # external service generated an id for this message to track it
            msg = notifications_api.find_message(external_id)
            if msg:
                # there is already a message with this id - do not send the message, respond with status
                serializer = MessageStatusSerializer(msg, many=False)
                return api_success(serializer.data)

        if 'user_email' not in request.data or not request.data['user_email']:
            validation_error = True
            error_data['user_email'] = ['This field is required.']

        if 'type' not in request.data or not request.data['type']:
            validation_error = True
            error_data['type'] = ['This field is required.']
        if 'message' not in request.data:
            validation_error = True
            error_data['message'] = ['This field is required.']

        if 'customization' not in request.data or not request.data['customization']:
            validation_error = True
            error_data['customization'] = ['This field is required.']

        if validation_error:
            raise APIRequestException('Not enough parameters in request', ErrorCodes.wrong_parameters,
                                      error_data=error_data)
        if not NotificationRateThrottle().allow_request(request=request, view=None):
            logger.warning(
                f'Request throttled for {request.data["user_email"]}::{request.data["type"]}'
                f' in customization {request.data["customization"]}'
            )
            raise APITooManyRequestsException('Too many request. Please try again later')
        # Clouddb doesn't always return a full name so try to get it from cloud portal
        if 'userFullName' not in request.data['message'] or not request.data['message']['userFullName']:
            user_account = Account.objects.filter(
                email=request.data['user_email']).first()
            if user_account:
                request.data['message']['userFullName'] = user_account.get_full_name()

        notifications_api.send(request.data['user_email'],
                               request.data['type'],
                               request.data['message'],
                               customization=request.data['customization'],
                               external_id=external_id)
    except ValidationError as error:
        error_data = error.detail if hasattr(error, 'detail') else None
        raise APIRequestException(
            error.message, ErrorCodes.wrong_parameters, error_data=error_data) from error
    return api_success()


# Refactor later add state for messages, enforce review before allowing to send
@swagger_auto_schema(method="POST",  auto_schema=None,
                     operation_description="Sends an mass email to all users belonging to targeted emails."
                                           "This is mainly used for things like announcing cloud maintenance.",
                     request_body=openapi.Schema(
                         type=openapi.TYPE_OBJECT,
                         properties={
                             "customizations": customizations__body,
                             "Preview": preview__body,
                             "Save": save__body,
                             "Send": send__body
                         }
                     ))
@api_view(['POST'])
@permission_classes((IsAuthenticated, ))
def cloud_notification_action(request):
    can_add = request.user.has_perm('notifications.add_cloudnotification')
    can_change = request.user.has_perm(
        'notifications.change_cloudnotification')
    can_send = request.user.has_perm('notifications.send_cloud_notification')

    customizations = [request.CUSTOMIZATION]
    if 'customizations' in request.data:
        customizations = request.data.getlist('customizations')

    for customization in customizations:
        if not UserGroupsToAssetPermissions.check_customization_permission(request.user,
                                                                           customization,
                                                                           'notifications.send_cloud_notification'):
            raise PermissionDenied

    notification_id = str(update_or_create_notification(
        request.data, customizations))

    if (can_add and not notification_id or can_change) and 'Save' in request.data:
        messages.success(request._request, "Changes have been saved")

    elif (can_add and not notification_id or can_change) and 'Preview' in request.data:
        request_target_users = request.data.getlist(
            'test_users', default=[request.user.id])

        target_users = Account.objects.filter(id__in=request_target_users)
        original_message = format_message(
            CloudNotification.objects.get(id=notification_id))

        for user in target_users:
            message = original_message.copy()
            message["userFullName"] = user.get_full_name()
            notifications_api.send(
                user.email, 'cloud_notification', message,
                customization=user.customization or getattr(request, 'CUSTOMIZATION', customization_ctx.get()))
        messages.success(request._request, "Preview has been sent")

    elif can_send and 'Send' in request.data and notification_id:
        force = 'ignore_subscriptions' in request.data

        notification = CloudNotification.objects.get(id=notification_id)
        message = format_message(notification)

        notification.sent_by = request.user
        notification.sent_date = timezone.now()
        notification.save()
        send_to_all_users.apply_async(args=[notification_id, message, customizations, force],
                                      queue=settings.NOTIFICATIONS_CONFIG['cloud_notification']['queue'])
        messages.success(request._request, "Sending cloud notifications")

    else:
        messages.error(request._request,
                       "Insufficient permission or invalid action")

    if not can_change:
        return redirect('/admin/notifications/')
    return redirect(reverse('admin:notifications_cloudnotification_change', args=[notification_id]))


@api_view(['GET'])
@permission_classes((IsSuperuser, ))
def notification_test(request):
    from notifications import tasks
    from random import seed, randint
    seed()
    tasks.async_task_test.delay(randint(1, 100), randint(1, 5))
    return Response('ok')
