debug: true

postgres:
    host: '$DB_HOST'
    port: '$DB_PORT'
    username: '$DB_USER'
    password: '$DB_PASSWORD'
    database: '$DB_NAME'

# Redis host is always `sqs://` for prod
default_host: 'cloud-test.hdw.mx'
