debug: true

postgres:
    host: '$DB_HOST'
    port: '$DB_PORT'
    username: '$DB_USER'
    password: '$DB_PASSWORD'
    database: '$DB_NAME'

default_host: 'cloud-test.hdw.mx'
redis_host: '$REDIS_HOST'
