include:
  - local: "ci/.shared.yml"

jenkins-build-webadmin:
  extends: .jenkins-builds
  allow_failure: true
  script:
    - |
      set -ex
      if [[ "$CI_COMMIT_REF_PROTECTED" == true ]]; then
        PUBLISH=ON
      else
        PUBLISH=OFF
      fi
    - echo "Running webadmin build"
    - runJenkinsJob.sh gitlab.vms.review.webadmin.build
      "PUBLISH=$PUBLISH"
      "BUILD_DESCRIPTION=$CI_COMMIT_TITLE"
      "GITLAB_BRANCH=$CI_COMMIT_REF_NAME"
      "GITLAB_COMMIT=$CI_COMMIT_SHA"
      "GITLAB_PIPELINE_URL=$CI_PIPELINE_URL"
      "GITLAB_JOB_ID=$CI_JOB_ID"
      "GITLAB_JOB_PROJECT=$CI_PROJECT_PATH"
      "GITLAB_JOB_URL=$CI_JOB_URL"
      "GITLAB_REFSPEC=$CI_COMMIT_SHA"
  rules:
  - if: !reference [ .enable_for_mr_branch ]
    changes: !reference [ .webadmin_changes ]
  - if: !reference [.enable_for_protected_branch]
    changes: !reference [ .webadmin_changes ]

jenkins-build-frontend:
  extends: .jenkins-builds
  script:
    - echo "Running frontend build"
    - runJenkinsJob.sh gitlab.cloud.frontend
      "BRANCH=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
      "BUILD_IDENTITY=$CI_PIPELINE_ID"
      "GITLAB_BRANCH=$CI_COMMIT_REF_NAME"
      "GITLAB_COMMIT=$CI_COMMIT_SHA"
      "GITLAB_PIPELINE_URL=$CI_PIPELINE_URL"
      "GITLAB_JOB_ID=$CI_JOB_ID"
      "GITLAB_JOB_PROJECT=$CI_PROJECT_PATH"
      "GITLAB_JOB_URL=$CI_JOB_URL"
      "REVISION=$CI_COMMIT_SHA"
  rules:
  - if: !reference [ .enable_for_mr ]
    changes: !reference [ .frontend_changes ]

jenkins-build-notification:
  extends: .jenkins-builds
  script:
    - echo "Running notification build"
    - runJenkinsJob.sh gitlab.cloud.notification
      "BRANCH=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
      "BUILD_IDENTITY=$CI_PIPELINE_ID"
      "GITLAB_BRANCH=$CI_COMMIT_REF_NAME"
      "GITLAB_COMMIT=$CI_COMMIT_SHA"
      "GITLAB_PIPELINE_URL=$CI_PIPELINE_URL"
      "GITLAB_JOB_ID=$CI_JOB_ID"
      "GITLAB_JOB_PROJECT=$CI_PROJECT_PATH"
      "GITLAB_JOB_URL=$CI_JOB_URL"
      "REVISION=$CI_COMMIT_SHA"
  rules:
  - if: !reference [ .enable_for_mr]
    changes: !reference [ .notification_changes ]

jenkins-build-channel-partners:
  extends: .jenkins-builds
  script:
    - echo "Running channel partners build"
    - runJenkinsJob.sh gitlab.cloud.channel_partners
      "BRANCH=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
      "BUILD_IDENTITY=$CI_PIPELINE_ID"
      "GITLAB_BRANCH=$CI_COMMIT_REF_NAME"
      "GITLAB_COMMIT=$CI_COMMIT_SHA"
      "GITLAB_PIPELINE_URL=$CI_PIPELINE_URL"
      "GITLAB_JOB_ID=$CI_JOB_ID"
      "GITLAB_JOB_PROJECT=$CI_PROJECT_PATH"
      "GITLAB_JOB_URL=$CI_JOB_URL"
      "REVISION=$CI_COMMIT_SHA"
  rules:
  - if: !reference [ .enable_for_mr ]
    changes: !reference [ .channel_partners_changes ]

cloud-deploy:
  extends: .jenkins-builds
  stage: deploy
  variables:
    CLOUD_BACKEND_IMAGE_TAG: latest
  script:
    - set -ex
    - runJenkinsJob.sh gitlab.cloud.deploy
        "CLOUD_PORTAL_IMAGE_TAG=${CI_PIPELINE_ID}.gitlab"
        "CLOUD_BACKEND_IMAGE_TAG=${CLOUD_BACKEND_IMAGE_TAG}"
        "RELEASE_NAME=${K8S_PRODUCT_RELEASE}"
        "CUSTOMIZATIONS=default" 2>&1 | tee "deploy.log"
    - |
      JENKINS_JOB_URL="$(grep 'Job Url:' "deploy.log" | \
        head -1 | \
        sed 's/\x1b\[[0-9;]*m//g' | \
        awk -F ': ' '{print $2}')"
    - curl
        --fail
        --silent
        --show-error
        -X GET
        --user "jenkins:$(cat "${JENKINS_API_TOKEN_FILE}")"
        "${JENKINS_JOB_URL}artifact/CLOUD_HOST.envvar" > cloud_host.env
  artifacts:
    reports:
      dotenv: cloud_host.env
  environment:
    name: ${K8S_PRODUCT_RELEASE}/${CI_COMMIT_REF_SLUG}
    url: https://${CLOUD_HOST}
    on_stop: cloud-remove-deployment:no-bot-start
  rules:
  - if: !reference [ .functional_tests_required ]
    changes: !reference [ .frontend_changes ]

# stop deployment and clean all data, manual UI action. may be used to verify clean deployment
# may be invoked using manual UI action to verify clean deployment
# also triggered when MR branch deleted (MR merged)
# ref: https://docs.gitlab.com/ee/ci/environments/#stop-an-environment-when-a-branch-is-deleted
#
# The job's name should have `no-bot-start` to prevent triggering by robocat bots
# https://networkoptix.atlassian.net/browse/INFRA-273
cloud-remove-deployment:no-bot-start:
  extends: .jenkins-builds
  stage: deploy
  variables:
    GIT_STRATEGY: none
  secrets:
    GITLAB_API_TOKEN: !reference [.tokens, secrets, GITLAB_API_TOKEN]
  script:
  - |
    GL_ENV_ID="$(curl --silent --header "PRIVATE-TOKEN: ${GITLAB_API_TOKEN}" \
      "${CI_SERVER_URL}/api/v4/projects/${CI_PROJECT_ID}/environments?name=${K8S_PRODUCT_RELEASE}/${CI_COMMIT_REF_SLUG}" |
      jq ".[0].id")"
    CLOUD_URL="$(curl --silent --header "PRIVATE-TOKEN: ${GITLAB_API_TOKEN}" \
      "${CI_SERVER_URL}/api/v4/projects/${CI_PROJECT_ID}/environments/${GL_ENV_ID}" |
      jq -r ".external_url")"
  - runJenkinsJob.sh gitlab.cloud.remove-deployment
    "CLOUD_HOST=${CLOUD_URL}"
  environment:
    name: ${K8S_PRODUCT_RELEASE}/${CI_COMMIT_REF_SLUG}
    action: stop
  rules:
  - if: !reference [ .functional_tests_required ]
    changes: !reference [ .frontend_changes ]
    when: manual
    # ref: https://docs.gitlab.com/ee/ci/yaml/#rulesallow_failure
    # the directive also impacts pipeline stage representation on top level
    # without it, the stage status shown unclear (as a cog) even if deploy successful
    allow_failure: true

create-vms-mr:
  stage: deploy
  extends: .jenkins-builds
  needs: [ "jenkins-build-webadmin" ]
  script:
    - runJenkinsJob.sh gitlab.vms.review.webadmin.create-vms-mr
      "BUILD_DESCRIPTION=$CI_COMMIT_TITLE"
      "CLOUD_PORTAL_COMMIT=$CI_COMMIT_SHA"
      "GITLAB_PIPELINE_URL=$CI_PIPELINE_URL"
      "GITLAB_JOB_ID=$CI_JOB_ID"
      "GITLAB_JOB_PROJECT=$CI_PROJECT_PATH"
      "GITLAB_JOB_URL=$CI_JOB_URL"
  rules:
  - if: !reference [ .enable_for_protected_branch ]
    changes: !reference [ .webadmin_changes ]
