export const LABEL_FORMAT_SECONDS_ONLY = 'ss"s"';
export const LABEL_FORMAT_HOURS_24 = 'HH:MM';
export const LABEL_FORMAT_HOURS_24_SECONDS = 'HH:MM:ss';
export const LABEL_FORMAT_DAY = 'dd';
export const LABEL_FORMAT_DAY_OF_YEAR = 'd mmmm yyyy';
export const LABEL_FORMAT_MONTH = 'mmmm';
export const LABEL_FORMAT_YEAR = 'yyyy';
export const LABEL_FORMAT_MONTH_AND_YEAR = 'mmmm yyyy';

export const LABEL_FORMATS = {
    SECONDS_ONLY: LABEL_FORMAT_SECONDS_ONLY,
    HOURS_24: LABEL_FORMAT_HOURS_24,
    HOURS_24_SECONDS: LABEL_FORMAT_HOURS_24_SECONDS,
    DAY: LABEL_FORMAT_DAY,
    DAY_OF_YEAR: LABEL_FORMAT_DAY_OF_YEAR,
    MONTH: LABEL_FORMAT_MONTH,
    YEAR: LABEL_FORMAT_YEAR,
    MONTH_AND_YEAR: LABEL_FORMAT_MONTH_AND_YEAR,
};
