*** Variables ***
${CAMERAS LINK}                              //nx-menu//a[@id="cameras"]
${EDITABLE TITLE}                            //h2[@id="editable-title"]
${CAMERAS VIEW BUTTON}                       //h4//button[@id="view-camera"]
${CAMERAS DETAILED INFO BUTTON}              //h4//button[@id="detailed-info"]
${ASPECT RATIO DROPDOWN}                     //button[@id="aspect-ratios"]
${ROTATION DROPDOWN}                         //button[@id="rotations"]
${ENABLE AUDIO CHECKBOX}                     //nx-section//nx-checkbox[@name="audioEnabled"]
${EDIT CREDENTIALS BUTTON}                   //nx-section//button[@id="update-credentials"]
${EDIT CREDENTIALS FORM}                     //form[@name="updateForm"]
${EDIT CREDENTIALS LOGIN INPUT}              ${EDIT CREDENTIALS FORM}//input[@id="cameraLoginCredentials"]
${EDIT CREDENTIALS PASSWORD INPUT}           ${EDIT CREDENTIALS FORM}//input[@id="cameraPasswordCredentials"]
${EDIT CREDENTIALS X BUTTON}                 ${EDIT CREDENTIALS FORM}//button[contains(@class,"close")]
${EDIT CREDENTIALS CANCEL BUTTON}            ${EDIT CREDENTIALS FORM}//button[contains(text(),"${CANCEL BUTTON TEXT}")]
${EDIT CREDENTIALS SAVE BUTTON}              ${EDIT CREDENTIALS FORM}//button[contains(text(),"${SAVE BUTTON TEXT}")]
${RECORDING CHECK BOX}                       //nx-switch/div[@id="recording"]
${ENABLED RECORDING SLIDER}                  //span[@class="slider round"]
${RECORD ALWAYS RADIO BUTTON}                //nx-radio//input[@id="Record always"]
${RECORD MOTION RADIO BUTTON}                //nx-radio//input[@id="Record only motion"]
${RECORD MOTION LOW QUALITY RADIO BUTTON}    //nx-radio//input[@id="Motion + low-res"]
${FPS INPUT}                                 //input[@name="fps"]
${QUALITY DROPDOWN}                          //button[@id="recording-quality"]
${DOT-MENU}                                  //button[@class="dot-menu"]
${ENABLE MOTION DETECTION BUTTON}            //button[@id="enable-motion-detection"]
${DISABLE MOTION DETECTION LINK}             ${DOT-MENU}/following-sibling::div/ul//a[@id="disable-motion"]
${CANVAS}                                    //nx-motion-detection-overlay/canvas
${OFFLINE PLACEHOLDER IAMGE}                 //nx-page-placeholder//div[contains(@class,"placeholder-icon") and @name="NO_SETTINGS"]
${OFFLINE TITLE}                             //nx-page-placeholder//h2[contains(@class,"placeholder-title") and @name="NO_SETTINGS"]
${OFFLINE MESSAGE}                           //nx-page-placeholder//div[contains(@class,"placeholder-message") and @name="NO_SETTINGS"]
${NO CAMERAS PLACEHOLDER IMAGE}              //nx-page-placeholder//div[contains(@class,"placeholder-icon") and @name="NO_CAMS"]
${NO CAMERAS TITLE}                          //nx-page-placeholder//h2[contains(@class,"placeholder-title") and @name="NO_CAMS"]
${NO CAMERAS MESSAGE}                        //nx-page-placeholder//div[contains(@class,"placeholder-message") and @name="NO_CAMS"]
${RECORDING SVG}                             //svg-icon[@data-src="/static/images/icons/standard/camera_recording.svg"]
${OFFLINE SVG}                               //svg-icon[@data-src="/static/images/icons/standard/camera_offline.svg"]
${UNAUTH SVG}                                //svg-icon[@data-src="/static/images/icons/standard/camera_unauthorized.svg"]
${NO IMAGE PLACEHOLDER}                      //nx-health-image//div[contains(text(),"${NO IMAGE TEXT}" )]
${CAMERA ERROR BAR}                          //nx-alert-block/div[@class="card simple-error"]
${CAMERA ERROR ICON}                         ${CAMERA ERROR BAR}//svg-icon[@data-src="/static/images/icons/error.svg"]
${CAMERA ERROR TEXT}                         ${CAMERA ERROR BAR}//div[@class="warning-margin"]/span