version: '3'
services:
  webapp:
    image: mediaserver
    ports:
      - "7003:7001"
    network_mode: "bridge"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./video:/dock
      - ./data/:/opt/networkoptix/mediaserver/var
      - ~/develop/devtools/util/:/scripts
    tmpfs:
      - /run
      - /run/lock
