include:
  - local: "ci/.shared.yml"

.functional_tests_required: '( $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" ||
  $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^releases_23\.3\./ )'

.require_testing:
  - cloud/**/*
  - front_end/**/*
  - ft/**/*

FT / VMS 5.1:
  stage: 'ft (#ask-ft)'
  needs: [ 'cloud-deploy' ]
  script: [ 'dev-cloud-portal-gitlab-vms-5.1' ]
  tags: [ 'cloud_portal_tests' ]
  timeout: '180m'
  rules:
    - if: !reference [ .functional_tests_required ]
      # noinspection YAMLSchemaValidation
      changes: !reference [ .require_testing ]

FT / VMS 6.0:
  stage: 'ft (#ask-ft)'
  needs: [ 'cloud-deploy' ]
  script: [ 'dev-cloud-portal-gitlab-vms-6.0' ]
  tags: [ 'cloud_portal_tests' ]
  timeout: '180m'
  rules:
    - if: !reference [ .functional_tests_required ]
      # noinspection YAMLSchemaValidation
      changes: !reference [ .require_testing ]

WebAdmin:
  stage: 'ft (#ask-ft)'
  needs: [ 'jenkins-build-webadmin' ]
  script: [ 'dev-cloud-portal-webadmin-develop' ]
  tags: [ 'cloud_portal_tests' ]
  timeout: '180m'
  rules:
    - if: !reference [ .functional_tests_required ]
      # noinspection YAMLSchemaValidation
      changes: !reference [ .webadmin_changes ]
