include:
  - local: "ci/.shared.yml"

.functional_tests_required: '( $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" ||
  $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^releases_23\.3\./ )'

.require_testing:
  - cloud/**/*
  - front_end/**/*
  - ft/**/*

FT / VMS 5.1:
 stage: 'ft (#ask-ft)'
 needs: [ 'cloud-deploy' ]
 script: [ 'cloud_portal_tests config:cloud_installers_5_1_url $CLOUD_HOST $CI_PIPELINE_URL' ]
 tags: [ 'cloud_portal_tests' ]
 timeout: '180m'
 rules:
   - if: !reference [ .functional_tests_required ]
     # noinspection YAMLSchemaValidation
     changes: !reference [ .require_testing ]

FT / VMS 6.0:
  stage: 'ft (#ask-ft)'
  needs: [ 'cloud-deploy' ]
  script: [ 'cloud_portal_tests config:cloud_installers_6_0_url $CLOUD_HOST $CI_PIPELINE_URL' ]
  tags: [ 'cloud_portal_tests' ]
  timeout: '180m'
  rules:
    - if: !reference [ .functional_tests_required ]
      # noinspection YAMLSchemaValidation
      changes: !reference [ .require_testing ]

WebAdmin:
  stage: 'ft (#ask-ft)'
  needs: [ 'jenkins-build-webadmin' ]
  script: [ 'web_admin_tests $ARTIFACTORY_WEBADMIN_URL branch:master' ]
  tags: [ 'cloud_portal_tests' ]
  timeout: '180m'
  rules:
    - if: !reference [ .functional_tests_required ]
      # noinspection YAMLSchemaValidation
      changes: !reference [ .webadmin_changes ]
