export type ComplicatedObject = {
    userId: string;
    email: string;
    fullName: string;
    accessLevel: string[];
    roles: string[];
    title: string;
    created: string;
};

export const ALL_STATES = [
    'Alabama',
    'Alaska',
    'American Samoa',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'District Of Columbia',
    'Federated States Of Micronesia',
    'Florida',
    'Georgia',
    'Guam',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Marshall Islands',
];

export const ALL_PEOPLE: ComplicatedObject[] = [
    {
        userId: 'abc1@networkoptix.com',
        email: 'abc1@networkoptix.com',
        fullName: 'Person 1',
        accessLevel: ['N/A'],
        roles: ['Administrator', 'Manager', 'Engineer', 'User', 'QA'],
        title: '',
        created: '2023-08-24T19:14:46.748Z',
    },
    {
        userId: 'abc2@networkoptix.com',
        email: 'abc2@networkoptix.com',
        fullName: 'Person 2',
        accessLevel: ['N/A'],
        roles: ['Engineer', 'User'],
        title: '',
        created: '2023-08-24T19:14:46.748Z',
    },
    {
        userId: 'abc3@networkoptix.com',
        email: 'abc3@networkoptix.com',
        fullName: 'Person 3',
        accessLevel: ['N/A'],
        roles: ['QA'],
        title: '',
        created: '2023-08-24T19:14:46.748Z',
    },
    {
        userId: 'abc4@networkoptix.com',
        email: 'abc4@networkoptix.com',
        fullName: 'Person 4',
        accessLevel: ['N/A'],
        roles: ['Engineer', 'Manager'],
        title: '',
        created: '2023-08-24T19:14:46.748Z',
    },
    {
        userId: 'abc5@networkoptix.com',
        email: 'abc5@networkoptix.com',
        fullName: 'Person 5',
        accessLevel: ['N/A'],
        roles: ['Administrator'],
        title: '',
        created: '2023-08-24T19:14:46.748Z',
    },
    {
        userId: 'abc6@networkoptix.com',
        email: 'abc6@networkoptix.com',
        fullName: 'Person 6',
        accessLevel: ['N/A'],
        roles: ['Manager'],
        title: '',
        created: '2023-08-24T19:14:46.748Z',
    },
    {
        userId: 'abc7@networkoptix.com',
        email: 'abc7@networkoptix.com',
        fullName: 'Person 7',
        accessLevel: ['N/A'],
        roles: ['Engineer', 'Administrator'],
        title: '',
        created: '2023-08-24T19:14:46.748Z',
    },
    {
        userId: 'abc8@networkoptix.com',
        email: 'abc8@networkoptix.com',
        fullName: 'Person 8',
        accessLevel: ['N/A'],
        roles: ['Administrator', 'Manager'],
        title: '',
        created: '2023-08-24T19:14:46.748Z',
    },
    {
        userId: 'abc9@networkoptix.com',
        email: 'abc9@networkoptix.com',
        fullName: 'Person 9',
        accessLevel: ['N/A'],
        roles: ['Engineer', 'QA'],
        title: '',
        created: '2023-08-24T19:14:46.748Z',
    },
    {
        userId: 'abc10@networkoptix.com',
        email: 'abc10@networkoptix.com',
        fullName: 'Person 10',
        accessLevel: ['N/A'],
        roles: [],
        title: '',
        created: '2023-08-24T19:14:46.748Z',
    },
    {
        userId: 'abc11@networkoptix.com',
        email: 'abc11@networkoptix.com',
        fullName: 'Person 11',
        accessLevel: ['N/A'],
        roles: ['Administrator'],
        title: '',
        created: '2023-08-24T19:14:46.748Z',
    },
    {
        userId: 'abc12@networkoptix.com',
        email: 'abc12@networkoptix.com',
        fullName: 'Person 12',
        accessLevel: ['N/A'],
        roles: ['Security'],
        title: '',
        created: '2023-08-24T19:14:46.748Z',
    },
    {
        userId: 'abc13@networkoptix.com',
        email: 'abc13@networkoptix.com',
        fullName: 'Person 13',
        accessLevel: ['N/A'],
        roles: ['Security', 'Engineer'],
        title: '',
        created: '2023-08-24T19:14:46.748Z',
    },
];
