# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-09 09:04
from django.db import connection, migrations, ProgrammingError

# Keeping this migration just to keep current graph consistent with history on prod

# Keeping below query commented out for historical purposes. If we wipe portal db but keep clouddb it may be relevant.

# import logging
#
# logger = logging.getLogger(__name__)
#
# """UPDATE cloudportal.api_account db1
#    JOIN clouddb.account db2
#    JOIN clouddb.account_status db3
#    ON db1.email=db2.email AND db2.status_code=db3.code
#    SET db1.activated_date=db1.created_date
#    WHERE db1.activated_date is null AND db3.description="Activated";"""
#
#
# def updateActivatedDate(apps, schema_editor):
#     cursor = connection.cursor()
#     try:
#         cursor.execute('''UPDATE cloudportal.api_account db1
#                           JOIN clouddb.account db2
#                           JOIN clouddb.account_status db3
#                           ON db1.email=db2.email AND db2.status_code=db3.code
#                           SET db1.activated_date=db1.created_date
#                           WHERE db1.activated_date is NULL AND db3.description="activated";''')
#
#     except ProgrammingError as error:
#         logger.warning(error)
#     except Exception as error:
#         logger.error(error)
#         raise error


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0013_auto_20171216_0210'),
    ]

    operations = [
    ]
