# Generated by Django 2.2 on 2019-09-30 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_account_subscribe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': (('can_view_release', 'Can view releases and patches'), ('invite_users', 'Invite users'), ('ignore_exceptions', 'Downgrades log level of exceptions to INFO'))},
        ),
    ]
