# Generated by Django 2.2 on 2020-08-20 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_remove_group_all_assets'),
        ('api', '0024_auto_20190930_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_assets', models.BooleanField(default=False)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='auth.Group')),
            ],
        ),
    ]
