# Generated by Django 2.2 on 2020-08-20 02:16

from django.db import migrations


def generate_group_options(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    GroupOptions = apps.get_model('api', 'GroupOptions')

    for group in Group.objects.filter(options=None):
        GroupOptions.objects.create(group=group)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_groupoptions'),
    ]

    operations = [
        migrations.RunPython(generate_group_options, lambda x, y: None)
    ]
