# Generated by Django 2.2 on 2021-01-15 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_create_group_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCustomProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.SlugField()),
                ('json_data', jsonfield.fields.JSONField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Custom Property',
                'verbose_name_plural': 'Account Custom Properties',
            },
        ),
    ]
