# Generated by Django 2.2.20 on 2021-07-01 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20210126_2358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': (('can_view_release', 'Can view releases and patches'), ('invite_users', 'Invite users'), ('ignore_exceptions', 'Downgrades log level of exceptions to INFO'), ('custom_clients', 'Can create/edit and download custom clients'))},
        ),
    ]
