# Generated by Django 2.2.24 on 2021-07-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20210701_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cookie_reviewed',
            field=models.BooleanField(default=False, help_text='If true then the user has accepted the cookie policy and the cookie banner will not show up.'),
        ),
    ]
