# Generated by Django 2.2.24 on 2021-07-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_account_cookie_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cookie_reviewed',
            field=models.BooleanField(default=False, help_text='If true then the user has accepted the cookie policy and the cookie banner will not appear.'),
        ),
    ]
