# Generated by Django 2.2.24 on 2021-09-25 05:35
from django.db import migrations
from django.conf import settings
from cms.models import AssetType


def add_all_releases_group(apps, schema_editor):
    Group = apps.get_model(
        'auth', 'Group')
    Permission = apps.get_model(
        'auth', 'Permission')
    ContentType = apps.get_model(
        'contenttypes', 'ContentType')
    GroupOptions = apps.get_model(
        'api', 'GroupOptions')
    Account = apps.get_model(
        'api', 'Account')
    Asset = apps.get_model(
        'cms', 'Asset')
    UserGroupsToAssetPermissions = apps.get_model(
        'cms', 'UserGroupsToAssetPermissions')

    cloud_portal = Asset.objects.filter(
        customizations__name__in=[settings.CUSTOMIZATION],
        asset_type__type=AssetType.ASSET_TYPES.cloud_portal
    ).first()

    all_releases_group, _ = Group.objects.get_or_create(
        name='Nx Internal - All releases access')

    GroupOptions.objects.get_or_create(
        group=all_releases_group)

    permission, _ = Permission.objects.get_or_create(
        name='User can view all releases', codename='user_can_view_all_releases', content_type=ContentType.objects.get_for_model(Account))

    all_releases_group.permissions.add(permission)

    UserGroupsToAssetPermissions.objects.get_or_create(
        group=all_releases_group, asset=cloud_portal)

    for user in Account.objects.filter(email__endswith=settings.SUPERUSER_DOMAIN):
        user.groups.add(all_releases_group)
        if not user.is_staff:
            user.is_staff = True
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20210726_2259'),
        ('cms', '0140_add_cloud_host_field')
    ]

    operations = [
        migrations.RunPython(add_all_releases_group, migrations.RunPython.noop)
    ]
