# Generated by Django 4.2.11 on 2024-04-11 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_all_releases_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='cookie_reviewed',
        ),
    ]
